# -*- coding: utf-8 -*-
# debut entete
import Accas
from Accas import AU_MOINS_UN,UN_PARMI,EXCLUS,PRESENT_PRESENT
from Accas import ENSEMBLE,PRESENT_ABSENT
from Accas import JDC_CATA,NIVEAU
from Accas import OPER,PROC,MACRO,FORM
from Accas import SIMP,FACT,BLOC
from Accas import EVAL,PARAMETRE,COMMENTAIRE,PARAMETRE_EVAL,COMMANDE_COMM
from Accas import ASSD,CO,GEOM,fonction,geom,assd
#
__version__="$Name:  $"
__Id__="$Id: cata_saturne2.py,v 1.2 2003/10/16 14:31:22 eficas Exp $"
#

import ops

JdC = JDC_CATA(code='SATURNE',
               execmodul=None,
               regles = (AU_MOINS_UN('CALCUL_SATURNE'),),
              )

# P. RASCLE MMN
# remarques diverses sur le catalogue Saturne
# - dans les blocs, il faut au moins un mot clé de statut obligatoire
# probleme de rafraichissement des blocs dépendants quand la valeur d'un mot cle global (ITURB) passe de 1 à 0

class sonde(ASSD):pass
class varsca(ASSD):pass
class flusca(ASSD):pass
class varpre(ASSD):pass
class varvitx(ASSD):pass
class varvity(ASSD):pass
class varvitz(ASSD):pass
class eturb(ASSD):pass
class dturb(ASSD):pass
class tsr11(ASSD):pass
class tsr22(ASSD):pass
class tsr33(ASSD):pass
class tsr12(ASSD):pass
class tsr13(ASSD):pass
class tsr23(ASSD):pass
class resti(ASSD):pass

# fin entete

INCLUDE=MACRO(nom="INCLUDE",op=-1,docu="U4.13.01-e",
             fr="Débranchement vers un fichier de commandes secondaires",
             sd_prod=ops.INCLUDE,op_init=ops.INCLUDE_context,fichier_ini=1,
         UNITE = SIMP(statut='o',typ='I'),
         INFO  = SIMP(statut='f',typ='I',defaut=1,into=(1,2)),
);

POURSUITE=MACRO(nom="POURSUITE",op=0,repetable='n',fr="Poursuite d une étude",
                docu="U4.11.03-f1",sd_prod = ops.POURSUITE,
                op_init = ops.POURSUITE_context,fichier_ini = 1,
         HDF             =FACT(statut='f',min=1,max=1,
           FICHIER         =SIMP(fr="nom du fichier hdf associe",statut='o',typ='TXM'),
         ),
         PAR_LOT         =SIMP(fr="mode de traitement des commandes",statut='f',typ='TXM',
                           into=("OUI","NON"),defaut="OUI"),
         BASE            =FACT(fr="définition des parmètres associés aux bases JEVEUX",
                               statut='f',min=1,max=3,
           FICHIER         =SIMP(fr="nom de la base",statut='o',typ='TXM'),
           TITRE           =SIMP(statut='f',typ='TXM'),
           CAS             =SIMP(statut='f',typ='TXM'),
           NMAX_ENRE       =SIMP(fr="nombre maximum d enregistrements",statut='f',typ='I'),
           LONG_ENRE       =SIMP(fr="longueur des enregistrements",statut='f',typ='I'),
           LONG_REPE       =SIMP(fr="longueur du répertoire",statut='f',typ='I'),
         ),
         IMPRESSION      =FACT(statut='f',min=1,max=3,
           FICHIER         =SIMP(statut='o',typ='TXM'),
           UNITE           =SIMP(statut='o',typ='I'),
         ),
         CATALOGUE       =FACT(statut='f',min=1,max=10,
           FICHIER         =SIMP(statut='o',typ='TXM'),
           TITRE           =SIMP(statut='f',typ='TXM'),
           UNITE           =SIMP(statut='f',typ='I'),
         ),
         DEBUG           =FACT(fr="option de déboggage reservée aux développeurs",
                               statut='f',min=1,max=1,
           JXVERI          =SIMP(fr="vérifie l intégrité de la segmentation mémoire",
                                 statut='f',typ='TXM',into=('OUI','NON'),defaut='NON'),
           JEVEUX          =SIMP(fr="force les déchargement sur disque",
                                 statut='f',typ='TXM',into=('OUI','NON'),defaut='NON'),
           ENVIMA          =SIMP(fr="imprime les valeurs définies dans ENVIMA",
                                 statut='f',typ='TXM',into=('TES',)),
         ),
         MEMOIRE         =FACT(fr="mode de gestion mémoire utilisé",statut='f',min=1,max=1,
           GESTION         =SIMP(statut='f',typ='TXM',into=('COMPACTE','RAPIDE'),defaut='RAPIDE'),
           TYPE_ALLOCATION =SIMP(statut='f',typ='I',into=(1,2,3,4),defaut=1),
           TAILLE          =SIMP(statut='f',typ='I'),
           TAILLE_BLOC     =SIMP(statut='f',typ='R',defaut=800.),
           PARTITION       =SIMP(statut='f',typ='R' ),
         ),
         CODE            =FACT("définition d un nom pour l'esemble d'une étude",
                               statut='f',min=1,max=1,
           NOM             =SIMP(statut='o',typ='TXM'),
           UNITE           =SIMP(statut='f',typ='I',defaut=15),
         ),
)  ;

FORMULE = FORM( nom='FORMULE',op=-5,sd_prod=fonction,
                fr="Définition d une fonction",reentrant = 'n',
                regles=(UN_PARMI('REEL','ENTIER','COMPLEXE'),),
                REEL = SIMP(typ = 'shell',max=1),
                ENTIER = SIMP(typ = 'shell',max=1),
                COMPLEXE = SIMP(typ = 'shell',max=1),
) ;

DEFI_SONDE = OPER(nom="DEFI_SONDE",op= 1,sd_prod=sonde,
     docu="U2D1",
     fr="définition d'une sonde historique avec ses coordonnées",
                  X = SIMP(statut ='o',typ='R',
                           fr="coordonnée X de la sonde"),
                  Y = SIMP(statut ='o',typ='R',
                           fr="coordonnée Y de la sonde"),
                  Z = SIMP(statut ='o',typ='R',
                           fr="coordonnée Z de la sonde")
                 );

def defi_scala_prod(**args):
   return varsca

DEFI_SCALA = OPER(nom="DEFI_SCALA",op=2,sd_prod=defi_scala_prod,
fr="définition d'une inconnue scalaire avec ses paramètres physico numériques",
                  NUMERIC = FACT(statut='o',max=01,
                                fr="propriétés numériques liées à l'inconnue",
                                    ICONV  = SIMP(statut='o',typ='I',defaut=1,into=(0,1),
                                                  fr="indicateur de convection"),
                                    ISTAT  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="présence terme instationnaire dans les matrices"),
                                    IDIFF  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="diffusion"),
                                    IDIRCL = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="décalage du spectre des valeurs propres en l'absence de Dirichlet"),
                                    SCHEMA_CONVECTIF = BLOC(condition="ICONV == 1", fr ="ordre du schéma convectif",
                                                            BLENCV = SIMP(statut='o',typ='R',defaut=0,val_min=0,val_max=1,
                                                                          fr="pourcentage schéma convectif au second ordre"),
                                                            ISCHCV = SIMP(statut='f',typ='I',defaut=0,into=(0,1),
                                                                          fr ="type schéma convectif au second ordre 1 : centré")
                                                            ),
                                    NITMAX = SIMP(statut='f',typ='I',defaut=10000,val_min=0,
                                                  fr="nombre max d'itération pour la résolution des systèmes linéaires"),
                                    EPSILO = SIMP(statut='f',typ='R',defaut=1.e-4,val_min=0,
                                                  fr="précision relative pour la résolution des systèmes linéaires"),
                                    IMLIGR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,-1,0,1),
                                                  fr="type de limitation des gradients"),
                                    NSWRGR = SIMP(statut='f',typ='I',defaut=100,val_min=0,
                                                  fr="reconstruction des gradients"),
                                    NSWRSM = SIMP(statut='f',typ='I',defaut=2,val_min=0,
                                                  fr="nombre d'itérations pour la reconstruction des seconds membres"),
                                    CLIMGR = SIMP(statut='f',typ='R',defaut=1.5,val_min=0,
                                                  fr="facteur de limitation des gradients"),
                                    EPSRGR = SIMP(statut='f',typ='R',defaut=1.e-5,val_min=0,
                                                  fr="précision relative pour la reconstruction itérative des gradients")
                                 ),
                  RESTITUE = FACT(statut='o',max=01,
                                  fr = "Description de la grandeur restituée",
                                  NOMVAR = SIMP(statut='o',typ='TXM',fr = "nom de la grandeur restituée"),
                                  ICHRVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "post-traitement (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  ILISVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "impression dans CR exécution (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  IHISVR = SIMP(statut='f',typ=sonde,min=0,max='**',
                                                fr = "inventaire des sondes utilisées pour la grandeur scalaire")
                                  ),
                  MODELE = FACT(statut='o',max=01,
                                fr="modélisation",
                                VALREF = SIMP(statut='o',typ='R',fr="valeur de référence (température, masse volumique...)"),
                                SCAMIN = SIMP(statut='f',typ='R',defaut=1.e12,fr="valeur minimale pour le scalaire"),
                                SCAMAX = SIMP(statut='f',typ='R',defaut=-1.e12,fr="valeur maximale pour le scalaire"),
                                SIGMAS = SIMP(statut='f',typ='R',val_min=0,defaut=1,fr="nombre de Prandtl pour le scalaire"),
                                VISLS0 = SIMP(statut='o',typ='R',fr="valeur de référence de la viscosité associée au scalaire"),
                                IVISLS = SIMP(statut='f',typ='I',defaut=0,into=(0,1),fr="viscosité variable")
                                )
                 );

DEFI_FLUSCA = OPER(nom="DEFI_FLUSCA",op=2,sd_prod=flusca,fr="définition des fluctuations d'une inconnue scalaire avec ses paramètres physico numériques",
                  VARFL  = SIMP(statut='o',typ=varsca,fr="scalaire associé au calcul de la variance des fluctuations"),
                  NUMERIC = FACT(statut='o',max=01,
                                fr="propriétés numériques liées à l'inconnue",
                                    ICONV  = SIMP(statut='o',typ='I',defaut=1,into=(0,1),
                                                  fr="indicateur de convection"),
                                    ISTAT  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="présence terme instationnaire dans les matrices"),
                                    IDIFF  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="diffusion"),
                                    IDIRCL = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="décalage du spectre des valeurs propres en l'absence de Dirichlet"),
                                    SCHEMA_CONVECTIF = BLOC(condition="ICONV == 1", fr ="ordre du schéma convectif",
                                                            BLENCV = SIMP(statut='o',typ='R',defaut=0,val_min=0,val_max=1,
                                                                          fr="pourcentage schéma convectif au second ordre"),
                                                            ISCHCV = SIMP(statut='f',typ='I',defaut=0,into=(0,1),
                                                                          fr ="type schéma convectif au second ordre 1 : centré")
                                                            ),
                                    NITMAX = SIMP(statut='f',typ='I',defaut=10000,val_min=0,
                                                  fr="nombre max d'itération pour la résolution des systèmes linéaires"),
                                    EPSILO = SIMP(statut='f',typ='R',defaut=1.e-4,val_min=0,
                                                  fr="précision relative pour la résolution des systèmes linéaires"),
                                    IMLIGR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,-1,0,1),
                                                  fr="type de limitation des gradients"),
                                    NSWRGR = SIMP(statut='f',typ='I',defaut=100,val_min=0,
                                                  fr="reconstruction des gradients"),
                                    NSWRSM = SIMP(statut='f',typ='I',defaut=2,val_min=0,
                                                  fr="nombre d'itérations pour la reconstruction des seconds membres"),
                                    CLIMGR = SIMP(statut='f',typ='R',defaut=1.5,val_min=0,
                                                  fr="facteur de limitation des gradients"),
                                    EPSRGR = SIMP(statut='f',typ='R',defaut=1.e-5,val_min=0,
                                                  fr="précision relative pour la reconstruction itérative des gradients")
                                 ),
                  RESTITUE = FACT(statut='o',max=01,
                                  fr = "Description de la grandeur restituée",
                                  NOMVAR = SIMP(statut='o',typ='TXM',fr = "nom de la grandeur restituée"),
                                  ICHRVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "post-traitement (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  ILISVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "impression dans CR exécution (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  IHISVR = SIMP(statut='f',typ=sonde,min=0,max='**',
                                                fr = "inventaire des sondes utilisées pour la grandeur scalaire")
                                  ),
                  MODELE = FACT(statut='o',max=01,
                                fr="modélisation",
                                VALREF = SIMP(statut='o',typ='R',fr="valeur de référence (température, masse volumique...)"),
                                SCAMIN = SIMP(statut='f',typ='R',defaut=1.e12,fr="valeur minimale pour le scalaire"),
                                SCAMAX = SIMP(statut='f',typ='R',defaut=-1.e12,fr="valeur maximale pour le scalaire"),
                                SIGMAS = SIMP(statut='f',typ='R',val_min=0,defaut=1,fr="nombre de Prandtl pour le scalaire"),
                                VISLS0 = SIMP(statut='o',typ='R',fr="valeur de référence de la viscosité associée au scalaire"),
                                IVISLS = SIMP(statut='f',typ='I',defaut=0,into=(0,1),fr="viscosité variable"),
                                RVARFL = SIMP(statut='o',typ='R',val_min=0,defaut=0.8,
                                                       fr="nombre de Prandtl pour la variance des fluctuations du scalaire")
                                )
                  );

DEFI_PRESSION = OPER(nom="DEFI_PRESSION",op=2,sd_prod=varpre,fr="définition del'inconnue pression avec ses paramètres physico numériques",
                   NUMERIC = FACT(statut='o',max=01,
                                  fr="propriétés de l'équation de pression",
                                  ICONV  = SIMP(statut='o',typ='I',defaut=0,into=(0,1),
                                                fr="indicateur de convection"),
                                  ISTAT  = SIMP(statut='f',typ='I',defaut=0,into=(0,1),
                                                fr="présence terme instationnaire dans les matrices"),
                                  IDIFF  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                fr="diffusion"),
                                  IDIRCL = SIMP(statut='f',typ='I',defaut=0,into=(0,1),
                                                fr="décalage du spectre des valeurs propres en l'absence de Dirichlet"),
                                  SCHEMA_CONVECTIF = BLOC(condition="ICONV == 1", fr ="ordre du schéma convectif",
                                                          BLENCV = SIMP(statut='o',typ='R',defaut=0,val_min=0,val_max=1,
                                                                        fr="pourcentage schéma convectif au second ordre"),
                                                          ISCHCV = SIMP(statut='f',typ='I',defaut=0,into=(0,1),
                                                                        fr ="type schéma convectif au second ordre 1 : centré")
                                                          ),
                                  NITMAX = SIMP(statut='f',typ='I',defaut=10000,val_min=0,
                                                fr="nombre max d'itération pour la résolution des systèmes linéaires"),
                                  EPSILO = SIMP(statut='f',typ='R',defaut=1.e-4,val_min=0,
                                                fr="précision relative pour la résolution des systèmes linéaires"),
                                  IMLIGR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,-1,0,1),
                                                fr="type de limitation des gradients"),
                                  NSWRGR = SIMP(statut='f',typ='I',defaut=100,val_min=0,
                                                fr="reconstruction des gradients"),
                                  NSWRSM = SIMP(statut='f',typ='I',defaut=2,val_min=0,
                                                fr="nombre d'itérations pour la reconstruction des seconds membres"),
                                  CLIMGR = SIMP(statut='f',typ='R',defaut=1.5,val_min=0,
                                                fr="facteur de limitation des gradients"),
                                  EPSRGR = SIMP(statut='f',typ='R',defaut=1.e-5,val_min=0,
                                                fr="précision relative pour la reconstruction itérative des gradients")
                                  ),
                  RESTITUE = FACT(statut='o',max=01,
                                  fr = "Description de la grandeur restituée",
                                  NOMVAR = SIMP(statut='o',typ='TXM',fr = "nom de la grandeur restituée",
                                                defaut="Pression"),
                                  ICHRVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "post-traitement (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  ILISVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "impression dans CR exécution (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  IHISVR = SIMP(statut='f',typ=sonde,min=0,max='**',
                                                fr = "inventaire des sondes utilisées pour la grandeur")
                                  ),
                  MODELE = FACT(statut='o',max=01,
                                fr="modélisation",
                                VALREF = SIMP(statut='o',typ='R',fr="valeur de référence (température, masse volumique...)"),
                                SCAMIN = SIMP(statut='f',typ='R',defaut=1.e12,fr="valeur minimale pour la grandeur"),
                                SCAMAX = SIMP(statut='f',typ='R',defaut=-1.e12,fr="valeur maximale pour la grandeur"),
                                SIGMAS = SIMP(statut='f',typ='R',val_min=0,defaut=1,fr="nombre de Prandtl pour la grandeur"),
                                VISLS0 = SIMP(statut='o',typ='R',fr="valeur de référence de la viscosité associée à la grandeur"),
                                IVISLS = SIMP(statut='f',typ='I',defaut=0,into=(0,1),fr="viscosité variable")
                                )
                    );

DEFI_VITX = OPER(nom="DEFI_VITX",op=2,sd_prod=varvitx,fr="définition de l'inconnue vitesse X avec ses paramètres physico numériques",
                   NUMERIC = FACT(statut='o',max=01,
                                  fr="propriétés de l'équation de vitesse X",
                                  ICONV  = SIMP(statut='o',typ='I',defaut=1,into=(0,1),
                                                fr="indicateur de convection"),
                                  ISTAT  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                fr="présence terme instationnaire dans les matrices"),
                                  IDIFF  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                fr="diffusion"),
                                  IDIRCL = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                fr="décalage du spectre des valeurs propres en l'absence de Dirichlet"),
                                  SCHEMA_CONVECTIF = BLOC(condition="ICONV == 1", fr ="ordre du schéma convectif",
                                                          BLENCV = SIMP(statut='o',typ='R',defaut=0,val_min=0,val_max=1,
                                                                        fr="pourcentage schéma convectif au second ordre"),
                                                          ISCHCV = SIMP(statut='f',typ='I',defaut=0,into=(0,1),
                                                                        fr ="type schéma convectif au second ordre 1 : centré")
                                                          ),
                                  NITMAX = SIMP(statut='f',typ='I',defaut=10000,val_min=0,
                                                fr="nombre max d'itération pour la résolution des systèmes linéaires"),
                                  EPSILO = SIMP(statut='f',typ='R',defaut=1.e-4,val_min=0,
                                                fr="précision relative pour la résolution des systèmes linéaires"),
                                  IMLIGR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,-1,0,1),
                                                fr="type de limitation des gradients"),
                                  NSWRGR = SIMP(statut='f',typ='I',defaut=100,val_min=0,
                                                fr="reconstruction des gradients"),
                                  NSWRSM = SIMP(statut='f',typ='I',defaut=2,val_min=0,
                                                fr="nombre d'itérations pour la reconstruction des seconds membres"),
                                  CLIMGR = SIMP(statut='f',typ='R',defaut=1.5,val_min=0,
                                                fr="facteur de limitation des gradients"),
                                  EPSRGR = SIMP(statut='f',typ='R',defaut=1.e-5,val_min=0,
                                                fr="précision relative pour la reconstruction itérative des gradients")
                                  ),
                  RESTITUE = FACT(statut='o',max=01,
                                  fr = "Description de la grandeur restituée",
                                  NOMVAR = SIMP(statut='o',typ='TXM',fr = "nom de la grandeur restituée",
                                                defaut="vitesse_u1"),
                                  ICHRVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "post-traitement (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  ILISVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "impression dans CR exécution (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  IHISVR = SIMP(statut='f',typ=sonde,min=0,max='**',
                                                fr = "inventaire des sondes utilisées pour la grandeur")
                                  ),
                  MODELE = FACT(statut='o',max=01,
                                fr="modélisation",
                                VALREF = SIMP(statut='o',typ='R',fr="valeur de référence (température, masse volumique...)"),
                                SCAMIN = SIMP(statut='f',typ='R',defaut=1.e12,fr="valeur minimale pour la grandeur"),
                                SCAMAX = SIMP(statut='f',typ='R',defaut=-1.e12,fr="valeur maximale pour la grandeur"),
                                SIGMAS = SIMP(statut='f',typ='R',val_min=0,defaut=1,fr="nombre de Prandtl pour la grandeur"),
                                VISLS0 = SIMP(statut='o',typ='R',fr="valeur de référence de la viscosité associée à la grandeur"),
                                IVISLS = SIMP(statut='f',typ='I',defaut=0,into=(0,1),fr="viscosité variable")
                                )
                );

DEFI_VITY = OPER(nom="DEFI_VITY",op=2,sd_prod=varvity,fr="définition de l'inconnue vitesse Y avec ses paramètres physico numériques",
                   NUMERIC = FACT(statut='o',max=01,
                                  fr="propriétés de l'équation de vitesse Y",
                                  ICONV  = SIMP(statut='o',typ='I',defaut=1,into=(0,1),
                                                fr="indicateur de convection"),
                                  ISTAT  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                fr="présence terme instationnaire dans les matrices"),
                                  IDIFF  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                fr="diffusion"),
                                  IDIRCL = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                fr="décalage du spectre des valeurs propres en l'absence de Dirichlet"),
                                  SCHEMA_CONVECTIF = BLOC(condition="ICONV == 1", fr ="ordre du schéma convectif",
                                                          BLENCV = SIMP(statut='o',typ='R',defaut=0,val_min=0,val_max=1,
                                                                        fr="pourcentage schéma convectif au second ordre"),
                                                          ISCHCV = SIMP(statut='f',typ='I',defaut=0,into=(0,1),
                                                                        fr ="type schéma convectif au second ordre 1 : centré")
                                                          ),
                                  NITMAX = SIMP(statut='f',typ='I',defaut=10000,val_min=0,
                                                fr="nombre max d'itération pour la résolution des systèmes linéaires"),
                                  EPSILO = SIMP(statut='f',typ='R',defaut=1.e-4,val_min=0,
                                                fr="précision relative pour la résolution des systèmes linéaires"),
                                  IMLIGR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,-1,0,1),
                                                fr="type de limitation des gradients"),
                                  NSWRGR = SIMP(statut='f',typ='I',defaut=100,val_min=0,
                                                fr="reconstruction des gradients"),
                                  NSWRSM = SIMP(statut='f',typ='I',defaut=2,val_min=0,
                                                fr="nombre d'itérations pour la reconstruction des seconds membres"),
                                  CLIMGR = SIMP(statut='f',typ='R',defaut=1.5,val_min=0,
                                                fr="facteur de limitation des gradients"),
                                  EPSRGR = SIMP(statut='f',typ='R',defaut=1.e-5,val_min=0,
                                                fr="précision relative pour la reconstruction itérative des gradients")
                                  ),
                  RESTITUE = FACT(statut='o',max=01,
                                  fr = "Description de la grandeur restituée",
                                  NOMVAR = SIMP(statut='o',typ='TXM',fr = "nom de la grandeur restituée",
                                                defaut="vitesse_v1"),
                                  ICHRVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "post-traitement (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  ILISVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "impression dans CR exécution (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  IHISVR = SIMP(statut='f',typ=sonde,min=0,max='**',
                                                fr = "inventaire des sondes utilisées pour la grandeur")
                                  ),
                  MODELE = FACT(statut='o',max=01,
                                fr="modélisation",
                                VALREF = SIMP(statut='o',typ='R',fr="valeur de référence (température, masse volumique...)"),
                                SCAMIN = SIMP(statut='f',typ='R',defaut=1.e12,fr="valeur minimale pour la grandeur"),
                                SCAMAX = SIMP(statut='f',typ='R',defaut=-1.e12,fr="valeur maximale pour la grandeur"),
                                SIGMAS = SIMP(statut='f',typ='R',val_min=0,defaut=1,fr="nombre de Prandtl pour la grandeur"),
                                VISLS0 = SIMP(statut='o',typ='R',fr="valeur de référence de la viscosité associée à la grandeur"),
                                IVISLS = SIMP(statut='f',typ='I',defaut=0,into=(0,1),fr="viscosité variable")
                                )
                );

DEFI_VITZ = OPER(nom="DEFI_VITZ",op=2,sd_prod=varvitz,fr="définition de l'inconnue vitesse Z avec ses paramètres physico numériques",
                   NUMERIC = FACT(statut='o',max=01,
                                  fr="propriétés de l'équation de vitesse Z",
                                  ICONV  = SIMP(statut='o',typ='I',defaut=1,into=(0,1),
                                                fr="indicateur de convection"),
                                  ISTAT  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                fr="présence terme instationnaire dans les matrices"),
                                  IDIFF  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                fr="diffusion"),
                                  IDIRCL = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                fr="décalage du spectre des valeurs propres en l'absence de Dirichlet"),
                                  SCHEMA_CONVECTIF = BLOC(condition="ICONV == 1", fr ="ordre du schéma convectif",
                                                          BLENCV = SIMP(statut='o',typ='R',defaut=0,val_min=0,val_max=1,
                                                                        fr="pourcentage schéma convectif au second ordre"),
                                                          ISCHCV = SIMP(statut='f',typ='I',defaut=0,into=(0,1),
                                                                        fr ="type schéma convectif au second ordre 1 : centré")
                                                          ),
                                  NITMAX = SIMP(statut='f',typ='I',defaut=10000,val_min=0,
                                                fr="nombre max d'itération pour la résolution des systèmes linéaires"),
                                  EPSILO = SIMP(statut='f',typ='R',defaut=1.e-4,val_min=0,
                                                fr="précision relative pour la résolution des systèmes linéaires"),
                                  IMLIGR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,-1,0,1),
                                                fr="type de limitation des gradients"),
                                  NSWRGR = SIMP(statut='f',typ='I',defaut=100,val_min=0,
                                                fr="reconstruction des gradients"),
                                  NSWRSM = SIMP(statut='f',typ='I',defaut=2,val_min=0,
                                                fr="nombre d'itérations pour la reconstruction des seconds membres"),
                                  CLIMGR = SIMP(statut='f',typ='R',defaut=1.5,val_min=0,
                                                fr="facteur de limitation des gradients"),
                                  EPSRGR = SIMP(statut='f',typ='R',defaut=1.e-5,val_min=0,
                                                fr="précision relative pour la reconstruction itérative des gradients")
                                  ),
                  RESTITUE = FACT(statut='o',max=01,
                                  fr = "Description de la grandeur restituée",
                                  NOMVAR = SIMP(statut='o',typ='TXM',fr = "nom de la grandeur restituée",
                                                defaut="vitesse_w1"),
                                  ICHRVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "post-traitement (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  ILISVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "impression dans CR exécution (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  IHISVR = SIMP(statut='f',typ=sonde,min=0,max='**',
                                                fr = "inventaire des sondes utilisées pour la grandeur")
                                  ),
                  MODELE = FACT(statut='o',max=01,
                                fr="modélisation",
                                VALREF = SIMP(statut='o',typ='R',fr="valeur de référence (température, masse volumique...)"),
                                SCAMIN = SIMP(statut='f',typ='R',defaut=1.e12,fr="valeur minimale pour la grandeur"),
                                SCAMAX = SIMP(statut='f',typ='R',defaut=-1.e12,fr="valeur maximale pour la grandeur"),
                                SIGMAS = SIMP(statut='f',typ='R',val_min=0,defaut=1,fr="nombre de Prandtl pour la grandeur"),
                                VISLS0 = SIMP(statut='o',typ='R',fr="valeur de référence de la viscosité associée à la grandeur"),
                                IVISLS = SIMP(statut='f',typ='I',defaut=0,into=(0,1),fr="viscosité variable"),
                                )
                );


DEFI_ETURB = OPER(nom="DEFI_ETURB",op=2,sd_prod=eturb,fr="définition de l'inconnue energie turbulente k-eps avec ses paramètres physico numériques",
                  NUMERIC = FACT(statut='o',max=01,
                                    fr="propriétés numériques liées à l'inconnue",
                                    ICONV  = SIMP(statut='o',typ='I',defaut=1,into=(0,1),
                                                  fr="indicateur de convection"),
                                    ISTAT  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="présence terme instationnaire dans les matrices"),
                                    IDIFF  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="diffusion"),
                                    IDIRCL = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="décalage du spectre des valeurs propres en l'absence de Dirichlet"),
                                    SCHEMA_CONVECTIF = BLOC(condition="ICONV == 1", fr ="ordre du schéma convectif",
                                                            BLENCV = SIMP(statut='o',typ='R',defaut=0,val_min=0,val_max=1,
                                                                          fr="pourcentage schéma convectif au second ordre"),
                                                            ISCHCV = SIMP(statut='f',typ='I',defaut=0,into=(0,1),
                                                                          fr ="type schéma convectif au second ordre 1 : centré")
                                                            ),
                                    NITMAX = SIMP(statut='f',typ='I',defaut=10000,val_min=0,
                                                  fr="nombre max d'itération pour la résolution des systèmes linéaires"),
                                    EPSILO = SIMP(statut='f',typ='R',defaut=1.e-4,val_min=0,
                                                  fr="précision relative pour la résolution des systèmes linéaires"),
                                    IMLIGR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,-1,0,1),
                                                  fr="type de limitation des gradients"),
                                    NSWRGR = SIMP(statut='f',typ='I',defaut=100,val_min=0,
                                                  fr="reconstruction des gradients"),
                                    NSWRSM = SIMP(statut='f',typ='I',defaut=2,val_min=0,
                                                  fr="nombre d'itérations pour la reconstruction des seconds membres"),
                                    CLIMGR = SIMP(statut='f',typ='R',defaut=1.5,val_min=0,
                                                  fr="facteur de limitation des gradients"),
                                    EPSRGR = SIMP(statut='f',typ='R',defaut=1.e-5,val_min=0,
                                                  fr="précision relative pour la reconstruction itérative des gradients")
                                 ),
                  RESTITUE = FACT(statut='o',max=01,
                                  fr = "Description de la grandeur restituée",
                                  NOMVAR = SIMP(statut='o',typ='TXM',fr = "nom de la grandeur restituée"),
                                  ICHRVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "post-traitement (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  ILISVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "impression dans CR exécution (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  IHISVR = SIMP(statut='f',typ=sonde,min=0,max='**',
                                                fr = "inventaire des sondes utilisées pour la grandeur scalaire")
                                  ),
                  MODELE = FACT(statut='o',max=01,
                                fr="modélisation",
                                VALREF = SIMP(statut='o',typ='R',fr="valeur de référence (température, masse volumique...)"),
                                SCAMIN = SIMP(statut='f',typ='R',defaut=1.e12,fr="valeur minimale pour le scalaire"),
                                SCAMAX = SIMP(statut='f',typ='R',defaut=-1.e12,fr="valeur maximale pour le scalaire"),
                                SIGMAS = SIMP(statut='f',typ='R',val_min=0,defaut=1,fr="nombre de Prandtl pour le scalaire"),
                                VISLS0 = SIMP(statut='o',typ='R',fr="valeur de référence de la viscosité associée au scalaire"),
                                IVISLS = SIMP(statut='f',typ='I',defaut=0,into=(0,1),fr="viscosité variable")
                                )
                 );

DEFI_DTURB = OPER(nom="DEFI_DTURB",op=2,sd_prod=dturb,fr="définition de l'inconnue dissipation turbulente k-eps avec ses paramètres physico numériques",
                  NUMERIC = FACT(statut='o',max=01,
                                fr="propriétés numériques liées à l'inconnue",
                                    ICONV  = SIMP(statut='o',typ='I',defaut=1,into=(0,1),
                                                  fr="indicateur de convection"),
                                    ISTAT  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="présence terme instationnaire dans les matrices"),
                                    IDIFF  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="diffusion"),
                                    IDIRCL = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="décalage du spectre des valeurs propres en l'absence de Dirichlet"),
                                    SCHEMA_CONVECTIF = BLOC(condition="ICONV == 1", fr ="ordre du schéma convectif",
                                                            BLENCV = SIMP(statut='o',typ='R',defaut=0,val_min=0,val_max=1,
                                                                          fr="pourcentage schéma convectif au second ordre"),
                                                            ISCHCV = SIMP(statut='f',typ='I',defaut=0,into=(0,1),
                                                                          fr ="type schéma convectif au second ordre 1 : centré")
                                                            ),
                                    NITMAX = SIMP(statut='f',typ='I',defaut=10000,val_min=0,
                                                  fr="nombre max d'itération pour la résolution des systèmes linéaires"),
                                    EPSILO = SIMP(statut='f',typ='R',defaut=1.e-4,val_min=0,
                                                  fr="précision relative pour la résolution des systèmes linéaires"),
                                    IMLIGR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,-1,0,1),
                                                  fr="type de limitation des gradients"),
                                    NSWRGR = SIMP(statut='f',typ='I',defaut=100,val_min=0,
                                                  fr="reconstruction des gradients"),
                                    NSWRSM = SIMP(statut='f',typ='I',defaut=2,val_min=0,
                                                  fr="nombre d'itérations pour la reconstruction des seconds membres"),
                                    CLIMGR = SIMP(statut='f',typ='R',defaut=1.5,val_min=0,
                                                  fr="facteur de limitation des gradients"),
                                    EPSRGR = SIMP(statut='f',typ='R',defaut=1.e-5,val_min=0,
                                                  fr="précision relative pour la reconstruction itérative des gradients")
                                 ),
                  RESTITUE = FACT(statut='o',max=01,
                                  fr = "Description de la grandeur restituée",
                                  NOMVAR = SIMP(statut='o',typ='TXM',fr = "nom de la grandeur restituée"),
                                  ICHRVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "post-traitement (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  ILISVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "impression dans CR exécution (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  IHISVR = SIMP(statut='f',typ=sonde,min=0,max='**',
                                                fr = "inventaire des sondes utilisées pour la grandeur scalaire")
                                  ),
                  MODELE = FACT(statut='o',max=01,
                                fr="modélisation",
                                VALREF = SIMP(statut='o',typ='R',fr="valeur de référence (température, masse volumique...)"),
                                SCAMIN = SIMP(statut='f',typ='R',defaut=1.e12,fr="valeur minimale pour le scalaire"),
                                SCAMAX = SIMP(statut='f',typ='R',defaut=-1.e12,fr="valeur maximale pour le scalaire"),
                                SIGMAS = SIMP(statut='f',typ='R',val_min=0,defaut=1,fr="nombre de Prandtl pour le scalaire"),
                                VISLS0 = SIMP(statut='o',typ='R',fr="valeur de référence de la viscosité associée au scalaire"),
                                IVISLS = SIMP(statut='f',typ='I',defaut=0,into=(0,1),fr="viscosité variable")
                                )
                 );

DEFI_TSR11 = OPER(nom="DEFI_TSR11",op=2,sd_prod=tsr11,fr="définition de l'inconnue tension Reynolds R11 Rij-eps avec ses paramètres physico numériques",
                  NUMERIC = FACT(statut='o',max=01,
                                fr="propriétés numériques liées à l'inconnue",
                                    ICONV  = SIMP(statut='o',typ='I',defaut=1,into=(0,1),
                                                  fr="indicateur de convection"),
                                    ISTAT  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="présence terme instationnaire dans les matrices"),
                                    IDIFF  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="diffusion"),
                                    IDIRCL = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="décalage du spectre des valeurs propres en l'absence de Dirichlet"),
                                    SCHEMA_CONVECTIF = BLOC(condition="ICONV == 1", fr ="ordre du schéma convectif",
                                                            BLENCV = SIMP(statut='o',typ='R',defaut=0,val_min=0,val_max=1,
                                                                          fr="pourcentage schéma convectif au second ordre"),
                                                            ISCHCV = SIMP(statut='f',typ='I',defaut=0,into=(0,1),
                                                                          fr ="type schéma convectif au second ordre 1 : centré")
                                                            ),
                                    NITMAX = SIMP(statut='f',typ='I',defaut=10000,val_min=0,
                                                  fr="nombre max d'itération pour la résolution des systèmes linéaires"),
                                    EPSILO = SIMP(statut='f',typ='R',defaut=1.e-4,val_min=0,
                                                  fr="précision relative pour la résolution des systèmes linéaires"),
                                    IMLIGR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,-1,0,1),
                                                  fr="type de limitation des gradients"),
                                    NSWRGR = SIMP(statut='f',typ='I',defaut=100,val_min=0,
                                                  fr="reconstruction des gradients"),
                                    NSWRSM = SIMP(statut='f',typ='I',defaut=2,val_min=0,
                                                  fr="nombre d'itérations pour la reconstruction des seconds membres"),
                                    CLIMGR = SIMP(statut='f',typ='R',defaut=1.5,val_min=0,
                                                  fr="facteur de limitation des gradients"),
                                    EPSRGR = SIMP(statut='f',typ='R',defaut=1.e-5,val_min=0,
                                                  fr="précision relative pour la reconstruction itérative des gradients")
                                 ),
                  RESTITUE = FACT(statut='o',max=01,
                                  fr = "Description de la grandeur restituée",
                                  NOMVAR = SIMP(statut='o',typ='TXM',fr = "nom de la grandeur restituée"),
                                  ICHRVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "post-traitement (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  ILISVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "impression dans CR exécution (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  IHISVR = SIMP(statut='f',typ=sonde,min=0,max='**',
                                                fr = "inventaire des sondes utilisées pour la grandeur scalaire")
                                  ),
                  MODELE = FACT(statut='o',max=01,
                                fr="modélisation",
                                VALREF = SIMP(statut='o',typ='R',fr="valeur de référence (température, masse volumique...)"),
                                SCAMIN = SIMP(statut='f',typ='R',defaut=1.e12,fr="valeur minimale pour le scalaire"),
                                SCAMAX = SIMP(statut='f',typ='R',defaut=-1.e12,fr="valeur maximale pour le scalaire"),
                                SIGMAS = SIMP(statut='f',typ='R',val_min=0,defaut=1,fr="nombre de Prandtl pour le scalaire"),
                                VISLS0 = SIMP(statut='o',typ='R',fr="valeur de référence de la viscosité associée au scalaire"),
                                IVISLS = SIMP(statut='f',typ='I',defaut=0,into=(0,1),fr="viscosité variable")
                                )
                 );

DEFI_TSR22 = OPER(nom="DEFI_TSR22",op=2,sd_prod=tsr11,fr="définition de l'inconnue tension Reynolds R22 Rij-eps avec ses paramètres physico numériques",
                  NUMERIC = FACT(statut='o',max=01,
                                fr="propriétés numériques liées à l'inconnue",
                                    ICONV  = SIMP(statut='o',typ='I',defaut=1,into=(0,1),
                                                  fr="indicateur de convection"),
                                    ISTAT  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="présence terme instationnaire dans les matrices"),
                                    IDIFF  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="diffusion"),
                                    IDIRCL = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="décalage du spectre des valeurs propres en l'absence de Dirichlet"),
                                    SCHEMA_CONVECTIF = BLOC(condition="ICONV == 1", fr ="ordre du schéma convectif",
                                                            BLENCV = SIMP(statut='o',typ='R',defaut=0,val_min=0,val_max=1,
                                                                          fr="pourcentage schéma convectif au second ordre"),
                                                            ISCHCV = SIMP(statut='f',typ='I',defaut=0,into=(0,1),
                                                                          fr ="type schéma convectif au second ordre 1 : centré")
                                                            ),
                                    NITMAX = SIMP(statut='f',typ='I',defaut=10000,val_min=0,
                                                  fr="nombre max d'itération pour la résolution des systèmes linéaires"),
                                    EPSILO = SIMP(statut='f',typ='R',defaut=1.e-4,val_min=0,
                                                  fr="précision relative pour la résolution des systèmes linéaires"),
                                    IMLIGR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,-1,0,1),
                                                  fr="type de limitation des gradients"),
                                    NSWRGR = SIMP(statut='f',typ='I',defaut=100,val_min=0,
                                                  fr="reconstruction des gradients"),
                                    NSWRSM = SIMP(statut='f',typ='I',defaut=2,val_min=0,
                                                  fr="nombre d'itérations pour la reconstruction des seconds membres"),
                                    CLIMGR = SIMP(statut='f',typ='R',defaut=1.5,val_min=0,
                                                  fr="facteur de limitation des gradients"),
                                    EPSRGR = SIMP(statut='f',typ='R',defaut=1.e-5,val_min=0,
                                                  fr="précision relative pour la reconstruction itérative des gradients")
                                 ),
                  RESTITUE = FACT(statut='o',max=01,
                                  fr = "Description de la grandeur restituée",
                                  NOMVAR = SIMP(statut='o',typ='TXM',fr = "nom de la grandeur restituée"),
                                  ICHRVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "post-traitement (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  ILISVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "impression dans CR exécution (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  IHISVR = SIMP(statut='f',typ=sonde,min=0,max='**',
                                                fr = "inventaire des sondes utilisées pour la grandeur scalaire")
                                  ),
                  MODELE = FACT(statut='o',max=01,
                                fr="modélisation",
                                VALREF = SIMP(statut='o',typ='R',fr="valeur de référence (température, masse volumique...)"),
                                SCAMIN = SIMP(statut='f',typ='R',defaut=1.e12,fr="valeur minimale pour le scalaire"),
                                SCAMAX = SIMP(statut='f',typ='R',defaut=-1.e12,fr="valeur maximale pour le scalaire"),
                                SIGMAS = SIMP(statut='f',typ='R',val_min=0,defaut=1,fr="nombre de Prandtl pour le scalaire"),
                                VISLS0 = SIMP(statut='o',typ='R',fr="valeur de référence de la viscosité associée au scalaire"),
                                IVISLS = SIMP(statut='f',typ='I',defaut=0,into=(0,1),fr="viscosité variable")
                                )
                 );

DEFI_TSR33 = OPER(nom="DEFI_TSR33",op=2,sd_prod=tsr11,fr="définition de l'inconnue tension Reynolds R33 Rij-eps avec ses paramètres physico numériques",
                  NUMERIC = FACT(statut='o',max=01,
                                fr="propriétés numériques liées à l'inconnue",
                                    ICONV  = SIMP(statut='o',typ='I',defaut=1,into=(0,1),
                                                  fr="indicateur de convection"),
                                    ISTAT  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="présence terme instationnaire dans les matrices"),
                                    IDIFF  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="diffusion"),
                                    IDIRCL = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="décalage du spectre des valeurs propres en l'absence de Dirichlet"),
                                    SCHEMA_CONVECTIF = BLOC(condition="ICONV == 1", fr ="ordre du schéma convectif",
                                                            BLENCV = SIMP(statut='o',typ='R',defaut=0,val_min=0,val_max=1,
                                                                          fr="pourcentage schéma convectif au second ordre"),
                                                            ISCHCV = SIMP(statut='f',typ='I',defaut=0,into=(0,1),
                                                                          fr ="type schéma convectif au second ordre 1 : centré")
                                                            ),
                                    NITMAX = SIMP(statut='f',typ='I',defaut=10000,val_min=0,
                                                  fr="nombre max d'itération pour la résolution des systèmes linéaires"),
                                    EPSILO = SIMP(statut='f',typ='R',defaut=1.e-4,val_min=0,
                                                  fr="précision relative pour la résolution des systèmes linéaires"),
                                    IMLIGR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,-1,0,1),
                                                  fr="type de limitation des gradients"),
                                    NSWRGR = SIMP(statut='f',typ='I',defaut=100,val_min=0,
                                                  fr="reconstruction des gradients"),
                                    NSWRSM = SIMP(statut='f',typ='I',defaut=2,val_min=0,
                                                  fr="nombre d'itérations pour la reconstruction des seconds membres"),
                                    CLIMGR = SIMP(statut='f',typ='R',defaut=1.5,val_min=0,
                                                  fr="facteur de limitation des gradients"),
                                    EPSRGR = SIMP(statut='f',typ='R',defaut=1.e-5,val_min=0,
                                                  fr="précision relative pour la reconstruction itérative des gradients")
                                 ),
                  RESTITUE = FACT(statut='o',max=01,
                                  fr = "Description de la grandeur restituée",
                                  NOMVAR = SIMP(statut='o',typ='TXM',fr = "nom de la grandeur restituée"),
                                  ICHRVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "post-traitement (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  ILISVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "impression dans CR exécution (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  IHISVR = SIMP(statut='f',typ=sonde,min=0,max='**',
                                                fr = "inventaire des sondes utilisées pour la grandeur scalaire")
                                  ),
                  MODELE = FACT(statut='o',max=01,
                                fr="modélisation",
                                VALREF = SIMP(statut='o',typ='R',fr="valeur de référence (température, masse volumique...)"),
                                SCAMIN = SIMP(statut='f',typ='R',defaut=1.e12,fr="valeur minimale pour le scalaire"),
                                SCAMAX = SIMP(statut='f',typ='R',defaut=-1.e12,fr="valeur maximale pour le scalaire"),
                                SIGMAS = SIMP(statut='f',typ='R',val_min=0,defaut=1,fr="nombre de Prandtl pour le scalaire"),
                                VISLS0 = SIMP(statut='o',typ='R',fr="valeur de référence de la viscosité associée au scalaire"),
                                IVISLS = SIMP(statut='f',typ='I',defaut=0,into=(0,1),fr="viscosité variable")
                                )
                 );

DEFI_TSR12 = OPER(nom="DEFI_TSR12",op=2,sd_prod=tsr11,fr="définition de l'inconnue tension Reynolds R12 Rij-eps avec ses paramètres physico numériques",
                  NUMERIC = FACT(statut='o',max=01,
                                fr="propriétés numériques liées à l'inconnue",
                                    ICONV  = SIMP(statut='o',typ='I',defaut=1,into=(0,1),
                                                  fr="indicateur de convection"),
                                    ISTAT  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="présence terme instationnaire dans les matrices"),
                                    IDIFF  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="diffusion"),
                                    IDIRCL = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="décalage du spectre des valeurs propres en l'absence de Dirichlet"),
                                    SCHEMA_CONVECTIF = BLOC(condition="ICONV == 1", fr ="ordre du schéma convectif",
                                                            BLENCV = SIMP(statut='o',typ='R',defaut=0,val_min=0,val_max=1,
                                                                          fr="pourcentage schéma convectif au second ordre"),
                                                            ISCHCV = SIMP(statut='f',typ='I',defaut=0,into=(0,1),
                                                                          fr ="type schéma convectif au second ordre 1 : centré")
                                                            ),
                                    NITMAX = SIMP(statut='f',typ='I',defaut=10000,val_min=0,
                                                  fr="nombre max d'itération pour la résolution des systèmes linéaires"),
                                    EPSILO = SIMP(statut='f',typ='R',defaut=1.e-4,val_min=0,
                                                  fr="précision relative pour la résolution des systèmes linéaires"),
                                    IMLIGR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,-1,0,1),
                                                  fr="type de limitation des gradients"),
                                    NSWRGR = SIMP(statut='f',typ='I',defaut=100,val_min=0,
                                                  fr="reconstruction des gradients"),
                                    NSWRSM = SIMP(statut='f',typ='I',defaut=2,val_min=0,
                                                  fr="nombre d'itérations pour la reconstruction des seconds membres"),
                                    CLIMGR = SIMP(statut='f',typ='R',defaut=1.5,val_min=0,
                                                  fr="facteur de limitation des gradients"),
                                    EPSRGR = SIMP(statut='f',typ='R',defaut=1.e-5,val_min=0,
                                                  fr="précision relative pour la reconstruction itérative des gradients")
                                 ),
                  RESTITUE = FACT(statut='o',max=01,
                                  fr = "Description de la grandeur restituée",
                                  NOMVAR = SIMP(statut='o',typ='TXM',fr = "nom de la grandeur restituée"),
                                  ICHRVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "post-traitement (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  ILISVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "impression dans CR exécution (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  IHISVR = SIMP(statut='f',typ=sonde,min=0,max='**',
                                                fr = "inventaire des sondes utilisées pour la grandeur scalaire")
                                  ),
                  MODELE = FACT(statut='o',max=01,
                                fr="modélisation",
                                VALREF = SIMP(statut='o',typ='R',fr="valeur de référence (température, masse volumique...)"),
                                SCAMIN = SIMP(statut='f',typ='R',defaut=1.e12,fr="valeur minimale pour le scalaire"),
                                SCAMAX = SIMP(statut='f',typ='R',defaut=-1.e12,fr="valeur maximale pour le scalaire"),
                                SIGMAS = SIMP(statut='f',typ='R',val_min=0,defaut=1,fr="nombre de Prandtl pour le scalaire"),
                                VISLS0 = SIMP(statut='o',typ='R',fr="valeur de référence de la viscosité associée au scalaire"),
                                IVISLS = SIMP(statut='f',typ='I',defaut=0,into=(0,1),fr="viscosité variable")
                                )
                 );

DEFI_TSR13 = OPER(nom="DEFI_TSR13",op=2,sd_prod=tsr11,fr="définition de l'inconnue tension Reynolds R13 Rij-eps avec ses paramètres physico numériques",
                  NUMERIC = FACT(statut='o',max=01,
                                fr="propriétés numériques liées à l'inconnue",
                                    ICONV  = SIMP(statut='o',typ='I',defaut=1,into=(0,1),
                                                  fr="indicateur de convection"),
                                    ISTAT  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="présence terme instationnaire dans les matrices"),
                                    IDIFF  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="diffusion"),
                                    IDIRCL = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="décalage du spectre des valeurs propres en l'absence de Dirichlet"),
                                    SCHEMA_CONVECTIF = BLOC(condition="ICONV == 1", fr ="ordre du schéma convectif",
                                                            BLENCV = SIMP(statut='o',typ='R',defaut=0,val_min=0,val_max=1,
                                                                          fr="pourcentage schéma convectif au second ordre"),
                                                            ISCHCV = SIMP(statut='f',typ='I',defaut=0,into=(0,1),
                                                                          fr ="type schéma convectif au second ordre 1 : centré")
                                                            ),
                                    NITMAX = SIMP(statut='f',typ='I',defaut=10000,val_min=0,
                                                  fr="nombre max d'itération pour la résolution des systèmes linéaires"),
                                    EPSILO = SIMP(statut='f',typ='R',defaut=1.e-4,val_min=0,
                                                  fr="précision relative pour la résolution des systèmes linéaires"),
                                    IMLIGR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,-1,0,1),
                                                  fr="type de limitation des gradients"),
                                    NSWRGR = SIMP(statut='f',typ='I',defaut=100,val_min=0,
                                                  fr="reconstruction des gradients"),
                                    NSWRSM = SIMP(statut='f',typ='I',defaut=2,val_min=0,
                                                  fr="nombre d'itérations pour la reconstruction des seconds membres"),
                                    CLIMGR = SIMP(statut='f',typ='R',defaut=1.5,val_min=0,
                                                  fr="facteur de limitation des gradients"),
                                    EPSRGR = SIMP(statut='f',typ='R',defaut=1.e-5,val_min=0,
                                                  fr="précision relative pour la reconstruction itérative des gradients")
                                 ),
                  RESTITUE = FACT(statut='o',max=01,
                                  fr = "Description de la grandeur restituée",
                                  NOMVAR = SIMP(statut='o',typ='TXM',fr = "nom de la grandeur restituée"),
                                  ICHRVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "post-traitement (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  ILISVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "impression dans CR exécution (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  IHISVR = SIMP(statut='f',typ=sonde,min=0,max='**',
                                                fr = "inventaire des sondes utilisées pour la grandeur scalaire")
                                  ),
                  MODELE = FACT(statut='o',max=01,
                                fr="modélisation",
                                VALREF = SIMP(statut='o',typ='R',fr="valeur de référence (température, masse volumique...)"),
                                SCAMIN = SIMP(statut='f',typ='R',defaut=1.e12,fr="valeur minimale pour le scalaire"),
                                SCAMAX = SIMP(statut='f',typ='R',defaut=-1.e12,fr="valeur maximale pour le scalaire"),
                                SIGMAS = SIMP(statut='f',typ='R',val_min=0,defaut=1,fr="nombre de Prandtl pour le scalaire"),
                                VISLS0 = SIMP(statut='o',typ='R',fr="valeur de référence de la viscosité associée au scalaire"),
                                IVISLS = SIMP(statut='f',typ='I',defaut=0,into=(0,1),fr="viscosité variable")
                                )
                 );

DEFI_TSR23 = OPER(nom="DEFI_TSR23",op=2,sd_prod=tsr11,fr="définition de l'inconnue tension Reynolds R23 Rij-eps avec ses paramètres physico numériques",
                  NUMERIC = FACT(statut='o',max=01,
                                fr="propriétés numériques liées à l'inconnue",
                                    ICONV  = SIMP(statut='o',typ='I',defaut=1,into=(0,1),
                                                  fr="indicateur de convection"),
                                    ISTAT  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="présence terme instationnaire dans les matrices"),
                                    IDIFF  = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="diffusion"),
                                    IDIRCL = SIMP(statut='f',typ='I',defaut=1,into=(0,1),
                                                  fr="décalage du spectre des valeurs propres en l'absence de Dirichlet"),
                                    SCHEMA_CONVECTIF = BLOC(condition="ICONV == 1", fr ="ordre du schéma convectif",
                                                            BLENCV = SIMP(statut='o',typ='R',defaut=0,val_min=0,val_max=1,
                                                                          fr="pourcentage schéma convectif au second ordre"),
                                                            ISCHCV = SIMP(statut='f',typ='I',defaut=0,into=(0,1),
                                                                          fr ="type schéma convectif au second ordre 1 : centré")
                                                            ),
                                    NITMAX = SIMP(statut='f',typ='I',defaut=10000,val_min=0,
                                                  fr="nombre max d'itération pour la résolution des systèmes linéaires"),
                                    EPSILO = SIMP(statut='f',typ='R',defaut=1.e-4,val_min=0,
                                                  fr="précision relative pour la résolution des systèmes linéaires"),
                                    IMLIGR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,-1,0,1),
                                                  fr="type de limitation des gradients"),
                                    NSWRGR = SIMP(statut='f',typ='I',defaut=100,val_min=0,
                                                  fr="reconstruction des gradients"),
                                    NSWRSM = SIMP(statut='f',typ='I',defaut=2,val_min=0,
                                                  fr="nombre d'itérations pour la reconstruction des seconds membres"),
                                    CLIMGR = SIMP(statut='f',typ='R',defaut=1.5,val_min=0,
                                                  fr="facteur de limitation des gradients"),
                                    EPSRGR = SIMP(statut='f',typ='R',defaut=1.e-5,val_min=0,
                                                  fr="précision relative pour la reconstruction itérative des gradients")
                                 ),
                  RESTITUE = FACT(statut='o',max=01,
                                  fr = "Description de la grandeur restituée",
                                  NOMVAR = SIMP(statut='o',typ='TXM',fr = "nom de la grandeur restituée"),
                                  ICHRVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "post-traitement (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  ILISVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "impression dans CR exécution (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  IHISVR = SIMP(statut='f',typ=sonde,min=0,max='**',
                                                fr = "inventaire des sondes utilisées pour la grandeur scalaire")
                                  ),
                  MODELE = FACT(statut='o',max=01,
                                fr="modélisation",
                                VALREF = SIMP(statut='o',typ='R',fr="valeur de référence (température, masse volumique...)"),
                                SCAMIN = SIMP(statut='f',typ='R',defaut=1.e12,fr="valeur minimale pour le scalaire"),
                                SCAMAX = SIMP(statut='f',typ='R',defaut=-1.e12,fr="valeur maximale pour le scalaire"),
                                SIGMAS = SIMP(statut='f',typ='R',val_min=0,defaut=1,fr="nombre de Prandtl pour le scalaire"),
                                VISLS0 = SIMP(statut='o',typ='R',fr="valeur de référence de la viscosité associée au scalaire"),
                                IVISLS = SIMP(statut='f',typ='I',defaut=0,into=(0,1),fr="viscosité variable")
                                )
                 );


DEFI_RESTI = OPER(nom="DEFI_RESTI",op=2,sd_prod=resti,fr = "Description de la grandeur restituée",
                                  NOMVAR = SIMP(statut='o',typ='TXM',fr = "nom de la grandeur restituée"),
                                  ICHRVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "post-traitement (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  ILISVR = SIMP(statut='f',typ='I',defaut=-999,into=(-999,0,1),
                                                fr = "impression dans CR exécution (-999 : le code décide ; 0 : non ; 1 : oui)"),
                                  IHISVR = SIMP(statut='f',typ=sonde,min=0,max='**',
                                                fr = "inventaire des sondes utilisées pour la grandeur scalaire")
                  );

CALCUL_SATURNE = PROC(nom = "CALCUL_SATURNE",op = 1,
                      fr = "définition des paramètres généraux pour un calcul Saturne",
                      docu = "néant",reentrant = 'n',
        ENVELOPPE = FACT(statut='o',max=01,fr = "gestion de l'enveloppe",
                         IFOENV = SIMP(statut='o',typ='I',defaut=2,into=(0,1,2),position='global',
                                       fr = "mode de communication enveloppe solveur"),
                         ENVTOSOLV = BLOC(condition="IFOENV > 0",
                                          fr = "liaison enveloppe vers solveur",
                                          IMPEVI = SIMP(statut='o',typ='I',defaut=13,val_min=0,val_max=99,
                                                        fr = "numéro de fichier enveloppe vers solveur"),
                                          FICEVI = SIMP(statut='o',typ='TXM',defaut="enveloppe_vers_solveur          ",
                                                        fr = "nom de fichier enveloppe vers solveur")
                                         ),
                         SOLVTOENV = BLOC(condition="IFOENV > 0",
                                          fr = "liaison solveur vers enveloppe",
                                          IMPEVO = SIMP(statut='o',typ='I',defaut=14,val_min=0,val_max=99,
                                                        fr = "numéro de fichier solveur vers enveloppe"),
                                          FICEVO = SIMP(statut='o',typ='TXM',defaut="solveur_vers_enveloppe          ",
                                                        fr = "nom de fichier solveur vers enveloppe")
                                         )
                        ),
        FICHIERS_CALCUL = FACT(statut='f',max=01,
                               fr ="définition des fichiers géométrie, suite, stop",
                               GEOMETRIE = BLOC(condition="IFOENV == 0",
                                                fr = "fichier géométrique (pas d'enveloppe)",
                                                IMPGEO = SIMP(statut='o',typ='I',defaut=10,val_min=0,val_max=99,
                                                              fr = "numéro de fichier géométrique"),
                                                FICGEO = SIMP(statut='o',typ='TXM',defaut="geomet",
                                                              fr = "nom de fichier géométrique")
                                               ),
                               SUITE_AMONT = BLOC(condition="ISUITE == 1",
                                                  fr = "fichier suite amont",
                                                  IMPAMO = SIMP(statut='o',typ='I',defaut=11,val_min=0,val_max=99,
                                                              fr = "numéro de fichier suite amont"),
                                                  FICGEO = SIMP(statut='o',typ='TXM',defaut="suiamo",
                                                              fr = "nom de fichier suite amont"),
                                                  IFOAMO = SIMP(statut='o',typ='I',defaut=1,into=(0,1),
                                                              fr = "format du fichier suite amont, 0 = binaire")
                                                 ),
                              ),
        POST_PROC_ENSIGHT = FACT(statut='f',max=01,
                                 fr = "options de post processing par Ensight",
                                 IFOENS = SIMP(statut='f',typ='I',defaut=-2,into=(-2,-1,0,1),
                                               fr = "option type de fichier et processus générateur"),
                                 NTCHR  = SIMP(statut='f',typ='I',defaut=-1,
                                               fr = "périodicité de sortie des fichiers Ensight"),
                                 ITCHR  = SIMP(statut='f',typ='I',defaut=0,val_min=0,
                                               fr = "compteur des sorties des fichiers Ensight"),
                                 N3S_ASCII_NOY = BLOC(condition="(IFOENS == -1) and (IFOENV == 0)",
                                                      fr = "format Ensight N3S ASCII généré par le noyau",
                                                      IMPPST = SIMP(statut='o',typ='I',defaut=21,val_min=0,val_max=99,
                                                                    fr = "numéro de fichier Ensight"),
                                                      FICPST = SIMP(statut='o',typ='TXM',defaut="dessin",
                                                                    fr = "nom de fichier Ensight")
                                                      ),
                                 P0_NOY =        BLOC(condition="((IFOENS == 0) or (IFOENS == 1)) and (IFOENV == 0)",
                                                      fr = "format Ensight P0 généré par le noyau",
                                                      IMPEP0 = SIMP(statut='o',typ='I',defaut=22,val_min=0,val_max=99,
                                                                    fr = "numéro de fichier Ensight"),
                                                      EMPCHR = SIMP(statut='o',typ='TXM',defaut="./",
                                                                    fr = "répertoire de fichier Ensight"),
                                                      ENTCHR = SIMP(statut='o',typ='TXM',defaut="chr",
                                                                    fr = "préfixe nom de fichier Ensight")
                                                      )
                                ),
        HISTORIQUE_PONCTUEL = FACT(statut='o',max=01,
                                   fr = "Sondes historiques",
                                   NTHIST = SIMP(statut='f',typ='I',defaut=-999,
                                                 fr="fréquence de sortie des historiques en pas de temps"),
                                   NTHSAV = SIMP(statut='f',typ='I',defaut=-999,
                                                 fr="fréquence de sauvegarde des historiques en pas de temps")
                                  ),
        OPTIONS_TURBULENCE = FACT(statut='o',max=01,
                                  fr="modèle de turbulence",
                                  ITURB  = SIMP(statut='f',fr="laminaire : 0, k-epsilon :1,Rij-epsilon :2",
                                                typ='I',into=(0,1,2),defaut=1,position='global'),
                                  MODTURB = BLOC(condition="ITURB == 1",
                                                 fr = "option k-epsilon",
                                                 IGRAKE = SIMP(statut='o',typ='I',
                                                               fr="prise en compte gravité dans k-epsilon",
                                                               into=(0,1),defaut=0),
                                                 IDEUCH = SIMP(statut='f',typ='I',
                                                               fr="prise en compte k-epsilon deux échelles",
                                                               into=(0,1),defaut=1),
                                                 IKEKOU = SIMP(statut='f',typ='I',
                                                               fr="prise en compte couplage en incréments sur k-epsilon",
                                                               into=(0,1),defaut=1)
                                                 ),
                                  TEMPTURB = BLOC(condition="ITURB == 1",
                                                  fr = "option k-epsilon",
                                                  ISCALT = SIMP(statut='o',typ=varsca,
                                                                fr=" identificateur inconnue scalaire température ")
                                                  )
                                  ),
        MARCHE_TEMPS = FACT(statut='o',max=01,
                            fr = "définition de la marche en temps",
                            DTREF  = SIMP(statut='o',fr="pas de temps de référence",
                                                        typ='R',val_min=0),
                            IDTVAR = SIMP(statut='f',fr="pas de temps constant : 0, variable temps espace : 1, variable temps : 2",
                                          typ='I',into=(0,1,2),defaut=0,position='global'),
                                  # probleme trace eficas quand un mot cle position global change
                            PASVAR = BLOC(condition="IDTVAR != 0",fr="options pas de temps variable",
                                          XCFMAX = SIMP(statut='o',fr="nombre de Courant-Fourier cible",
                                                        typ='R',defaut=0.5,val_min=0),
                                          FMIN =   SIMP(statut='f',fr="rapport min pas calculé DTREF",
                                                        typ='R',defaut=0.1,val_min=0),
                                          FMAX =   SIMP(statut='f',fr="rapport max pas calculé DTREF",
                                                        typ='R',defaut=1000,val_min=0),
                                          VARRDT = SIMP(statut='f',fr="variation relative max pas calculé entre deux instants",
                                                        typ='R',defaut=0.1,val_min=0)
                                          )
                            ),
        OPTIONS_EQUATIONS = FACT(statut='o',max=01,
                                   fr = "propriétés des équations, inconnues principales",
                                   IMGR   = SIMP(statut='f',fr="utilisation du multigrille pour la résolution des systèmes linéaires",
                                                 typ='I',into=(0,1),defaut=0),
                                   IMRGRA = SIMP(statut='f',fr="type de reconstruction des gradients 1 : moindres carrés",
                                                 typ='I',into=(0,1),defaut=0),
                                   ),
        VARIABLES = FACT(statut='o',max=01,
                         fr = "Restitution des grandeurs principales",
                         NTLIST = SIMP(statut='f',typ='I',defaut=1,val_min=1,val_max='**',
                                       fr = "fréquence de sortie (en pas de temps) dans le compte rendu d'éxécution"),
                         IWARNI = SIMP(statut='f',typ='I',defaut=2,val_min=0,val_max='**',
                                       fr = "niveau de détail des impressions dans le compte rendu d'éxécution"),
                        ),
        GESTION_CALCUL = FACT(statut='o',max=01,
                              fr = "calcul suite et numéros de pas de temps début et fin",
                              ISUITE = SIMP(statut='o',typ='I',defaut=0,into=(0,1),position='global',
                                            fr = "indicateur calcul suite (1 = suite)"),
                              NTPABS = SIMP(statut='f',typ='I',defaut=0,
                                            fr = "numéro dernier pas de temps calcul précédent (initialisation automatique)"),
                              NTMABS = SIMP(statut='o',typ='I',
                                            fr = "numéro dernier pas de temps visé (absolu)"),
                              TTPABS = SIMP(statut='f',typ='R',defaut=0,
                                            fr = "temps simulation au dernier pas de temps précédent (initialisation automatique)")
                             ),
        CONSTANTES_PHYSIQUES=FACT(statut='o',max=01,
                                  fr = "Grandeurs physiques et modélisation",
                                  TURBULENCE = BLOC(condition="ITURB >= 0",
                                                    XKAPPA = SIMP(statut ='o',typ='R',defaut=0.42,val_min=0,fr="constante de Karman"),
                                                    CSTLOG = SIMP(statut ='f',typ='R',defaut=5.2,val_min=0,fr="constante de la loi log"),
                                                    YPLULI = SIMP(statut ='f',typ='R',defaut=2/0.42,val_min=0,fr="valeur limite de y+ pour la sous couche visqueuse"),
                                                    CMU = SIMP(statut ='f',typ='R',defaut=0.009,val_min=0,fr="constante C mu"),
                                                    CE1 = SIMP(statut ='f',typ='R',defaut=1.44,val_min=0,fr="constante C epsilon 1"),
                                                    CE2 = SIMP(statut ='f',typ='R',defaut=1.92,val_min=0,fr="constante C epsilon 2"),
                                                    CE3 = SIMP(statut ='f',typ='R',defaut=1.0,val_min=0,fr="constante C epsilon 3"),
                                                    SIGMAK = SIMP(statut ='f',typ='R',defaut=1.0,val_min=0,fr="nombre de Prandtl pour k en k-epsilon"),
                                                    SIGMAE = SIMP(statut ='f',typ='R',defaut=1.3,val_min=0,fr="nombre de Prandtl pour epsilon en k-epsilon"),
                                                    ALMAX = SIMP(statut ='f',typ='R',val_min=0,fr="longueur macroscopique caractéristique du domaine"),
                                                    UREF = SIMP(statut ='f',typ='R',val_min=0,fr="vitesse caractéristique de l'écoulement pour l'initialisation du k-epsilon")
                                                    )
                                  )
                                 );

