# debut entete
import Accas
from Accas import *
#
JdC = JDC_CATA(code='SYRTHES',
               execmodul=None,
               niveaux=(NIVEAU(nom='generalites',label='Généralités',valide_vide=0),
                        NIVEAU(nom='gest_calc',label='Gestion du calcul',valide_vide=0,actif="generalites == 1"),
                        NIVEAU(nom='gest_sort',label='Gestion des sorties'),
                        NIVEAU(nom='choix_num',label='Choix numériques',valide_vide=0),
                        NIVEAU(nom='prop_phys',label='Propriétés physiques',valide_vide=0,actif='choix_num==1'),
                        NIVEAU(nom='cond_init',label='Conditions initiales',valide_vide=0,actif='prop_phys==1'),
                        NIVEAU(nom='cond_limi',label='Conditions aux limites',valide_vide=0,actif='cond_init==1'),
                        NIVEAU(nom='flux_volu',label='Flux volumiques',valide_vide=0,actif='cond_limi==1'),
                        NIVEAU(nom='soli_mouv',label='Solides en mouvement'),
                        NIVEAU(nom='couplages',label='Couplages'),
                        NIVEAU(nom='rayonnement',label='Rayonnement',valide_vide=0,actif='flux_volu==1'),
                        NIVEAU(nom='cond_lim_ray',label='Conditions limites rayonnement',valide_vide=0,actif='rayonnement==1'),
                        NIVEAU(nom='in_out_ray',label='Entrées/Sorties rayonnement',valide_vide=0,actif='rayonnement==1'),
                        NIVEAU(nom='fichiers',label='Fichiers pour le calcul'))
               )


GENERALITES = PROC(nom='GENERALITES',op=10,
                   fr="Définition des principales options du calcul",
                   niveau='generalites',
                   TYPE_DE_CALCUL=SIMP(typ='TXM',
                                       statut='o',
                                       into=('Syrthes thermique solide seule','Syrthes couplé'),
                                       defaut='Syrthes thermique solide seule',
                                       position='global_jdc'),
                   TITRE = SIMP(statut='f',typ='TXM'),
                   DIMENSION = SIMP(statut='o',
                                    typ='I',
                                    into=(2,3),
                                    defaut=2,
                                    position='global_jdc'),
                   b_axys = BLOC(condition="TYPE_DE_CALCUL=='Syrthes thermique solide seule'",
                                 AXE_SYMETRIE = SIMP(statut='o',
                                                     typ='TXM',
                                                     into=('AUCUN','OX','OY'),
                                                     defaut='AUCUN')));

GESTION_DU_CALCUL = PROC(nom='GESTION_DU_CALCUL',op=10,
                         fr="Gestion des pas de temps et éventuellement du couplage fluide/solide",
                         niveau='gest_calc',
                         CALCUL_SYRTHES_SEUL = BLOC(condition="TYPE_DE_CALCUL == 'Syrthes thermique solide seule'",
                                                    PAS_DE_TEMPS_SOLIDE = SIMP(typ='I',statut='o'),
                                                    NB_PAS_DE_TEMPS = SIMP(typ='I',statut='o'),
                                                    SUITE_DE_CALCUL = SIMP(typ='TXM',statut='o',into=('OUI','NON'),defaut='NON')),
                         CALCUL_SYRTHES_COUPLE = BLOC(condition="TYPE_DE_CALCUL =='Syrthes couplé'",
                                                      CORRESPONDANCE_MAILLAGES_F_S = SIMP(statut='o',
                                                                                          typ='TXM',
                                                                                          into=('calcul','lecture sur fichier','calcul et écriture sur fichier'),
                                                                                          defaut='calcul et écriture sur fichier'),
                                                      PAS_DE_TEMPS_SOLIDE = SIMP(typ='TXM',
                                                                                 statut='o',
                                                                                 into=('fixé indépendamment','égal à celui du fluide'),
                                                                                 defaut='égal à celui du fluide'),
                                                      CHOIX_FREQUENCE_CALCUL_SOLIDE = SIMP(typ='TXM',
                                                                                     statut='o',
                                                                                     into=('calcul solide à chaque pas de temps',
                                                                                           'calcul solide tous les n pas de temps fluide',
                                                                                           'calcul fluide tous les n pas de temps solide'),
                                                                                     defaut='calcul solide à chaque pas de temps'),
                                                      frequence_calcul = BLOC(condition="CHOIX_FREQUENCE_CALCUL_SOLIDE != 'calcul solide à chaque pas de temps'",
                                                                              FREQUENCE = SIMP(statut='o',
                                                                                               typ='I')))
                                                      
                       );

GESTION_DES_SORTIES = PROC(nom="GESTION_DES_SORTIES",op=10,
                           fr="Gestion des résultats du code",
                           niveau='gest_sort',
                           IMPRESSIONS_SOLIDE=SIMP(statut='o',typ='TXM',
                                                   into=('aucune','minimales','normales','détaillées'),
                                                   defaut='normales'),
                           RESULTATS_DOMAINE_SOLIDE=FACT(statut='o',
                                                         FICHIER_CHRONOLOGIQUE=SIMP(typ='TXM',statut='o',
                                                                                    into=('aucune sortie','tous les n pas de temps'),
                                                                                    defaut='aucune sortie'),
                                                         pas_de_temps=BLOC(condition="FICHIER_CHRONOLOGIQUE=='tous les n pas de temps'",
                                                                           PAS_DE_TEMPS=SIMP(statut='o',typ='I')),
                                                         FICHIER_LISTING=SIMP(statut='o',typ='TXM',
                                                                              into=('aucune sortie',),
                                                                              defaut='aucune sortie'),
                                                         HISTORIQUE_SOLIDE=SIMP(statut='o',typ='TXM',
                                                                                into=('OUI','NON'),
                                                                                defaut='NON'),
                                                         historique=BLOC(condition="HISTORIQUE_SOLIDE=='OUI'",
                                                                         NOMBRE_CAPTEURS=SIMP(statut='o',typ='I'),
                                                                         FREQUENCE_ECRITURE=SIMP(statut='o',typ='I',defaut=1),
                                                                         LISTE_NOEUDS = FACT(statut='o',max='**',
                                                                                             NOEUDS=SIMP(statut='o',max='**',typ='I'),
                                                                                             COMMENTAIRE=SIMP(statut='o',typ='TXM',defaut=""))),
                                                         ),
                           RESULTATS_DOMAINE_FLUIDE=BLOC(condition="TYPE_DE_CALCUL=='Syrthes couplé'",
                                                         ECRITURE_MAILLAGE_PEAU_FLUIDE=SIMP(statut='o',into=('OUI','NON'),
                                                                                            defaut='NON',typ='TXM'),
                                                         ECRITURE_RESULTATS_PEAU_FLUIDE=SIMP(statut='o',into=('OUI','NON'),
                                                                                             defaut='NON',typ='TXM'),
                                                         ECRITURE_CHRONO_PEAU_FLUIDE=SIMP(statut='o',into=('OUI','NON'),
                                                                                          defaut='NON',typ='TXM'))
                           );

CHOIX_NUMERIQUES=PROC(nom="CHOIX_NUMERIQUES",op=10,
                      fr="Modification des options du solveur",
                      niveau='choix_num',
                      SOLVEUR_SOLIDE = FACT(statut='o',
                                            NOMBRE_ITERATIONS=SIMP(statut='o',typ='I'),
                                            PRECISION=SIMP(statut='o',typ='R'))
                      );

PROPRIETES_PHYSIQUES=PROC(nom="PROPRIETES_PHYSIQUES",op=10,
                          fr="Définition des propriétés physiques des matériaux",
                          niveau='prop_phys',
                          DEFINITION_PAR = SIMP(statut='o',typ='TXM',into=('NOEUD','ELEMENT','NOEUD PAR ELEMENT'),
                                                defaut='ELEMENT'),
                          ISOTROPIE = SIMP(statut='o', typ='TXM', into=('Matériaux isotropes',
                                                                        'Matériaux anisotropes',
                                                                        'Matériaux orthotropes'),
                                           defaut='Matériaux isotropes'),
                          proprietes_des_materiaux_isotropes = BLOC(condition="ISOTROPIE=='Mat\351riaux isotropes'",                          
                              DEFINITION_MASSE_VOLUMIQUE=FACT(statut='o',max='**',
                                                          MASSE_VOLUMIQUE = SIMP(statut='o',typ='R'),
                                                          REFERENCES = SIMP(statut='o',typ='I',max='**'),
                                                          COMMENTAIRES=SIMP(statut='f',typ='TXM')),
                              DEFINITION_CHALEUR_SPECIFIQUE=FACT(statut='o',max='**',
                                                          CHALEUR_SPECIFIQUE = SIMP(statut='o',typ='R'),
                                                          REFERENCES = SIMP(statut='o',typ='I',max='**'),
                                                          COMMENTAIRES=SIMP(statut='f',typ='TXM')),
                              DEFINITION_CONDUCTIVITE_THERMIQUE=FACT(statut='o',max='**',
                                                          CONDUCTIVITE_THERMIQUE = SIMP(statut='o',typ='R'),
                                                          REFERENCES = SIMP(statut='o',typ='I',max='**'),
                                                          COMMENTAIRES=SIMP(statut='f',typ='TXM'))
                                                                    ),
                          proprietes_des_materiaux_orthotropes_2D = BLOC(condition="ISOTROPIE=='Mat\351riaux orthotropes' and DIMENSION==2",
                              DEFINITION_MASSE_VOLUMIQUE=FACT(statut='o',max='**',
                                                          MASSE_VOLUMIQUE = SIMP(statut='o',typ='R'),
                                                          REFERENCES = SIMP(statut='o',typ='I',max='**'),
                                                          COMMENTAIRES=SIMP(statut='f',typ='TXM')),
                              DEFINITION_CHALEUR_SPECIFIQUE=FACT(statut='o',max='**',
                                                          CHALEUR_SPECIFIQUE = SIMP(statut='o',typ='R'),
                                                          REFERENCES = SIMP(statut='o',typ='I',max='**'),
                                                          COMMENTAIRES=SIMP(statut='f',typ='TXM')),
                              DEFINITION_CONDUCTIVITE_THERMIQUE=FACT(statut='o',max='**',
                                                          CONDUCTIVITE_EN_X = SIMP(statut='o',typ='R'),
                                                          CONDUCTIVITE_EN_Y = SIMP(statut='o',typ='R'),
                                                          REFERENCES = SIMP(statut='o',typ='I',max='**'),
                                                          COMMENTAIRES=SIMP(statut='f',typ='TXM'))
                                                                         ),
                          proprietes_des_materiaux_orthotropes_3D = BLOC(condition="ISOTROPIE=='Mat\351riaux orthotropes' and DIMENSION==3",
                              DEFINITION_MASSE_VOLUMIQUE=FACT(statut='o',max='**',
                                                          MASSE_VOLUMIQUE = SIMP(statut='o',typ='R'),
                                                          REFERENCES = SIMP(statut='o',typ='I',max='**'),
                                                          COMMENTAIRES=SIMP(statut='f',typ='TXM')),
                              DEFINITION_CHALEUR_SPECIFIQUE=FACT(statut='o',max='**',
                                                          CHALEUR_SPECIFIQUE = SIMP(statut='o',typ='R'),
                                                          REFERENCES = SIMP(statut='o',typ='I',max='**'),
                                                          COMMENTAIRES=SIMP(statut='f',typ='TXM')),
                              DEFINITION_CONDUCTIVITE_THERMIQUE=FACT(statut='o',max='**',
                                                          CONDUCTIVITE_EN_X = SIMP(statut='o',typ='R'),
                                                          CONDUCTIVITE_EN_Y = SIMP(statut='o',typ='R'),
                                                          CONDUCTIVITE_EN_Z = SIMP(statut='o',typ='R'),
                                                          REFERENCES = SIMP(statut='o',typ='I',max='**'),
                                                          COMMENTAIRES=SIMP(statut='f',typ='TXM'))
                                                                         ),
                          proprietes_des_materiaux_anisotropes_2D = BLOC(condition="ISOTROPIE=='Mat\351riaux anisotropes' and DIMENSION==2",
                              DEFINITION_MASSE_VOLUMIQUE=FACT(statut='o',max='**',
                                                          MASSE_VOLUMIQUE = SIMP(statut='o',typ='R'),
                                                          REFERENCES = SIMP(statut='o',typ='I',max='**'),
                                                          COMMENTAIRES=SIMP(statut='f',typ='TXM')),
                              DEFINITION_CHALEUR_SPECIFIQUE=FACT(statut='o',max='**',
                                                          CHALEUR_SPECIFIQUE = SIMP(statut='o',typ='R'),
                                                          REFERENCES = SIMP(statut='o',typ='I',max='**'),
                                                          COMMENTAIRES=SIMP(statut='f',typ='TXM')),
                              DEFINITION_CONDUCTIVITE_THERMIQUE=FACT(statut='o',max='**',
                                                          CONDUCTIVITE_EN_X = SIMP(statut='o',typ='R'),
                                                          CONDUCTIVITE_EN_Y = SIMP(statut='o',typ='R'),
                                                          ANGLE_SUIVANT_Z = SIMP(statut='o',typ='R'),
                                                          REFERENCES = SIMP(statut='o',typ='I',max='**'),
                                                          COMMENTAIRES=SIMP(statut='f',typ='TXM'))
                                                                         ),
                          proprietes_des_materiaux_anisotropes_3D = BLOC(condition="ISOTROPIE=='Mat\351riaux anisotropes' and DIMENSION==3",
                              DEFINITION_MASSE_VOLUMIQUE=FACT(statut='o',max='**',
                                                          MASSE_VOLUMIQUE = SIMP(statut='o',typ='R'),
                                                          REFERENCES = SIMP(statut='o',typ='I',max='**'),
                                                          COMMENTAIRES=SIMP(statut='f',typ='TXM')),
                              DEFINITION_CHALEUR_SPECIFIQUE=FACT(statut='o',max='**',
                                                          CHALEUR_SPECIFIQUE = SIMP(statut='o',typ='R'),
                                                          REFERENCES = SIMP(statut='o',typ='I',max='**'),
                                                          COMMENTAIRES=SIMP(statut='f',typ='TXM')),
                              DEFINITION_CONDUCTIVITE_THERMIQUE=FACT(statut='o',max='**',
                                                          CONDUCTIVITE_EN_X = SIMP(statut='o',typ='R'),
                                                          CONDUCTIVITE_EN_Y = SIMP(statut='o',typ='R'),
                                                          CONDUCTIVITE_EN_Z = SIMP(statut='o',typ='R'),
                                                          ANGLE_SUIVANT_X = SIMP(statut='o',typ='R'),
                                                          ANGLE_SUIVANT_Y = SIMP(statut='o',typ='R'),
                                                          ANGLE_SUIVANT_Z = SIMP(statut='o',typ='R'),
                                                          REFERENCES = SIMP(statut='o',typ='I',max='**'),
                                                          COMMENTAIRES=SIMP(statut='f',typ='TXM'))
                                                                         ),
                          );

CONDITIONS_INITIALES=PROC(nom="CONDITIONS_INITIALES",op=10,
                          fr="Définition des conditions initiales",
                          niveau='cond_init',
                          Temperature_initiale = FACT(statut='o',max='**',
                                                      TEMPERATURE = SIMP(typ='R',statut='o',defaut=20),
                                                      REFERENCES = SIMP(statut='o',typ='I',max='**',defaut=-1),
                                                      COMMENTAIRES = SIMP(statut='f',typ='TXM')
                                                      )
                          );


CONDITIONS_LIMITES = PROC(nom='CONDITIONS_LIMITES',op=10,
                          niveau='cond_limi',
                          fr="Définition des conditions aux limites",
                          NOEUD_OU_FACE = SIMP(statut='o',typ='TXM',into=('NOEUD','FACE'),defaut='FACE'),
                          FLUX_SURFACIQUE=FACT(max='**',
                                               FLUX=SIMP(statut='o',typ='R',defaut=0),
                                               REFERENCES = SIMP(statut='o',typ='I',max='**'),
                                               COMMENTAIRES = SIMP(statut='f',typ='TXM')
                                               ),
                          DIRICHLET=FACT(max='**',
                                         TEMPERATURE=SIMP(statut='o',typ='R',defaut=20),
                                         REFERENCES = SIMP(statut='o',typ='I',max='**'),
                                         COMMENTAIRES = SIMP(statut='f',typ='TXM')
                                         ),

                          COEFFICIENT_ECHANGE=FACT(max='**',
                                                   TEMPERATURE=SIMP(statut='o',typ='R',defaut=20),
                                                   COEFFICIENT = SIMP(statut='o',typ='R',defaut=0),
                                                   REFERENCES = SIMP(statut='o',typ='I',max='**'),
                                                   COMMENTAIRES = SIMP(statut='f',typ='TXM')
                                                  ),
                          RESISTANCE_CONTACT=FACT(max='**',
                                                  RESISTANCE = SIMP(statut='o',typ='R',defaut=0),
                                                  REFERENCES = SIMP(statut='o',typ='I',max='**'),
                                                  COMMENTAIRES = SIMP(statut='f',typ='TXM')
                                                 ),
                         );

