
from Ihm import I_REGLE

from Noyau import N_SENSIBILITE 

class REUSE_SENSIBLE(I_REGLE.REGLE,N_SENSIBILITE.REUSE_SENSIBLE):pass
class CONCEPT_SENSIBLE(I_REGLE.REGLE,N_SENSIBILITE.CONCEPT_SENSIBLE):pass
class DERIVABLE(I_REGLE.REGLE,N_SENSIBILITE.DERIVABLE):pass

