# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desWidgetCommande.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetCommande(object):
    def setupUi(self, WidgetCommande):
        WidgetCommande.setObjectName("WidgetCommande")
        WidgetCommande.resize(1031, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetCommande.sizePolicy().hasHeightForWidth())
        WidgetCommande.setSizePolicy(sizePolicy)
        WidgetCommande.setMinimumSize(QtCore.QSize(0, 0))
        WidgetCommande.setToolTip("")
        WidgetCommande.setStyleSheet("background-color : rgb(224,223,222);\n"
"font : \'times\' 9px")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(WidgetCommande)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_2 = QtWidgets.QFrame(WidgetCommande)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.RBValide = MonBoutonValide(self.frame_2)
        self.RBValide.setMinimumSize(QtCore.QSize(17, 31))
        self.RBValide.setMaximumSize(QtCore.QSize(21, 31))
        self.RBValide.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBValide.setStyleSheet("border : 0px")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Editeur/icons/ast-green-ball.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBValide.setIcon(icon)
        self.RBValide.setIconSize(QtCore.QSize(21, 31))
        self.RBValide.setObjectName("RBValide")
        self.horizontalLayout.addWidget(self.RBValide)
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.labelNomCommande = MonLabelClic(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelNomCommande.sizePolicy().hasHeightForWidth())
        self.labelNomCommande.setSizePolicy(sizePolicy)
        self.labelNomCommande.setMinimumSize(QtCore.QSize(150, 31))
        self.labelNomCommande.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelNomCommande.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelNomCommande.setObjectName("labelNomCommande")
        self.horizontalLayout.addWidget(self.labelNomCommande)
        spacerItem2 = QtWidgets.QSpacerItem(2, 40, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.LENom = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LENom.sizePolicy().hasHeightForWidth())
        self.LENom.setSizePolicy(sizePolicy)
        self.LENom.setStyleSheet(" QLineEdit {\n"
"     border: 2px solid gray;\n"
"     border-radius: 10px;\n"
"     padding: 0 8px;\n"
"     background: darkgray;\n"
"   /*  selection-background-color: darkgray;*/\n"
" }\n"
"QLineEdit:disabled\n"
"{\n"
"    background: lightgray;\n"
"}\n"
"/*read-only {\n"
"     background: lightblue;*/")
        self.LENom.setReadOnly(False)
        self.LENom.setObjectName("LENom")
        self.horizontalLayout.addWidget(self.LENom)
        spacerItem3 = QtWidgets.QSpacerItem(2, 40, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RBRun = QtWidgets.QToolButton(self.frame_2)
        self.RBRun.setMinimumSize(QtCore.QSize(21, 31))
        self.RBRun.setMaximumSize(QtCore.QSize(21, 31))
        self.RBRun.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBRun.setStyleSheet("border : 0px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Editeur/icons/roue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBRun.setIcon(icon1)
        self.RBRun.setIconSize(QtCore.QSize(21, 31))
        self.RBRun.setObjectName("RBRun")
        self.horizontalLayout_2.addWidget(self.RBRun)
        self.RBInfo = QtWidgets.QToolButton(self.frame_2)
        self.RBInfo.setMinimumSize(QtCore.QSize(21, 31))
        self.RBInfo.setMaximumSize(QtCore.QSize(21, 31))
        self.RBInfo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBInfo.setStyleSheet("border : 0px")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Editeur/icons/point-interrogation30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBInfo.setIcon(icon2)
        self.RBInfo.setIconSize(QtCore.QSize(21, 31))
        self.RBInfo.setObjectName("RBInfo")
        self.horizontalLayout_2.addWidget(self.RBInfo)
        self.RBRegle = QtWidgets.QToolButton(self.frame_2)
        self.RBRegle.setMinimumSize(QtCore.QSize(21, 31))
        self.RBRegle.setMaximumSize(QtCore.QSize(21, 31))
        self.RBRegle.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBRegle.setStyleSheet("border : 0px")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Editeur/icons/lettreRblanc30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBRegle.setIcon(icon3)
        self.RBRegle.setIconSize(QtCore.QSize(21, 31))
        self.RBRegle.setObjectName("RBRegle")
        self.horizontalLayout_2.addWidget(self.RBRegle)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.RBPoubelle = QtWidgets.QToolButton(self.frame_2)
        self.RBPoubelle.setMinimumSize(QtCore.QSize(21, 31))
        self.RBPoubelle.setMaximumSize(QtCore.QSize(21, 31))
        self.RBPoubelle.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBPoubelle.setStyleSheet("border : 0px")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Editeur/icons/deleteRond.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBPoubelle.setIcon(icon4)
        self.RBPoubelle.setIconSize(QtCore.QSize(21, 31))
        self.RBPoubelle.setObjectName("RBPoubelle")
        self.horizontalLayout.addWidget(self.RBPoubelle)
        self.RBValide.raise_()
        self.labelNomCommande.raise_()
        self.LENom.raise_()
        self.RBPoubelle.raise_()
        self.horizontalLayout_4.addWidget(self.frame_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bCatalogue = QtWidgets.QPushButton(WidgetCommande)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bCatalogue.sizePolicy().hasHeightForWidth())
        self.bCatalogue.setSizePolicy(sizePolicy)
        self.bCatalogue.setMinimumSize(QtCore.QSize(160, 31))
        self.bCatalogue.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bCatalogue.setStyleSheet("background-color:rgb(104,110,149);\n"
"color :white;\n"
"border-radius : 12px\n"
"")
        self.bCatalogue.setAutoDefault(True)
        self.bCatalogue.setDefault(True)
        self.bCatalogue.setObjectName("bCatalogue")
        self.verticalLayout_2.addWidget(self.bCatalogue)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bAvant = QtWidgets.QPushButton(WidgetCommande)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bAvant.sizePolicy().hasHeightForWidth())
        self.bAvant.setSizePolicy(sizePolicy)
        self.bAvant.setMinimumSize(QtCore.QSize(60, 24))
        self.bAvant.setMaximumSize(QtCore.QSize(60, 24))
        self.bAvant.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bAvant.setStyleSheet("background-color:rgb(104,110,149);\n"
"color :white;\n"
"border-radius : 12px\n"
"")
        self.bAvant.setAutoDefault(True)
        self.bAvant.setDefault(True)
        self.bAvant.setObjectName("bAvant")
        self.horizontalLayout_3.addWidget(self.bAvant)
        self.bApres = QtWidgets.QPushButton(WidgetCommande)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bApres.sizePolicy().hasHeightForWidth())
        self.bApres.setSizePolicy(sizePolicy)
        self.bApres.setMinimumSize(QtCore.QSize(60, 24))
        self.bApres.setMaximumSize(QtCore.QSize(60, 24))
        self.bApres.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bApres.setStyleSheet("background-color:rgb(104,110,149);\n"
"color :white;\n"
"border-radius : 12px\n"
"")
        self.bApres.setAutoDefault(True)
        self.bApres.setDefault(True)
        self.bApres.setObjectName("bApres")
        self.horizontalLayout_3.addWidget(self.bApres)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.labelDoc = QtWidgets.QLabel(WidgetCommande)
        self.labelDoc.setObjectName("labelDoc")
        self.verticalLayout_3.addWidget(self.labelDoc)
        self.scrollAreaCommandes = QtWidgets.QScrollArea(WidgetCommande)
        self.scrollAreaCommandes.setMinimumSize(QtCore.QSize(0, 81))
        self.scrollAreaCommandes.setStyleSheet("background : rgb(247,247,247)\n"
"\n"
"\n"
"")
        self.scrollAreaCommandes.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollAreaCommandes.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollAreaCommandes.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollAreaCommandes.setWidgetResizable(True)
        self.scrollAreaCommandes.setObjectName("scrollAreaCommandes")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1013, 129))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.commandesLayout = QtWidgets.QVBoxLayout()
        self.commandesLayout.setContentsMargins(11, 11, 11, 11)
        self.commandesLayout.setSpacing(1)
        self.commandesLayout.setObjectName("commandesLayout")
        self.verticalLayout.addLayout(self.commandesLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.scrollAreaCommandes.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollAreaCommandes)

        self.retranslateUi(WidgetCommande)
        QtCore.QMetaObject.connectSlotsByName(WidgetCommande)

    def retranslateUi(self, WidgetCommande):
        _translate = QtCore.QCoreApplication.translate
        WidgetCommande.setWindowTitle(_translate("WidgetCommande", "DCommandeUnique"))
        self.RBValide.setToolTip(_translate("WidgetCommande", "Affiche le rapport de validité de la commande"))
        self.RBValide.setText(_translate("WidgetCommande", "..."))
        self.labelNomCommande.setText(_translate("WidgetCommande", "<html><head/><body><p><span style=\" color:#0000ff;\">commande </span></p></body></html>"))
        self.LENom.setToolTip(_translate("WidgetCommande", "Nom de l\'objet. Seuls, les objets valides peuvent être nommés"))
        self.RBRun.setToolTip(_translate("WidgetCommande", "Lance un script associé à la commande"))
        self.RBRun.setText(_translate("WidgetCommande", "..."))
        self.RBInfo.setToolTip(_translate("WidgetCommande", "ouvre un navigateur sur l\'aide contextuelle"))
        self.RBInfo.setText(_translate("WidgetCommande", "..."))
        self.RBRegle.setToolTip(_translate("WidgetCommande", "affiche les régles de validité"))
        self.RBRegle.setText(_translate("WidgetCommande", "..."))
        self.RBPoubelle.setToolTip(_translate("WidgetCommande", "Détruit la commande"))
        self.RBPoubelle.setText(_translate("WidgetCommande", "..."))
        self.bCatalogue.setToolTip(_translate("WidgetCommande", "Affiche les commandes possibles"))
        self.bCatalogue.setText(_translate("WidgetCommande", "&Commandes"))
        self.bCatalogue.setShortcut(_translate("WidgetCommande", "Shift+A, Alt+A, Alt+A, Alt+A"))
        self.bAvant.setToolTip(_translate("WidgetCommande", "Affiche le formulaire de la commande précédente"))
        self.bAvant.setText(_translate("WidgetCommande", "<<"))
        self.bAvant.setShortcut(_translate("WidgetCommande", "Shift+A, Alt+A, Alt+A, Alt+A"))
        self.bApres.setToolTip(_translate("WidgetCommande", "Affiche le formulaire de la commande suivante"))
        self.bApres.setText(_translate("WidgetCommande", ">>"))
        self.bApres.setShortcut(_translate("WidgetCommande", "Shift+A, Alt+A, Alt+A, Alt+A"))
        self.labelDoc.setText(_translate("WidgetCommande", "TextLabel"))

from monBoutonValide import MonBoutonValide
from monLabelClic import MonLabelClic

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetCommande = QtWidgets.QWidget()
    ui = Ui_WidgetCommande()
    ui.setupUi(WidgetCommande)
    WidgetCommande.show()
    sys.exit(app.exec_())

