# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desWidgetVide.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetVide(object):
    def setupUi(self, WidgetVide):
        WidgetVide.setObjectName("WidgetVide")
        WidgetVide.resize(1069, 55)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetVide.sizePolicy().hasHeightForWidth())
        WidgetVide.setSizePolicy(sizePolicy)
        WidgetVide.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(WidgetVide)
        self.horizontalLayout_3.setContentsMargins(0, 2, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(21, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.RBValide = MonBoutonValide(WidgetVide)
        self.RBValide.setMinimumSize(QtCore.QSize(21, 31))
        self.RBValide.setMaximumSize(QtCore.QSize(21, 35))
        self.RBValide.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBValide.setStyleSheet("border : 0px")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Editeur/icons/ast-green-ball.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBValide.setIcon(icon)
        self.RBValide.setIconSize(QtCore.QSize(32, 32))
        self.RBValide.setObjectName("RBValide")
        self.horizontalLayout.addWidget(self.RBValide)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(WidgetVide)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(300, 24))
        self.label.setMaximumSize(QtCore.QSize(178, 16777215))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEditVal = QtWidgets.QLineEdit(WidgetVide)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditVal.sizePolicy().hasHeightForWidth())
        self.lineEditVal.setSizePolicy(sizePolicy)
        self.lineEditVal.setMinimumSize(QtCore.QSize(0, 32))
        self.lineEditVal.setMaximumSize(QtCore.QSize(805, 16777215))
        self.lineEditVal.setStyleSheet("background:rgb(235,235,235);\n"
"border:0px;")
        self.lineEditVal.setObjectName("lineEditVal")
        self.horizontalLayout_3.addWidget(self.lineEditVal)
        spacerItem1 = QtWidgets.QSpacerItem(79, 17, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RBSalome = QtWidgets.QToolButton(WidgetVide)
        self.RBSalome.setMinimumSize(QtCore.QSize(25, 30))
        self.RBSalome.setMaximumSize(QtCore.QSize(25, 30))
        self.RBSalome.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBSalome.setStyleSheet("border : 0px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Editeur/icons/flecheSalome.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBSalome.setIcon(icon1)
        self.RBSalome.setIconSize(QtCore.QSize(32, 32))
        self.RBSalome.setObjectName("RBSalome")
        self.horizontalLayout_2.addWidget(self.RBSalome)
        self.RBSalomeVue = QtWidgets.QToolButton(WidgetVide)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RBSalomeVue.sizePolicy().hasHeightForWidth())
        self.RBSalomeVue.setSizePolicy(sizePolicy)
        self.RBSalomeVue.setMinimumSize(QtCore.QSize(25, 30))
        self.RBSalomeVue.setMaximumSize(QtCore.QSize(25, 30))
        self.RBSalomeVue.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBSalomeVue.setStyleSheet("border:0px")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Editeur/icons/icon_salome.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBSalomeVue.setIcon(icon2)
        self.RBSalomeVue.setIconSize(QtCore.QSize(32, 32))
        self.RBSalomeVue.setObjectName("RBSalomeVue")
        self.horizontalLayout_2.addWidget(self.RBSalomeVue)
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.RBPoubelle = QtWidgets.QToolButton(WidgetVide)
        self.RBPoubelle.setMinimumSize(QtCore.QSize(21, 31))
        self.RBPoubelle.setMaximumSize(QtCore.QSize(21, 31))
        self.RBPoubelle.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBPoubelle.setStyleSheet("border : 0px")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Editeur/icons/deleteRond.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBPoubelle.setIcon(icon3)
        self.RBPoubelle.setIconSize(QtCore.QSize(21, 32))
        self.RBPoubelle.setObjectName("RBPoubelle")
        self.horizontalLayout_2.addWidget(self.RBPoubelle)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(WidgetVide)
        QtCore.QMetaObject.connectSlotsByName(WidgetVide)
        WidgetVide.setTabOrder(self.lineEditVal, self.RBSalome)
        WidgetVide.setTabOrder(self.RBSalome, self.RBSalomeVue)
        WidgetVide.setTabOrder(self.RBSalomeVue, self.RBValide)
        WidgetVide.setTabOrder(self.RBValide, self.RBPoubelle)

    def retranslateUi(self, WidgetVide):
        _translate = QtCore.QCoreApplication.translate
        WidgetVide.setWindowTitle(_translate("WidgetVide", "Form"))
        self.RBValide.setText(_translate("WidgetVide", "..."))
        self.label.setText(_translate("WidgetVide", "<html><head/><body><p><span style=\" color:#0055ff;\">Label</span></p></body></html>"))
        self.lineEditVal.setText(_translate("WidgetVide", "Attend un objet de type XXXX. Il faut le créer"))
        self.RBSalome.setText(_translate("WidgetVide", "..."))
        self.RBSalomeVue.setText(_translate("WidgetVide", "..."))
        self.RBPoubelle.setText(_translate("WidgetVide", "..."))

from monBoutonValide import MonBoutonValide

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetVide = QtWidgets.QWidget()
    ui = Ui_WidgetVide()
    ui.setupUi(WidgetVide)
    WidgetVide.show()
    sys.exit(app.exec_())

