# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desWidgetParam.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetParam(object):
    def setupUi(self, WidgetParam):
        WidgetParam.setObjectName("WidgetParam")
        WidgetParam.resize(1058, 440)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetParam.sizePolicy().hasHeightForWidth())
        WidgetParam.setSizePolicy(sizePolicy)
        WidgetParam.setMinimumSize(QtCore.QSize(0, 0))
        WidgetParam.setToolTip("")
        WidgetParam.setStyleSheet("background-color : rgb(224,223,222);\n"
"font : \'times\' 9px")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(WidgetParam)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(WidgetParam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.RBValide = MonBoutonValide(self.frame_2)
        self.RBValide.setMinimumSize(QtCore.QSize(17, 31))
        self.RBValide.setMaximumSize(QtCore.QSize(21, 31))
        self.RBValide.setToolTip("")
        self.RBValide.setStyleSheet("border : 0px")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Editeur/icons/ast-green-ball.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBValide.setIcon(icon)
        self.RBValide.setIconSize(QtCore.QSize(21, 31))
        self.RBValide.setObjectName("RBValide")
        self.horizontalLayout.addWidget(self.RBValide)
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.labelNomCommande = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelNomCommande.sizePolicy().hasHeightForWidth())
        self.labelNomCommande.setSizePolicy(sizePolicy)
        self.labelNomCommande.setMinimumSize(QtCore.QSize(150, 31))
        self.labelNomCommande.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelNomCommande.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelNomCommande.setObjectName("labelNomCommande")
        self.horizontalLayout.addWidget(self.labelNomCommande)
        spacerItem2 = QtWidgets.QSpacerItem(78, 40, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.RBPoubelle = QtWidgets.QToolButton(self.frame_2)
        self.RBPoubelle.setMinimumSize(QtCore.QSize(21, 31))
        self.RBPoubelle.setMaximumSize(QtCore.QSize(21, 31))
        self.RBPoubelle.setStyleSheet("border : 0px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Editeur/icons/deleteRond.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBPoubelle.setIcon(icon1)
        self.RBPoubelle.setIconSize(QtCore.QSize(21, 31))
        self.RBPoubelle.setObjectName("RBPoubelle")
        self.horizontalLayout.addWidget(self.RBPoubelle)
        self.RBValide.raise_()
        self.labelNomCommande.raise_()
        self.RBPoubelle.raise_()
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bCatalogue = QtWidgets.QPushButton(WidgetParam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bCatalogue.sizePolicy().hasHeightForWidth())
        self.bCatalogue.setSizePolicy(sizePolicy)
        self.bCatalogue.setMinimumSize(QtCore.QSize(160, 31))
        self.bCatalogue.setStyleSheet("background-color:rgb(104,110,149);\n"
"color :white;\n"
"border-radius : 12px\n"
"")
        self.bCatalogue.setAutoDefault(True)
        self.bCatalogue.setDefault(True)
        self.bCatalogue.setObjectName("bCatalogue")
        self.verticalLayout_2.addWidget(self.bCatalogue)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bAvant = QtWidgets.QPushButton(WidgetParam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bAvant.sizePolicy().hasHeightForWidth())
        self.bAvant.setSizePolicy(sizePolicy)
        self.bAvant.setMinimumSize(QtCore.QSize(60, 24))
        self.bAvant.setMaximumSize(QtCore.QSize(60, 24))
        self.bAvant.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bAvant.setStyleSheet("background-color:rgb(104,110,149);\n"
"color :white;\n"
"border-radius : 12px\n"
"")
        self.bAvant.setAutoDefault(True)
        self.bAvant.setDefault(True)
        self.bAvant.setObjectName("bAvant")
        self.horizontalLayout_3.addWidget(self.bAvant)
        self.bApres = QtWidgets.QPushButton(WidgetParam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bApres.sizePolicy().hasHeightForWidth())
        self.bApres.setSizePolicy(sizePolicy)
        self.bApres.setMinimumSize(QtCore.QSize(60, 24))
        self.bApres.setMaximumSize(QtCore.QSize(60, 24))
        self.bApres.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bApres.setStyleSheet("background-color:rgb(104,110,149);\n"
"color :white;\n"
"border-radius : 12px\n"
"")
        self.bApres.setAutoDefault(True)
        self.bApres.setDefault(True)
        self.bApres.setObjectName("bApres")
        self.horizontalLayout_3.addWidget(self.bApres)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.scrollAreaCommandes = QtWidgets.QScrollArea(WidgetParam)
        self.scrollAreaCommandes.setMinimumSize(QtCore.QSize(0, 81))
        self.scrollAreaCommandes.setStyleSheet("background : rgb(247,247,247);\n"
"\n"
"\n"
"\n"
"")
        self.scrollAreaCommandes.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollAreaCommandes.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollAreaCommandes.setWidgetResizable(True)
        self.scrollAreaCommandes.setObjectName("scrollAreaCommandes")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1040, 349))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(25)
        self.gridLayout.setObjectName("gridLayout")
        self.textLabelVal = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.textLabelVal.setWordWrap(False)
        self.textLabelVal.setObjectName("textLabelVal")
        self.gridLayout.addWidget(self.textLabelVal, 1, 0, 1, 1)
        self.lineEditNom = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditNom.setMinimumSize(QtCore.QSize(231, 31))
        self.lineEditNom.setStyleSheet("background:rgb(235,235,235);\n"
"border:0px;\n"
"\n"
"")
        self.lineEditNom.setObjectName("lineEditNom")
        self.gridLayout.addWidget(self.lineEditNom, 0, 1, 1, 1)
        self.lineEditVal = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditVal.setMinimumSize(QtCore.QSize(231, 31))
        self.lineEditVal.setStyleSheet("background:rgb(235,235,235);\n"
"border:0px;")
        self.lineEditVal.setObjectName("lineEditVal")
        self.gridLayout.addWidget(self.lineEditVal, 1, 1, 1, 1)
        self.textLabelNom = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.textLabelNom.setWordWrap(False)
        self.textLabelNom.setObjectName("textLabelNom")
        self.gridLayout.addWidget(self.textLabelNom, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.bVerifie = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bVerifie.sizePolicy().hasHeightForWidth())
        self.bVerifie.setSizePolicy(sizePolicy)
        self.bVerifie.setMinimumSize(QtCore.QSize(160, 31))
        self.bVerifie.setStyleSheet("background-color:rgb(104,110,149);\n"
"color :white;\n"
"border-radius : 12px\n"
"")
        self.bVerifie.setAutoDefault(True)
        self.bVerifie.setDefault(True)
        self.bVerifie.setObjectName("bVerifie")
        self.gridLayout.addWidget(self.bVerifie, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.LECommentaire = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.LECommentaire.setWordWrap(False)
        self.LECommentaire.setObjectName("LECommentaire")
        self.verticalLayout.addWidget(self.LECommentaire)
        spacerItem4 = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.scrollAreaCommandes.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollAreaCommandes)

        self.retranslateUi(WidgetParam)
        QtCore.QMetaObject.connectSlotsByName(WidgetParam)
        WidgetParam.setTabOrder(self.RBPoubelle, self.bCatalogue)
        WidgetParam.setTabOrder(self.bCatalogue, self.RBValide)
        WidgetParam.setTabOrder(self.RBValide, self.scrollAreaCommandes)

    def retranslateUi(self, WidgetParam):
        _translate = QtCore.QCoreApplication.translate
        WidgetParam.setWindowTitle(_translate("WidgetParam", "DCommandeUnique"))
        self.RBValide.setText(_translate("WidgetParam", "..."))
        self.labelNomCommande.setText(_translate("WidgetParam", "<html><head/><body><p><span style=\" color:#000000;\">Paramètre</span></p></body></html>"))
        self.RBPoubelle.setToolTip(_translate("WidgetParam", "Détruit le commentaire"))
        self.RBPoubelle.setText(_translate("WidgetParam", "..."))
        self.bCatalogue.setToolTip(_translate("WidgetParam", "Affiche les commandes possibles"))
        self.bCatalogue.setText(_translate("WidgetParam", "&Commandes"))
        self.bCatalogue.setShortcut(_translate("WidgetParam", "Shift+A, Alt+A, Alt+A, Alt+A"))
        self.bAvant.setToolTip(_translate("WidgetParam", "Affiche le formulaire de la commande précédente"))
        self.bAvant.setText(_translate("WidgetParam", "<<"))
        self.bAvant.setShortcut(_translate("WidgetParam", "Shift+A, Alt+A, Alt+A, Alt+A"))
        self.bApres.setToolTip(_translate("WidgetParam", "Affiche le formulaire de la commande suivante"))
        self.bApres.setText(_translate("WidgetParam", ">>"))
        self.bApres.setShortcut(_translate("WidgetParam", "Shift+A, Alt+A, Alt+A, Alt+A"))
        self.textLabelVal.setText(_translate("WidgetParam", "<html><head/><body><p>Valeur: </p></body></html>"))
        self.textLabelNom.setText(_translate("WidgetParam", "<html><head/><body><p>Nom: </p></body></html>"))
        self.bVerifie.setToolTip(_translate("WidgetParam", "Affiche les commandes possibles"))
        self.bVerifie.setText(_translate("WidgetParam", "Verifie la valeur"))
        self.bVerifie.setShortcut(_translate("WidgetParam", "Shift+A, Alt+A, Alt+A, Alt+A"))
        self.LECommentaire.setText(_translate("WidgetParam", "<html><head/><body><p><br/></p></body></html>"))

from monBoutonValide import MonBoutonValide

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetParam = QtWidgets.QWidget()
    ui = Ui_WidgetParam()
    ui.setupUi(WidgetParam)
    WidgetParam.show()
    sys.exit(app.exec_())

