# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desWidgetSimpFichier.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetSimpFichier(object):
    def setupUi(self, WidgetSimpFichier):
        WidgetSimpFichier.setObjectName("WidgetSimpFichier")
        WidgetSimpFichier.resize(1095, 62)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetSimpFichier.sizePolicy().hasHeightForWidth())
        WidgetSimpFichier.setSizePolicy(sizePolicy)
        WidgetSimpFichier.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(WidgetSimpFichier)
        self.horizontalLayout_4.setContentsMargins(0, 1, 0, 1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(21, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.RBValide = MonBoutonValide(WidgetSimpFichier)
        self.RBValide.setMinimumSize(QtCore.QSize(21, 25))
        self.RBValide.setMaximumSize(QtCore.QSize(21, 25))
        self.RBValide.setStyleSheet("border : 0px")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Editeur/icons/ast-green-ball.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBValide.setIcon(icon)
        self.RBValide.setIconSize(QtCore.QSize(25, 25))
        self.RBValide.setObjectName("RBValide")
        self.horizontalLayout.addWidget(self.RBValide)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.label = MonLabelClic(WidgetSimpFichier)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(300, 25))
        self.label.setMaximumSize(QtCore.QSize(178, 16777215))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEditVal = QtWidgets.QLineEdit(WidgetSimpFichier)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditVal.sizePolicy().hasHeightForWidth())
        self.lineEditVal.setSizePolicy(sizePolicy)
        self.lineEditVal.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditVal.setMaximumSize(QtCore.QSize(805, 16777215))
        self.lineEditVal.setStyleSheet("background:rgb(235,235,235);\n"
"border:0px;")
        self.lineEditVal.setObjectName("lineEditVal")
        self.horizontalLayout_3.addWidget(self.lineEditVal)
        spacerItem2 = QtWidgets.QSpacerItem(71, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BFichier = QtWidgets.QToolButton(WidgetSimpFichier)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BFichier.sizePolicy().hasHeightForWidth())
        self.BFichier.setSizePolicy(sizePolicy)
        self.BFichier.setMaximumSize(QtCore.QSize(25, 25))
        self.BFichier.setStyleSheet("border : 0px")
        icon = QtGui.QIcon.fromTheme("system-file-manager")
        self.BFichier.setIcon(icon)
        self.BFichier.setIconSize(QtCore.QSize(25, 25))
        self.BFichier.setObjectName("BFichier")
        self.horizontalLayout_2.addWidget(self.BFichier)
        self.BVisuFichier = QtWidgets.QToolButton(WidgetSimpFichier)
        self.BVisuFichier.setMaximumSize(QtCore.QSize(25, 25))
        self.BVisuFichier.setStyleSheet("border:0px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Editeur/icons/visuFichier.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BVisuFichier.setIcon(icon1)
        self.BVisuFichier.setIconSize(QtCore.QSize(25, 25))
        self.BVisuFichier.setObjectName("BVisuFichier")
        self.horizontalLayout_2.addWidget(self.BVisuFichier)
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.RBPoubelle = QtWidgets.QToolButton(WidgetSimpFichier)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RBPoubelle.sizePolicy().hasHeightForWidth())
        self.RBPoubelle.setSizePolicy(sizePolicy)
        self.RBPoubelle.setMinimumSize(QtCore.QSize(21, 25))
        self.RBPoubelle.setMaximumSize(QtCore.QSize(21, 25))
        self.RBPoubelle.setStyleSheet("border : 0px")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Editeur/icons/deleteRond.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBPoubelle.setIcon(icon2)
        self.RBPoubelle.setIconSize(QtCore.QSize(21, 25))
        self.RBPoubelle.setObjectName("RBPoubelle")
        self.horizontalLayout_2.addWidget(self.RBPoubelle)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)

        self.retranslateUi(WidgetSimpFichier)
        QtCore.QMetaObject.connectSlotsByName(WidgetSimpFichier)
        WidgetSimpFichier.setTabOrder(self.lineEditVal, self.BFichier)
        WidgetSimpFichier.setTabOrder(self.BFichier, self.BVisuFichier)
        WidgetSimpFichier.setTabOrder(self.BVisuFichier, self.RBPoubelle)
        WidgetSimpFichier.setTabOrder(self.RBPoubelle, self.RBValide)

    def retranslateUi(self, WidgetSimpFichier):
        _translate = QtCore.QCoreApplication.translate
        WidgetSimpFichier.setWindowTitle(_translate("WidgetSimpFichier", "Form"))
        self.RBValide.setToolTip(_translate("WidgetSimpFichier", "Affiche le rapport de validité du mot-clef"))
        self.RBValide.setText(_translate("WidgetSimpFichier", "..."))
        self.label.setText(_translate("WidgetSimpFichier", "<html><head/><body><p>aaa</p><p>dqsklmdqm</p></body></html>"))
        self.BFichier.setToolTip(_translate("WidgetSimpFichier", "affiche l\'explorateur de fichier"))
        self.BFichier.setText(_translate("WidgetSimpFichier", "..."))
        self.BVisuFichier.setToolTip(_translate("WidgetSimpFichier", "ouvre le fichier choisi"))
        self.BVisuFichier.setText(_translate("WidgetSimpFichier", "..."))
        self.RBPoubelle.setToolTip(_translate("WidgetSimpFichier", "Détruit le mot-clef"))
        self.RBPoubelle.setText(_translate("WidgetSimpFichier", "..."))

from monBoutonValide import MonBoutonValide
from monLabelClic import MonLabelClic

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetSimpFichier = QtWidgets.QWidget()
    ui = Ui_WidgetSimpFichier()
    ui.setupUi(WidgetSimpFichier)
    WidgetSimpFichier.show()
    sys.exit(app.exec_())

