# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desWidgetPlusieursPlie.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetPlusieursPlie(object):
    def setupUi(self, WidgetPlusieursPlie):
        WidgetPlusieursPlie.setObjectName("WidgetPlusieursPlie")
        WidgetPlusieursPlie.resize(1095, 62)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetPlusieursPlie.sizePolicy().hasHeightForWidth())
        WidgetPlusieursPlie.setSizePolicy(sizePolicy)
        WidgetPlusieursPlie.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(WidgetPlusieursPlie)
        self.horizontalLayout_4.setContentsMargins(0, 1, 0, 1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BVisuListe = QtWidgets.QToolButton(WidgetPlusieursPlie)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BVisuListe.sizePolicy().hasHeightForWidth())
        self.BVisuListe.setSizePolicy(sizePolicy)
        self.BVisuListe.setMaximumSize(QtCore.QSize(21, 25))
        self.BVisuListe.setStyleSheet("border:0px")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Editeur/icons/plusnode.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BVisuListe.setIcon(icon)
        self.BVisuListe.setIconSize(QtCore.QSize(25, 25))
        self.BVisuListe.setObjectName("BVisuListe")
        self.horizontalLayout.addWidget(self.BVisuListe)
        self.RBValide = MonBoutonValide(WidgetPlusieursPlie)
        self.RBValide.setMinimumSize(QtCore.QSize(21, 25))
        self.RBValide.setMaximumSize(QtCore.QSize(21, 25))
        self.RBValide.setStyleSheet("border : 0px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Editeur/icons/ast-green-ball.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBValide.setIcon(icon1)
        self.RBValide.setIconSize(QtCore.QSize(25, 25))
        self.RBValide.setObjectName("RBValide")
        self.horizontalLayout.addWidget(self.RBValide)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.label = MonLabelClic(WidgetPlusieursPlie)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(300, 25))
        self.label.setMaximumSize(QtCore.QSize(178, 16777215))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEditVal = QtWidgets.QLineEdit(WidgetPlusieursPlie)
        self.lineEditVal.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditVal.sizePolicy().hasHeightForWidth())
        self.lineEditVal.setSizePolicy(sizePolicy)
        self.lineEditVal.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditVal.setMaximumSize(QtCore.QSize(805, 16777215))
        self.lineEditVal.setStyleSheet("background:rgb(195,195,195);\n"
"border:0px;\n"
"")
        self.lineEditVal.setObjectName("lineEditVal")
        self.horizontalLayout_3.addWidget(self.lineEditVal)
        spacerItem1 = QtWidgets.QSpacerItem(71, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.RBPoubelle = QtWidgets.QToolButton(WidgetPlusieursPlie)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RBPoubelle.sizePolicy().hasHeightForWidth())
        self.RBPoubelle.setSizePolicy(sizePolicy)
        self.RBPoubelle.setMinimumSize(QtCore.QSize(21, 25))
        self.RBPoubelle.setMaximumSize(QtCore.QSize(21, 25))
        self.RBPoubelle.setStyleSheet("border : 0px")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Editeur/icons/deleteRond.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBPoubelle.setIcon(icon2)
        self.RBPoubelle.setIconSize(QtCore.QSize(21, 25))
        self.RBPoubelle.setObjectName("RBPoubelle")
        self.horizontalLayout_2.addWidget(self.RBPoubelle)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)

        self.retranslateUi(WidgetPlusieursPlie)
        QtCore.QMetaObject.connectSlotsByName(WidgetPlusieursPlie)
        WidgetPlusieursPlie.setTabOrder(self.lineEditVal, self.RBPoubelle)
        WidgetPlusieursPlie.setTabOrder(self.RBPoubelle, self.RBValide)

    def retranslateUi(self, WidgetPlusieursPlie):
        _translate = QtCore.QCoreApplication.translate
        WidgetPlusieursPlie.setWindowTitle(_translate("WidgetPlusieursPlie", "Form"))
        self.BVisuListe.setToolTip(_translate("WidgetPlusieursPlie", "permet de gérer la liste"))
        self.BVisuListe.setText(_translate("WidgetPlusieursPlie", "..."))
        self.RBValide.setToolTip(_translate("WidgetPlusieursPlie", "Affiche le rapport de validité du mot-clef"))
        self.RBValide.setText(_translate("WidgetPlusieursPlie", "..."))
        self.label.setText(_translate("WidgetPlusieursPlie", "<html><head/><body><p>aaa</p><p>dqsklmdqm</p></body></html>"))
        self.RBPoubelle.setToolTip(_translate("WidgetPlusieursPlie", "Détruit le mot-clef"))
        self.RBPoubelle.setText(_translate("WidgetPlusieursPlie", "..."))

from monBoutonValide import MonBoutonValide
from monLabelClic import MonLabelClic

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetPlusieursPlie = QtWidgets.QWidget()
    ui = Ui_WidgetPlusieursPlie()
    ui.setupUi(WidgetPlusieursPlie)
    WidgetPlusieursPlie.show()
    sys.exit(app.exec_())

