# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desWidgetFact.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetFact(object):
    def setupUi(self, WidgetFact):
        WidgetFact.setObjectName("WidgetFact")
        WidgetFact.resize(949, 49)
        WidgetFact.setFocusPolicy(QtCore.Qt.StrongFocus)
        WidgetFact.setStyleSheet(" QGroupBox {\n"
"     border: 1px solid gray;\n"
"     border-radius: 5px;\n"
"     margin-top: 1ex; /* leave space at the top for the title */\n"
" }\n"
"\n"
" QGroupBox::title {\n"
"     padding: 0 3px;\n"
" }")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(WidgetFact)
        self.horizontalLayout_3.setContentsMargins(0, 2, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.RBPlie = QtWidgets.QToolButton(WidgetFact)
        self.RBPlie.setMinimumSize(QtCore.QSize(21, 15))
        self.RBPlie.setMaximumSize(QtCore.QSize(21, 21))
        self.RBPlie.setStyleSheet("border : 0px")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Editeur/icons/minusnode.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBPlie.setIcon(icon)
        self.RBPlie.setIconSize(QtCore.QSize(21, 21))
        self.RBPlie.setObjectName("RBPlie")
        self.verticalLayout.addWidget(self.RBPlie)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.line_7 = QtWidgets.QFrame(WidgetFact)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_4.addWidget(self.line_7)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.RBValide = MonBoutonValide(WidgetFact)
        self.RBValide.setMinimumSize(QtCore.QSize(17, 25))
        self.RBValide.setMaximumSize(QtCore.QSize(21, 25))
        self.RBValide.setStyleSheet("border : 0px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Editeur/icons/ast-green-ball.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBValide.setIcon(icon1)
        self.RBValide.setIconSize(QtCore.QSize(21, 25))
        self.RBValide.setObjectName("RBValide")
        self.gridLayout.addWidget(self.RBValide, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.GroupBox = MonLabelClic(WidgetFact)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupBox.sizePolicy().hasHeightForWidth())
        self.GroupBox.setSizePolicy(sizePolicy)
        self.GroupBox.setMinimumSize(QtCore.QSize(0, 25))
        self.GroupBox.setMaximumSize(QtCore.QSize(12121213, 25))
        self.GroupBox.setObjectName("GroupBox")
        self.horizontalLayout.addWidget(self.GroupBox)
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.line_4 = QtWidgets.QFrame(WidgetFact)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setMinimumSize(QtCore.QSize(200, 0))
        self.line_4.setMaximumSize(QtCore.QSize(1500, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RBInfo = QtWidgets.QToolButton(WidgetFact)
        self.RBInfo.setMinimumSize(QtCore.QSize(21, 25))
        self.RBInfo.setMaximumSize(QtCore.QSize(21, 25))
        self.RBInfo.setStyleSheet("border : 0px")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Editeur/icons/point-interrogation30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBInfo.setIcon(icon2)
        self.RBInfo.setIconSize(QtCore.QSize(21, 25))
        self.RBInfo.setObjectName("RBInfo")
        self.horizontalLayout_2.addWidget(self.RBInfo)
        self.RBRegle = QtWidgets.QToolButton(WidgetFact)
        self.RBRegle.setMinimumSize(QtCore.QSize(21, 25))
        self.RBRegle.setMaximumSize(QtCore.QSize(21, 25))
        self.RBRegle.setStyleSheet("border : 0px")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Editeur/icons/lettreRblanc30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBRegle.setIcon(icon3)
        self.RBRegle.setIconSize(QtCore.QSize(21, 25))
        self.RBRegle.setObjectName("RBRegle")
        self.horizontalLayout_2.addWidget(self.RBRegle)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.RBPoubelle = QtWidgets.QToolButton(WidgetFact)
        self.RBPoubelle.setMinimumSize(QtCore.QSize(21, 25))
        self.RBPoubelle.setMaximumSize(QtCore.QSize(21, 25))
        self.RBPoubelle.setStyleSheet("border : 0px")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Editeur/icons/deleteRond.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBPoubelle.setIcon(icon4)
        self.RBPoubelle.setIconSize(QtCore.QSize(21, 25))
        self.RBPoubelle.setObjectName("RBPoubelle")
        self.horizontalLayout.addWidget(self.RBPoubelle)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.commandesLayout = QtWidgets.QVBoxLayout()
        self.commandesLayout.setContentsMargins(-1, 2, -1, -1)
        self.commandesLayout.setSpacing(0)
        self.commandesLayout.setObjectName("commandesLayout")
        self.gridLayout.addLayout(self.commandesLayout, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)

        self.retranslateUi(WidgetFact)
        QtCore.QMetaObject.connectSlotsByName(WidgetFact)

    def retranslateUi(self, WidgetFact):
        _translate = QtCore.QCoreApplication.translate
        WidgetFact.setWindowTitle(_translate("WidgetFact", "Form"))
        self.RBPlie.setText(_translate("WidgetFact", "..."))
        self.RBValide.setText(_translate("WidgetFact", "..."))
        self.GroupBox.setText(_translate("WidgetFact", "<html><head/><body><p><span style=\" font-style:italic;\">TextLabel</span></p></body></html>"))
        self.RBInfo.setText(_translate("WidgetFact", "..."))
        self.RBRegle.setText(_translate("WidgetFact", "..."))
        self.RBPoubelle.setText(_translate("WidgetFact", "..."))

from monBoutonValide import MonBoutonValide
from monLabelClic import MonLabelClic

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetFact = QtWidgets.QWidget()
    ui = Ui_WidgetFact()
    ui.setupUi(WidgetFact)
    WidgetFact.show()
    sys.exit(app.exec_())

