# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desWidgetTuple3.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetTuple3(object):
    def setupUi(self, WidgetTuple3):
        WidgetTuple3.setObjectName("WidgetTuple3")
        WidgetTuple3.resize(1282, 61)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetTuple3.sizePolicy().hasHeightForWidth())
        WidgetTuple3.setSizePolicy(sizePolicy)
        WidgetTuple3.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(WidgetTuple3)
        self.horizontalLayout_3.setContentsMargins(1, 0, 0, 1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(21, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.RBValide = MonBoutonValide(WidgetTuple3)
        self.RBValide.setMinimumSize(QtCore.QSize(21, 25))
        self.RBValide.setMaximumSize(QtCore.QSize(21, 25))
        self.RBValide.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBValide.setStyleSheet("border : 0px")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Editeur/icons/ast-green-ball.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBValide.setIcon(icon)
        self.RBValide.setIconSize(QtCore.QSize(25, 25))
        self.RBValide.setObjectName("RBValide")
        self.horizontalLayout_2.addWidget(self.RBValide)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.label = MonLabelClic(WidgetTuple3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(300, 25))
        self.label.setMaximumSize(QtCore.QSize(178, 16777215))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(WidgetTuple3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEditVal1 = QtWidgets.QLineEdit(WidgetTuple3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditVal1.sizePolicy().hasHeightForWidth())
        self.lineEditVal1.setSizePolicy(sizePolicy)
        self.lineEditVal1.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditVal1.setMaximumSize(QtCore.QSize(805, 16777215))
        self.lineEditVal1.setStyleSheet("background:rgb(235,235,235);\n"
"border:0px;")
        self.lineEditVal1.setObjectName("lineEditVal1")
        self.horizontalLayout.addWidget(self.lineEditVal1)
        self.label_4 = QtWidgets.QLabel(WidgetTuple3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEditVal2 = QtWidgets.QLineEdit(WidgetTuple3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditVal2.sizePolicy().hasHeightForWidth())
        self.lineEditVal2.setSizePolicy(sizePolicy)
        self.lineEditVal2.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditVal2.setMaximumSize(QtCore.QSize(805, 16777215))
        self.lineEditVal2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEditVal2.setStyleSheet("background:rgb(235,235,235);\n"
"border:0px;")
        self.lineEditVal2.setObjectName("lineEditVal2")
        self.horizontalLayout.addWidget(self.lineEditVal2)
        self.label_3 = QtWidgets.QLabel(WidgetTuple3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEditVal3 = QtWidgets.QLineEdit(WidgetTuple3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditVal3.sizePolicy().hasHeightForWidth())
        self.lineEditVal3.setSizePolicy(sizePolicy)
        self.lineEditVal3.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditVal3.setMaximumSize(QtCore.QSize(805, 16777215))
        self.lineEditVal3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEditVal3.setStyleSheet("background:rgb(235,235,235);\n"
"border:0px;")
        self.lineEditVal3.setObjectName("lineEditVal3")
        self.horizontalLayout.addWidget(self.lineEditVal3)
        self.label_5 = QtWidgets.QLabel(WidgetTuple3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.RBPoubelle = QtWidgets.QToolButton(WidgetTuple3)
        self.RBPoubelle.setMinimumSize(QtCore.QSize(21, 25))
        self.RBPoubelle.setMaximumSize(QtCore.QSize(21, 25))
        self.RBPoubelle.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBPoubelle.setStyleSheet("border : 0px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Editeur/icons/deleteRond.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBPoubelle.setIcon(icon1)
        self.RBPoubelle.setIconSize(QtCore.QSize(25, 25))
        self.RBPoubelle.setObjectName("RBPoubelle")
        self.horizontalLayout.addWidget(self.RBPoubelle)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(WidgetTuple3)
        QtCore.QMetaObject.connectSlotsByName(WidgetTuple3)

    def retranslateUi(self, WidgetTuple3):
        _translate = QtCore.QCoreApplication.translate
        WidgetTuple3.setWindowTitle(_translate("WidgetTuple3", "Form"))
        self.RBValide.setToolTip(_translate("WidgetTuple3", "Affiche le rapport de validation du mot-clef"))
        self.RBValide.setText(_translate("WidgetTuple3", "..."))
        self.label.setText(_translate("WidgetTuple3", "<html><head/><body><p>aaa</p><p>dqsklmdqm</p></body></html>"))
        self.label_2.setText(_translate("WidgetTuple3", "<html><head/><body><p><span style=\" font-size:14pt;\">(</span></p></body></html>"))
        self.label_4.setText(_translate("WidgetTuple3", "<html><head/><body><p><span style=\" font-size:14pt;\">,</span></p></body></html>"))
        self.label_3.setText(_translate("WidgetTuple3", "<html><head/><body><p><span style=\" font-size:14pt;\">,</span></p></body></html>"))
        self.label_5.setText(_translate("WidgetTuple3", "<html><head/><body><p><span style=\" font-size:14pt;\">)</span></p></body></html>"))
        self.RBPoubelle.setToolTip(_translate("WidgetTuple3", "Détruit le mot-clef"))
        self.RBPoubelle.setText(_translate("WidgetTuple3", "..."))

from monBoutonValide import MonBoutonValide
from monLabelClic import MonLabelClic

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetTuple3 = QtWidgets.QWidget()
    ui = Ui_WidgetTuple3()
    ui.setupUi(WidgetTuple3)
    WidgetTuple3.show()
    sys.exit(app.exec_())

