# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desWidgetSDCOInto.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetSDCOInto(object):
    def setupUi(self, WidgetSDCOInto):
        WidgetSDCOInto.setObjectName("WidgetSDCOInto")
        WidgetSDCOInto.resize(858, 312)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetSDCOInto.sizePolicy().hasHeightForWidth())
        WidgetSDCOInto.setSizePolicy(sizePolicy)
        WidgetSDCOInto.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(WidgetSDCOInto)
        self.horizontalLayout_2.setContentsMargins(0, 1, 0, 1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(21, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.RBValide = MonBoutonValide(WidgetSDCOInto)
        self.RBValide.setMinimumSize(QtCore.QSize(21, 25))
        self.RBValide.setMaximumSize(QtCore.QSize(21, 25))
        self.RBValide.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBValide.setStyleSheet("border : 0px")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Editeur/icons/ast-green-ball.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBValide.setIcon(icon)
        self.RBValide.setIconSize(QtCore.QSize(25, 25))
        self.RBValide.setObjectName("RBValide")
        self.horizontalLayout.addWidget(self.RBValide)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.label = MonLabelClic(WidgetSDCOInto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(300, 25))
        self.label.setMaximumSize(QtCore.QSize(178, 16777215))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.frame = QtWidgets.QFrame(WidgetSDCOInto)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textLabel2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textLabel2.sizePolicy().hasHeightForWidth())
        self.textLabel2.setSizePolicy(sizePolicy)
        self.textLabel2.setMaximumSize(QtCore.QSize(16777215, 31))
        self.textLabel2.setWordWrap(False)
        self.textLabel2.setObjectName("textLabel2")
        self.verticalLayout_3.addWidget(self.textLabel2)
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 200))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 462, 200))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.LBSDCO = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.LBSDCO.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LBSDCO.setObjectName("LBSDCO")
        self.gridLayout.addWidget(self.LBSDCO, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.LESDCO = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LESDCO.sizePolicy().hasHeightForWidth())
        self.LESDCO.setSizePolicy(sizePolicy)
        self.LESDCO.setMinimumSize(QtCore.QSize(0, 25))
        self.LESDCO.setMaximumSize(QtCore.QSize(805, 31))
        self.LESDCO.setStyleSheet("background:rgb(235,235,235);\n"
"border:0px;")
        self.LESDCO.setObjectName("LESDCO")
        self.verticalLayout_3.addWidget(self.LESDCO)
        self.horizontalLayout_2.addWidget(self.frame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.RBPoubelle = QtWidgets.QToolButton(WidgetSDCOInto)
        self.RBPoubelle.setMinimumSize(QtCore.QSize(21, 31))
        self.RBPoubelle.setMaximumSize(QtCore.QSize(21, 31))
        self.RBPoubelle.setStyleSheet("border : 0px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Editeur/icons/deleteRond.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBPoubelle.setIcon(icon1)
        self.RBPoubelle.setIconSize(QtCore.QSize(32, 32))
        self.RBPoubelle.setObjectName("RBPoubelle")
        self.verticalLayout.addWidget(self.RBPoubelle)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(WidgetSDCOInto)
        QtCore.QMetaObject.connectSlotsByName(WidgetSDCOInto)

    def retranslateUi(self, WidgetSDCOInto):
        _translate = QtCore.QCoreApplication.translate
        WidgetSDCOInto.setWindowTitle(_translate("WidgetSDCOInto", "Form"))
        self.RBValide.setToolTip(_translate("WidgetSDCOInto", "Affiche le rapport de validation du mot-clef"))
        self.RBValide.setText(_translate("WidgetSDCOInto", "..."))
        self.label.setText(_translate("WidgetSDCOInto", "<html><head/><body><p>aaa</p><p>dqsklmdqm</p></body></html>"))
        self.textLabel2.setText(_translate("WidgetSDCOInto", "<html><head/><body><p>Structures de données du type requis </p><p><br/></p></body></html>"))
        self.label_3.setText(_translate("WidgetSDCOInto", "<html><head/><body><p>ou Nom du concept</p></body></html>"))
        self.RBPoubelle.setToolTip(_translate("WidgetSDCOInto", "Détruit le mot-clef"))
        self.RBPoubelle.setText(_translate("WidgetSDCOInto", "..."))

from monBoutonValide import MonBoutonValide
from monLabelClic import MonLabelClic

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetSDCOInto = QtWidgets.QWidget()
    ui = Ui_WidgetSDCOInto()
    ui.setupUi(WidgetSDCOInto)
    WidgetSDCOInto.show()
    sys.exit(app.exec_())

