# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desWidgetInactif.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetInactif(object):
    def setupUi(self, WidgetInactif):
        WidgetInactif.setObjectName("WidgetInactif")
        WidgetInactif.resize(946, 495)
        WidgetInactif.setMinimumSize(QtCore.QSize(350, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(WidgetInactif)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame = QtWidgets.QFrame(WidgetInactif)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.RBValide = QtWidgets.QCheckBox(self.frame)
        self.RBValide.setMinimumSize(QtCore.QSize(17, 31))
        self.RBValide.setMaximumSize(QtCore.QSize(21, 31))
        self.RBValide.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBValide.setStyleSheet("border : 0px")
        self.RBValide.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Editeur/icons/ast-white-square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBValide.setIcon(icon)
        self.RBValide.setIconSize(QtCore.QSize(21, 31))
        self.RBValide.setCheckable(False)
        self.RBValide.setObjectName("RBValide")
        self.horizontalLayout.addWidget(self.RBValide)
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.labelNomCommande = MonLabelClic(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelNomCommande.sizePolicy().hasHeightForWidth())
        self.labelNomCommande.setSizePolicy(sizePolicy)
        self.labelNomCommande.setMinimumSize(QtCore.QSize(150, 31))
        self.labelNomCommande.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelNomCommande.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelNomCommande.setObjectName("labelNomCommande")
        self.horizontalLayout.addWidget(self.labelNomCommande)
        spacerItem2 = QtWidgets.QSpacerItem(2, 40, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(2, 40, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.RBPoubelle = QtWidgets.QToolButton(self.frame)
        self.RBPoubelle.setMinimumSize(QtCore.QSize(21, 31))
        self.RBPoubelle.setMaximumSize(QtCore.QSize(21, 31))
        self.RBPoubelle.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBPoubelle.setStyleSheet("border : 0px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Editeur/icons/deleteRond.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBPoubelle.setIcon(icon1)
        self.RBPoubelle.setIconSize(QtCore.QSize(21, 31))
        self.RBPoubelle.setObjectName("RBPoubelle")
        self.horizontalLayout.addWidget(self.RBPoubelle)
        self.RBValide.raise_()
        self.labelNomCommande.raise_()
        self.RBPoubelle.raise_()
        self.horizontalLayout_4.addWidget(self.frame)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bCatalogue = QtWidgets.QPushButton(WidgetInactif)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bCatalogue.sizePolicy().hasHeightForWidth())
        self.bCatalogue.setSizePolicy(sizePolicy)
        self.bCatalogue.setMinimumSize(QtCore.QSize(160, 31))
        self.bCatalogue.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bCatalogue.setStyleSheet("background-color:rgb(104,110,149);\n"
"color :white;\n"
"border-radius : 12px\n"
"")
        self.bCatalogue.setAutoDefault(True)
        self.bCatalogue.setDefault(True)
        self.bCatalogue.setObjectName("bCatalogue")
        self.verticalLayout_2.addWidget(self.bCatalogue)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bAvant = QtWidgets.QPushButton(WidgetInactif)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bAvant.sizePolicy().hasHeightForWidth())
        self.bAvant.setSizePolicy(sizePolicy)
        self.bAvant.setMinimumSize(QtCore.QSize(60, 24))
        self.bAvant.setMaximumSize(QtCore.QSize(60, 24))
        self.bAvant.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bAvant.setStyleSheet("background-color:rgb(104,110,149);\n"
"color :white;\n"
"border-radius : 12px\n"
"")
        self.bAvant.setAutoDefault(True)
        self.bAvant.setDefault(True)
        self.bAvant.setObjectName("bAvant")
        self.horizontalLayout_3.addWidget(self.bAvant)
        self.bApres = QtWidgets.QPushButton(WidgetInactif)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bApres.sizePolicy().hasHeightForWidth())
        self.bApres.setSizePolicy(sizePolicy)
        self.bApres.setMinimumSize(QtCore.QSize(60, 24))
        self.bApres.setMaximumSize(QtCore.QSize(60, 24))
        self.bApres.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bApres.setStyleSheet("background-color:rgb(104,110,149);\n"
"color :white;\n"
"border-radius : 12px\n"
"")
        self.bApres.setAutoDefault(True)
        self.bApres.setDefault(True)
        self.bApres.setObjectName("bApres")
        self.horizontalLayout_3.addWidget(self.bApres)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 66, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.textLabel1_3 = QtWidgets.QLabel(WidgetInactif)
        self.textLabel1_3.setMinimumSize(QtCore.QSize(0, 0))
        self.textLabel1_3.setWordWrap(False)
        self.textLabel1_3.setObjectName("textLabel1_3")
        self.verticalLayout.addWidget(self.textLabel1_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 67, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.textLabel1 = QtWidgets.QLabel(WidgetInactif)
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.verticalLayout.addWidget(self.textLabel1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 66, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)

        self.retranslateUi(WidgetInactif)
        QtCore.QMetaObject.connectSlotsByName(WidgetInactif)

    def retranslateUi(self, WidgetInactif):
        _translate = QtCore.QCoreApplication.translate
        WidgetInactif.setWindowTitle(_translate("WidgetInactif", "DInactif"))
        self.RBValide.setToolTip(_translate("WidgetInactif", "Affiche le rapport de validité de la commande"))
        self.labelNomCommande.setText(_translate("WidgetInactif", "<html><head/><body><p><span style=\" color:#0000ff;\">commande </span></p></body></html>"))
        self.RBPoubelle.setToolTip(_translate("WidgetInactif", "Détruit la commande"))
        self.RBPoubelle.setText(_translate("WidgetInactif", "..."))
        self.bCatalogue.setToolTip(_translate("WidgetInactif", "Affiche les commandes possibles"))
        self.bCatalogue.setText(_translate("WidgetInactif", "&Commandes"))
        self.bCatalogue.setShortcut(_translate("WidgetInactif", "Shift+A, Alt+A, Alt+A, Alt+A"))
        self.bAvant.setToolTip(_translate("WidgetInactif", "Affiche le formulaire de la commande précédente"))
        self.bAvant.setText(_translate("WidgetInactif", "<<"))
        self.bAvant.setShortcut(_translate("WidgetInactif", "Shift+A, Alt+A, Alt+A, Alt+A"))
        self.bApres.setToolTip(_translate("WidgetInactif", "Affiche le formulaire de la commande suivante"))
        self.bApres.setText(_translate("WidgetInactif", ">>"))
        self.bApres.setShortcut(_translate("WidgetInactif", "Shift+A, Alt+A, Alt+A, Alt+A"))
        self.textLabel1_3.setText(_translate("WidgetInactif", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Le noeud sélectionné</span></p><p align=\"center\"><span style=\" font-size:16pt;\">ne correspond pas à un objet actif</span></p></body></html>"))
        self.textLabel1.setText(_translate("WidgetInactif", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:x-large;\"><span style=\" font-size:x-large;\">Seules les commandes placées</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:x-large;\"><span style=\" font-size:x-large;\"> entre : DEBUT / FIN sont actives </span></p></body></html>"))

from monLabelClic import MonLabelClic

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetInactif = QtWidgets.QWidget()
    ui = Ui_WidgetInactif()
    ui.setupUi(WidgetInactif)
    WidgetInactif.show()
    sys.exit(app.exec_())

