# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desWidgetPlusieursBase.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetPlusieursBase(object):
    def setupUi(self, WidgetPlusieursBase):
        WidgetPlusieursBase.setObjectName("WidgetPlusieursBase")
        WidgetPlusieursBase.resize(764, 202)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetPlusieursBase.sizePolicy().hasHeightForWidth())
        WidgetPlusieursBase.setSizePolicy(sizePolicy)
        WidgetPlusieursBase.setMinimumSize(QtCore.QSize(100, 20))
        WidgetPlusieursBase.setStyleSheet("/* QFrame {\n"
"border: 1px solid gray;\n"
"}*/\n"
"")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(WidgetPlusieursBase)
        self.horizontalLayout_2.setContentsMargins(0, 2, 2, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BFermeListe = QtWidgets.QToolButton(WidgetPlusieursBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BFermeListe.sizePolicy().hasHeightForWidth())
        self.BFermeListe.setSizePolicy(sizePolicy)
        self.BFermeListe.setMaximumSize(QtCore.QSize(21, 25))
        self.BFermeListe.setStyleSheet("border:0px")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Editeur/icons/minusnode.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BFermeListe.setIcon(icon)
        self.BFermeListe.setIconSize(QtCore.QSize(25, 25))
        self.BFermeListe.setObjectName("BFermeListe")
        self.horizontalLayout.addWidget(self.BFermeListe)
        self.RBValide = MonBoutonValide(WidgetPlusieursBase)
        self.RBValide.setMinimumSize(QtCore.QSize(21, 25))
        self.RBValide.setMaximumSize(QtCore.QSize(21, 25))
        self.RBValide.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBValide.setStyleSheet("border : 0px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Editeur/icons/ast-green-ball.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBValide.setIcon(icon1)
        self.RBValide.setIconSize(QtCore.QSize(25, 25))
        self.RBValide.setObjectName("RBValide")
        self.horizontalLayout.addWidget(self.RBValide)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = MonLabelClic(WidgetPlusieursBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(300, 25))
        self.label.setMaximumSize(QtCore.QSize(178, 16777215))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.scrollArea_2 = QtWidgets.QScrollArea(WidgetPlusieursBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 112, 138))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.monCommentaireLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monCommentaireLabel.sizePolicy().hasHeightForWidth())
        self.monCommentaireLabel.setSizePolicy(sizePolicy)
        self.monCommentaireLabel.setObjectName("monCommentaireLabel")
        self.horizontalLayout_7.addWidget(self.monCommentaireLabel)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(WidgetPlusieursBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(400, 50))
        self.scrollArea.setStyleSheet("background : rgb(247,247,247);\n"
"border: 1px solid gray;\n"
"/* QFrame {\n"
"border: 1px solid gray;\n"
"}*/\n"
"\n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.scrollArea.setObjectName("scrollArea")
        self.verticalWidgetLE = QtWidgets.QWidget()
        self.verticalWidgetLE.setGeometry(QtCore.QRect(0, 0, 398, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidgetLE.sizePolicy().hasHeightForWidth())
        self.verticalWidgetLE.setSizePolicy(sizePolicy)
        self.verticalWidgetLE.setObjectName("verticalWidgetLE")
        self.verticalLayoutLE = QtWidgets.QVBoxLayout(self.verticalWidgetLE)
        self.verticalLayoutLE.setContentsMargins(2, 0, 2, 0)
        self.verticalLayoutLE.setSpacing(2)
        self.verticalLayoutLE.setObjectName("verticalLayoutLE")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutLE.addItem(spacerItem1)
        self.scrollArea.setWidget(self.verticalWidgetLE)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.frame = QtWidgets.QFrame(WidgetPlusieursBase)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.RBHaut = QtWidgets.QToolButton(self.frame)
        self.RBHaut.setMinimumSize(QtCore.QSize(21, 31))
        self.RBHaut.setMaximumSize(QtCore.QSize(21, 31))
        self.RBHaut.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBHaut.setStyleSheet("border : 0px")
        icon = QtGui.QIcon.fromTheme("go-up")
        self.RBHaut.setIcon(icon)
        self.RBHaut.setIconSize(QtCore.QSize(32, 32))
        self.RBHaut.setObjectName("RBHaut")
        self.horizontalLayout_4.addWidget(self.RBHaut)
        self.RBBas = QtWidgets.QToolButton(self.frame)
        self.RBBas.setMinimumSize(QtCore.QSize(21, 31))
        self.RBBas.setMaximumSize(QtCore.QSize(21, 31))
        self.RBBas.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBBas.setStyleSheet("border : 0px")
        icon = QtGui.QIcon.fromTheme("go-down")
        self.RBBas.setIcon(icon)
        self.RBBas.setIconSize(QtCore.QSize(32, 32))
        self.RBBas.setObjectName("RBBas")
        self.horizontalLayout_4.addWidget(self.RBBas)
        self.RBMoins = QtWidgets.QToolButton(self.frame)
        self.RBMoins.setMinimumSize(QtCore.QSize(21, 31))
        self.RBMoins.setMaximumSize(QtCore.QSize(21, 31))
        self.RBMoins.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBMoins.setStyleSheet("border : 0px")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Editeur/icons/MoinsBleu2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.RBMoins.setIcon(icon2)
        self.RBMoins.setIconSize(QtCore.QSize(32, 32))
        self.RBMoins.setObjectName("RBMoins")
        self.horizontalLayout_4.addWidget(self.RBMoins)
        self.RBPlus = QtWidgets.QToolButton(self.frame)
        self.RBPlus.setMinimumSize(QtCore.QSize(21, 31))
        self.RBPlus.setMaximumSize(QtCore.QSize(21, 31))
        self.RBPlus.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBPlus.setStyleSheet("border : 0px")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Editeur/icons/PlusBleu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBPlus.setIcon(icon3)
        self.RBPlus.setIconSize(QtCore.QSize(32, 32))
        self.RBPlus.setObjectName("RBPlus")
        self.horizontalLayout_4.addWidget(self.RBPlus)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.RBVoisListe = QtWidgets.QToolButton(self.frame)
        self.RBVoisListe.setMinimumSize(QtCore.QSize(21, 31))
        self.RBVoisListe.setMaximumSize(QtCore.QSize(21, 31))
        self.RBVoisListe.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBVoisListe.setStyleSheet("border : 0px")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Editeur/icons/verre-loupe-icone-6087-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBVoisListe.setIcon(icon4)
        self.RBVoisListe.setIconSize(QtCore.QSize(32, 32))
        self.RBVoisListe.setObjectName("RBVoisListe")
        self.horizontalLayout_6.addWidget(self.RBVoisListe)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.RBSalome = QtWidgets.QToolButton(self.frame)
        self.RBSalome.setMinimumSize(QtCore.QSize(21, 31))
        self.RBSalome.setMaximumSize(QtCore.QSize(21, 31))
        self.RBSalome.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBSalome.setStyleSheet("border : 0px")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Editeur/icons/flecheSalome.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBSalome.setIcon(icon5)
        self.RBSalome.setIconSize(QtCore.QSize(32, 32))
        self.RBSalome.setObjectName("RBSalome")
        self.horizontalLayout_5.addWidget(self.RBSalome)
        self.RBSalomeVue = QtWidgets.QToolButton(self.frame)
        self.RBSalomeVue.setMinimumSize(QtCore.QSize(21, 31))
        self.RBSalomeVue.setMaximumSize(QtCore.QSize(21, 31))
        self.RBSalomeVue.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBSalomeVue.setStyleSheet("border : 0px")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../Editeur/icons/eye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBSalomeVue.setIcon(icon6)
        self.RBSalomeVue.setIconSize(QtCore.QSize(32, 32))
        self.RBSalomeVue.setObjectName("RBSalomeVue")
        self.horizontalLayout_5.addWidget(self.RBSalomeVue)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BSelectFichier = QtWidgets.QToolButton(WidgetPlusieursBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSelectFichier.sizePolicy().hasHeightForWidth())
        self.BSelectFichier.setSizePolicy(sizePolicy)
        self.BSelectFichier.setMaximumSize(QtCore.QSize(25, 30))
        self.BSelectFichier.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.BSelectFichier.setStyleSheet("border:0px")
        icon = QtGui.QIcon.fromTheme("text-x-generic")
        self.BSelectFichier.setIcon(icon)
        self.BSelectFichier.setIconSize(QtCore.QSize(32, 32))
        self.BSelectFichier.setObjectName("BSelectFichier")
        self.horizontalLayout_3.addWidget(self.BSelectFichier)
        spacerItem5 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.RBPoubelle = QtWidgets.QToolButton(WidgetPlusieursBase)
        self.RBPoubelle.setMinimumSize(QtCore.QSize(21, 31))
        self.RBPoubelle.setMaximumSize(QtCore.QSize(21, 31))
        self.RBPoubelle.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBPoubelle.setStyleSheet("border : 0px")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../Editeur/icons/deleteRond.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBPoubelle.setIcon(icon7)
        self.RBPoubelle.setIconSize(QtCore.QSize(32, 32))
        self.RBPoubelle.setObjectName("RBPoubelle")
        self.horizontalLayout_3.addWidget(self.RBPoubelle)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.label.raise_()
        self.monCommentaireLabel.raise_()
        self.scrollArea_2.raise_()

        self.retranslateUi(WidgetPlusieursBase)
        QtCore.QMetaObject.connectSlotsByName(WidgetPlusieursBase)
        WidgetPlusieursBase.setTabOrder(self.scrollArea, self.RBHaut)
        WidgetPlusieursBase.setTabOrder(self.RBHaut, self.RBBas)
        WidgetPlusieursBase.setTabOrder(self.RBBas, self.RBMoins)
        WidgetPlusieursBase.setTabOrder(self.RBMoins, self.RBVoisListe)
        WidgetPlusieursBase.setTabOrder(self.RBVoisListe, self.RBSalome)
        WidgetPlusieursBase.setTabOrder(self.RBSalome, self.RBSalomeVue)
        WidgetPlusieursBase.setTabOrder(self.RBSalomeVue, self.BSelectFichier)
        WidgetPlusieursBase.setTabOrder(self.BSelectFichier, self.RBPoubelle)

    def retranslateUi(self, WidgetPlusieursBase):
        _translate = QtCore.QCoreApplication.translate
        WidgetPlusieursBase.setWindowTitle(_translate("WidgetPlusieursBase", "Form"))
        self.BFermeListe.setToolTip(_translate("WidgetPlusieursBase", "permet de gérer la liste"))
        self.BFermeListe.setText(_translate("WidgetPlusieursBase", "..."))
        self.RBValide.setToolTip(_translate("WidgetPlusieursBase", "Affiche le rapport de validation du mot-clef"))
        self.RBValide.setText(_translate("WidgetPlusieursBase", "..."))
        self.label.setText(_translate("WidgetPlusieursBase", "<html><head/><body><p>aaa</p><p>dqsklmdqm</p></body></html>"))
        self.monCommentaireLabel.setText(_translate("WidgetPlusieursBase", "TextLabel"))
        self.RBHaut.setToolTip(_translate("WidgetPlusieursBase", "Remonte la ligne"))
        self.RBHaut.setText(_translate("WidgetPlusieursBase", "..."))
        self.RBBas.setToolTip(_translate("WidgetPlusieursBase", "Descend la ligne"))
        self.RBBas.setText(_translate("WidgetPlusieursBase", "..."))
        self.RBMoins.setToolTip(_translate("WidgetPlusieursBase", "supprime une ligne"))
        self.RBMoins.setText(_translate("WidgetPlusieursBase", "..."))
        self.RBPlus.setToolTip(_translate("WidgetPlusieursBase", "Ajoute une ligne"))
        self.RBPlus.setText(_translate("WidgetPlusieursBase", "..."))
        self.RBVoisListe.setToolTip(_translate("WidgetPlusieursBase", "Montre l\'ensemble des valeurs"))
        self.RBVoisListe.setText(_translate("WidgetPlusieursBase", "..."))
        self.RBSalome.setToolTip(_translate("WidgetPlusieursBase", "Sélectionne depuis Salome"))
        self.RBSalome.setText(_translate("WidgetPlusieursBase", "..."))
        self.RBSalomeVue.setToolTip(_translate("WidgetPlusieursBase", "Visualise dans Salome"))
        self.RBSalomeVue.setText(_translate("WidgetPlusieursBase", "..."))
        self.BSelectFichier.setToolTip(_translate("WidgetPlusieursBase", "Ouvre un fichier de sélection des valeurs"))
        self.BSelectFichier.setText(_translate("WidgetPlusieursBase", "..."))
        self.RBPoubelle.setToolTip(_translate("WidgetPlusieursBase", "Détruit le mot-clef"))
        self.RBPoubelle.setText(_translate("WidgetPlusieursBase", "..."))

from monBoutonValide import MonBoutonValide
from monLabelClic import MonLabelClic

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetPlusieursBase = QtWidgets.QWidget()
    ui = Ui_WidgetPlusieursBase()
    ui.setupUi(WidgetPlusieursBase)
    WidgetPlusieursBase.show()
    sys.exit(app.exec_())

