# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desWidgetPlusieursIntoOrdonne.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetPlusieursIntoOrdonne(object):
    def setupUi(self, WidgetPlusieursIntoOrdonne):
        WidgetPlusieursIntoOrdonne.setObjectName("WidgetPlusieursIntoOrdonne")
        WidgetPlusieursIntoOrdonne.resize(1013, 243)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetPlusieursIntoOrdonne.sizePolicy().hasHeightForWidth())
        WidgetPlusieursIntoOrdonne.setSizePolicy(sizePolicy)
        WidgetPlusieursIntoOrdonne.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(WidgetPlusieursIntoOrdonne)
        self.horizontalLayout_2.setContentsMargins(0, 2, 0, 7)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BFermeListe = QtWidgets.QToolButton(WidgetPlusieursIntoOrdonne)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BFermeListe.sizePolicy().hasHeightForWidth())
        self.BFermeListe.setSizePolicy(sizePolicy)
        self.BFermeListe.setMaximumSize(QtCore.QSize(21, 25))
        self.BFermeListe.setStyleSheet("border:0px")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Editeur/icons/minusnode.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BFermeListe.setIcon(icon)
        self.BFermeListe.setIconSize(QtCore.QSize(25, 25))
        self.BFermeListe.setObjectName("BFermeListe")
        self.horizontalLayout.addWidget(self.BFermeListe)
        self.RBValide = MonBoutonValide(WidgetPlusieursIntoOrdonne)
        self.RBValide.setMinimumSize(QtCore.QSize(21, 25))
        self.RBValide.setMaximumSize(QtCore.QSize(21, 25))
        self.RBValide.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBValide.setStyleSheet("border : 0px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Editeur/icons/ast-green-ball.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBValide.setIcon(icon1)
        self.RBValide.setIconSize(QtCore.QSize(25, 25))
        self.RBValide.setObjectName("RBValide")
        self.horizontalLayout.addWidget(self.RBValide)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = MonLabelClic(WidgetPlusieursIntoOrdonne)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(300, 25))
        self.label.setMaximumSize(QtCore.QSize(178, 16777215))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.scrollArea_2 = QtWidgets.QScrollArea(WidgetPlusieursIntoOrdonne)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 112, 172))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.monCommentaireLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monCommentaireLabel.sizePolicy().hasHeightForWidth())
        self.monCommentaireLabel.setSizePolicy(sizePolicy)
        self.monCommentaireLabel.setObjectName("monCommentaireLabel")
        self.verticalLayout_6.addWidget(self.monCommentaireLabel)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.scrollArea = QtWidgets.QScrollArea(WidgetPlusieursIntoOrdonne)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet("background : rgb(247,247,247)")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.scrollArea.setObjectName("scrollArea")
        self.verticalWidgetLE = QtWidgets.QWidget()
        self.verticalWidgetLE.setGeometry(QtCore.QRect(0, 0, 301, 232))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidgetLE.sizePolicy().hasHeightForWidth())
        self.verticalWidgetLE.setSizePolicy(sizePolicy)
        self.verticalWidgetLE.setObjectName("verticalWidgetLE")
        self.CBLayout = QtWidgets.QVBoxLayout(self.verticalWidgetLE)
        self.CBLayout.setContentsMargins(0, 0, 0, 0)
        self.CBLayout.setSpacing(0)
        self.CBLayout.setObjectName("CBLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.CBLayout.addItem(spacerItem2)
        self.scrollArea.setWidget(self.verticalWidgetLE)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        spacerItem3 = QtWidgets.QSpacerItem(8, 108, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollAreaRE = QtWidgets.QScrollArea(WidgetPlusieursIntoOrdonne)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaRE.sizePolicy().hasHeightForWidth())
        self.scrollAreaRE.setSizePolicy(sizePolicy)
        self.scrollAreaRE.setStyleSheet("background : rgb(247,247,247)")
        self.scrollAreaRE.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollAreaRE.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollAreaRE.setLineWidth(1)
        self.scrollAreaRE.setWidgetResizable(True)
        self.scrollAreaRE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.scrollAreaRE.setObjectName("scrollAreaRE")
        self.verticalWidgetLEChoisis = QtWidgets.QWidget()
        self.verticalWidgetLEChoisis.setGeometry(QtCore.QRect(0, 0, 297, 187))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidgetLEChoisis.sizePolicy().hasHeightForWidth())
        self.verticalWidgetLEChoisis.setSizePolicy(sizePolicy)
        self.verticalWidgetLEChoisis.setObjectName("verticalWidgetLEChoisis")
        self.CBChoisis = QtWidgets.QVBoxLayout(self.verticalWidgetLEChoisis)
        self.CBChoisis.setContentsMargins(0, 0, 0, 0)
        self.CBChoisis.setSpacing(0)
        self.CBChoisis.setObjectName("CBChoisis")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.CBChoisis.addItem(spacerItem4)
        self.scrollAreaRE.setWidget(self.verticalWidgetLEChoisis)
        self.verticalLayout_2.addWidget(self.scrollAreaRE)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.frame = QtWidgets.QFrame(WidgetPlusieursIntoOrdonne)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.RBHaut = QtWidgets.QToolButton(self.frame)
        self.RBHaut.setMinimumSize(QtCore.QSize(21, 31))
        self.RBHaut.setMaximumSize(QtCore.QSize(21, 31))
        self.RBHaut.setStyleSheet("border : 0px")
        icon = QtGui.QIcon.fromTheme("go-up")
        self.RBHaut.setIcon(icon)
        self.RBHaut.setIconSize(QtCore.QSize(32, 32))
        self.RBHaut.setObjectName("RBHaut")
        self.horizontalLayout_4.addWidget(self.RBHaut)
        self.RBBas = QtWidgets.QToolButton(self.frame)
        self.RBBas.setMinimumSize(QtCore.QSize(21, 31))
        self.RBBas.setMaximumSize(QtCore.QSize(21, 31))
        self.RBBas.setStyleSheet("border : 0px")
        icon = QtGui.QIcon.fromTheme("go-down")
        self.RBBas.setIcon(icon)
        self.RBBas.setIconSize(QtCore.QSize(32, 32))
        self.RBBas.setObjectName("RBBas")
        self.horizontalLayout_4.addWidget(self.RBBas)
        self.RBMoins = QtWidgets.QToolButton(self.frame)
        self.RBMoins.setMinimumSize(QtCore.QSize(21, 31))
        self.RBMoins.setMaximumSize(QtCore.QSize(21, 31))
        self.RBMoins.setStyleSheet("border : 0px")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Editeur/icons/MoinsBleu2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBMoins.setIcon(icon2)
        self.RBMoins.setIconSize(QtCore.QSize(32, 32))
        self.RBMoins.setObjectName("RBMoins")
        self.horizontalLayout_4.addWidget(self.RBMoins)
        self.RBPlus = QtWidgets.QToolButton(self.frame)
        self.RBPlus.setMinimumSize(QtCore.QSize(21, 31))
        self.RBPlus.setMaximumSize(QtCore.QSize(21, 31))
        self.RBPlus.setStyleSheet("border : 0px")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Editeur/icons/PlusBleu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBPlus.setIcon(icon3)
        self.RBPlus.setIconSize(QtCore.QSize(32, 32))
        self.RBPlus.setObjectName("RBPlus")
        self.horizontalLayout_4.addWidget(self.RBPlus)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.RBVoisListe = QtWidgets.QToolButton(self.frame)
        self.RBVoisListe.setMinimumSize(QtCore.QSize(21, 31))
        self.RBVoisListe.setMaximumSize(QtCore.QSize(21, 31))
        self.RBVoisListe.setStyleSheet("border : 0px")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Editeur/icons/verre-loupe-icone-6087-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBVoisListe.setIcon(icon4)
        self.RBVoisListe.setIconSize(QtCore.QSize(32, 32))
        self.RBVoisListe.setObjectName("RBVoisListe")
        self.horizontalLayout_3.addWidget(self.RBVoisListe)
        spacerItem6 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_5.addWidget(self.frame)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        spacerItem7 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.RBPoubelle = QtWidgets.QToolButton(WidgetPlusieursIntoOrdonne)
        self.RBPoubelle.setMinimumSize(QtCore.QSize(21, 31))
        self.RBPoubelle.setMaximumSize(QtCore.QSize(21, 31))
        self.RBPoubelle.setStyleSheet("border : 0px")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Editeur/icons/deleteRond.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBPoubelle.setIcon(icon5)
        self.RBPoubelle.setIconSize(QtCore.QSize(32, 32))
        self.RBPoubelle.setObjectName("RBPoubelle")
        self.verticalLayout.addWidget(self.RBPoubelle)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.scrollArea.raise_()

        self.retranslateUi(WidgetPlusieursIntoOrdonne)
        QtCore.QMetaObject.connectSlotsByName(WidgetPlusieursIntoOrdonne)

    def retranslateUi(self, WidgetPlusieursIntoOrdonne):
        _translate = QtCore.QCoreApplication.translate
        WidgetPlusieursIntoOrdonne.setWindowTitle(_translate("WidgetPlusieursIntoOrdonne", "Form"))
        self.BFermeListe.setToolTip(_translate("WidgetPlusieursIntoOrdonne", "permet de gérer la liste"))
        self.BFermeListe.setText(_translate("WidgetPlusieursIntoOrdonne", "..."))
        self.RBValide.setToolTip(_translate("WidgetPlusieursIntoOrdonne", "Affiche le rapport de validation du mot-clef"))
        self.RBValide.setText(_translate("WidgetPlusieursIntoOrdonne", "..."))
        self.label.setText(_translate("WidgetPlusieursIntoOrdonne", "<html><head/><body><p>aaa</p><p>dqsklmdqm</p></body></html>"))
        self.monCommentaireLabel.setText(_translate("WidgetPlusieursIntoOrdonne", "TextLabel"))
        self.RBHaut.setToolTip(_translate("WidgetPlusieursIntoOrdonne", "Remonte d\'une ligne"))
        self.RBHaut.setText(_translate("WidgetPlusieursIntoOrdonne", "..."))
        self.RBBas.setToolTip(_translate("WidgetPlusieursIntoOrdonne", "Descend d\'une ligne"))
        self.RBBas.setText(_translate("WidgetPlusieursIntoOrdonne", "..."))
        self.RBMoins.setToolTip(_translate("WidgetPlusieursIntoOrdonne", "Détruit une ligne"))
        self.RBMoins.setText(_translate("WidgetPlusieursIntoOrdonne", "..."))
        self.RBPlus.setToolTip(_translate("WidgetPlusieursIntoOrdonne", "ajoute une ligne"))
        self.RBPlus.setText(_translate("WidgetPlusieursIntoOrdonne", "..."))
        self.RBVoisListe.setToolTip(_translate("WidgetPlusieursIntoOrdonne", "visualise l\'ensemble des valeurs"))
        self.RBVoisListe.setText(_translate("WidgetPlusieursIntoOrdonne", "..."))
        self.RBPoubelle.setToolTip(_translate("WidgetPlusieursIntoOrdonne", "Détruit le mot-clef"))
        self.RBPoubelle.setText(_translate("WidgetPlusieursIntoOrdonne", "..."))

from monBoutonValide import MonBoutonValide
from monLabelClic import MonLabelClic

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetPlusieursIntoOrdonne = QtWidgets.QWidget()
    ui = Ui_WidgetPlusieursIntoOrdonne()
    ui.setupUi(WidgetPlusieursIntoOrdonne)
    WidgetPlusieursIntoOrdonne.show()
    sys.exit(app.exec_())

