# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desWidgetPlusieursTuple.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetPlusieursTuple(object):
    def setupUi(self, WidgetPlusieursTuple):
        WidgetPlusieursTuple.setObjectName("WidgetPlusieursTuple")
        WidgetPlusieursTuple.resize(612, 175)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetPlusieursTuple.sizePolicy().hasHeightForWidth())
        WidgetPlusieursTuple.setSizePolicy(sizePolicy)
        WidgetPlusieursTuple.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(WidgetPlusieursTuple)
        self.horizontalLayout_2.setContentsMargins(0, 2, 0, 2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(21, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.RBValide = MonBoutonValide(WidgetPlusieursTuple)
        self.RBValide.setMinimumSize(QtCore.QSize(21, 25))
        self.RBValide.setMaximumSize(QtCore.QSize(21, 25))
        self.RBValide.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBValide.setStyleSheet("border : 0px")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Editeur/icons/ast-green-ball.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBValide.setIcon(icon)
        self.RBValide.setIconSize(QtCore.QSize(25, 25))
        self.RBValide.setObjectName("RBValide")
        self.horizontalLayout.addWidget(self.RBValide)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = MonLabelClic(WidgetPlusieursTuple)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(300, 25))
        self.label.setMaximumSize(QtCore.QSize(178, 16777215))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.scrollArea_2 = QtWidgets.QScrollArea(WidgetPlusieursTuple)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 112, 109))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.monCommentaireLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monCommentaireLabel.sizePolicy().hasHeightForWidth())
        self.monCommentaireLabel.setSizePolicy(sizePolicy)
        self.monCommentaireLabel.setObjectName("monCommentaireLabel")
        self.verticalLayout_7.addWidget(self.monCommentaireLabel)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(WidgetPlusieursTuple)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet("background : rgb(247,247,247)")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.scrollArea.setObjectName("scrollArea")
        self.verticalWidgetLE = QtWidgets.QWidget()
        self.verticalWidgetLE.setGeometry(QtCore.QRect(0, 0, 197, 110))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidgetLE.sizePolicy().hasHeightForWidth())
        self.verticalWidgetLE.setSizePolicy(sizePolicy)
        self.verticalWidgetLE.setObjectName("verticalWidgetLE")
        self.verticalLayoutLE = QtWidgets.QVBoxLayout(self.verticalWidgetLE)
        self.verticalLayoutLE.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutLE.setSpacing(0)
        self.verticalLayoutLE.setObjectName("verticalLayoutLE")
        spacerItem2 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutLE.addItem(spacerItem2)
        self.scrollArea.setWidget(self.verticalWidgetLE)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout_4.addWidget(self.frame)
        self.frame1 = QtWidgets.QFrame(WidgetPlusieursTuple)
        self.frame1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame1.setObjectName("frame1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame1)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.RBHaut = QtWidgets.QToolButton(self.frame1)
        self.RBHaut.setMinimumSize(QtCore.QSize(21, 31))
        self.RBHaut.setMaximumSize(QtCore.QSize(21, 31))
        self.RBHaut.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBHaut.setStyleSheet("border : 0px")
        icon = QtGui.QIcon.fromTheme("go-up")
        self.RBHaut.setIcon(icon)
        self.RBHaut.setIconSize(QtCore.QSize(32, 32))
        self.RBHaut.setObjectName("RBHaut")
        self.horizontalLayout_5.addWidget(self.RBHaut)
        self.RBBas = QtWidgets.QToolButton(self.frame1)
        self.RBBas.setMinimumSize(QtCore.QSize(21, 31))
        self.RBBas.setMaximumSize(QtCore.QSize(21, 31))
        self.RBBas.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBBas.setStyleSheet("border : 0px")
        icon = QtGui.QIcon.fromTheme("go-down")
        self.RBBas.setIcon(icon)
        self.RBBas.setIconSize(QtCore.QSize(32, 32))
        self.RBBas.setObjectName("RBBas")
        self.horizontalLayout_5.addWidget(self.RBBas)
        self.RBMoins = QtWidgets.QToolButton(self.frame1)
        self.RBMoins.setMinimumSize(QtCore.QSize(21, 31))
        self.RBMoins.setMaximumSize(QtCore.QSize(21, 31))
        self.RBMoins.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBMoins.setStyleSheet("border : 0px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Editeur/icons/MoinsBleu2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.RBMoins.setIcon(icon1)
        self.RBMoins.setIconSize(QtCore.QSize(32, 32))
        self.RBMoins.setObjectName("RBMoins")
        self.horizontalLayout_5.addWidget(self.RBMoins)
        self.RBPlus = QtWidgets.QToolButton(self.frame1)
        self.RBPlus.setMinimumSize(QtCore.QSize(21, 31))
        self.RBPlus.setMaximumSize(QtCore.QSize(21, 31))
        self.RBPlus.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBPlus.setStyleSheet("border : 0px")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Editeur/icons/PlusBleu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBPlus.setIcon(icon2)
        self.RBPlus.setIconSize(QtCore.QSize(32, 32))
        self.RBPlus.setObjectName("RBPlus")
        self.horizontalLayout_5.addWidget(self.RBPlus)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.RBVoisListe = QtWidgets.QToolButton(self.frame1)
        self.RBVoisListe.setMinimumSize(QtCore.QSize(21, 31))
        self.RBVoisListe.setMaximumSize(QtCore.QSize(21, 31))
        self.RBVoisListe.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBVoisListe.setStyleSheet("border : 0px")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Editeur/icons/verre-loupe-icone-6087-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBVoisListe.setIcon(icon3)
        self.RBVoisListe.setIconSize(QtCore.QSize(32, 32))
        self.RBVoisListe.setObjectName("RBVoisListe")
        self.horizontalLayout_6.addWidget(self.RBVoisListe)
        self.verticalLayout_4.addWidget(self.frame1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BSelectFichier = QtWidgets.QToolButton(WidgetPlusieursTuple)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSelectFichier.sizePolicy().hasHeightForWidth())
        self.BSelectFichier.setSizePolicy(sizePolicy)
        self.BSelectFichier.setMaximumSize(QtCore.QSize(25, 30))
        self.BSelectFichier.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.BSelectFichier.setStyleSheet("border:0px")
        icon = QtGui.QIcon.fromTheme("text-x-generic")
        self.BSelectFichier.setIcon(icon)
        self.BSelectFichier.setIconSize(QtCore.QSize(32, 32))
        self.BSelectFichier.setObjectName("BSelectFichier")
        self.horizontalLayout_3.addWidget(self.BSelectFichier)
        spacerItem4 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.RBPoubelle = QtWidgets.QToolButton(WidgetPlusieursTuple)
        self.RBPoubelle.setMinimumSize(QtCore.QSize(21, 31))
        self.RBPoubelle.setMaximumSize(QtCore.QSize(21, 31))
        self.RBPoubelle.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RBPoubelle.setStyleSheet("border : 0px")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Editeur/icons/deleteRond.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RBPoubelle.setIcon(icon4)
        self.RBPoubelle.setIconSize(QtCore.QSize(32, 32))
        self.RBPoubelle.setObjectName("RBPoubelle")
        self.horizontalLayout_3.addWidget(self.RBPoubelle)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(WidgetPlusieursTuple)
        QtCore.QMetaObject.connectSlotsByName(WidgetPlusieursTuple)

    def retranslateUi(self, WidgetPlusieursTuple):
        _translate = QtCore.QCoreApplication.translate
        WidgetPlusieursTuple.setWindowTitle(_translate("WidgetPlusieursTuple", "Form"))
        self.RBValide.setToolTip(_translate("WidgetPlusieursTuple", "Affiche le rapport de validation du mot-clef"))
        self.RBValide.setText(_translate("WidgetPlusieursTuple", "..."))
        self.label.setText(_translate("WidgetPlusieursTuple", "<html><head/><body><p>aaa</p><p>dqsklmdqm</p></body></html>"))
        self.monCommentaireLabel.setText(_translate("WidgetPlusieursTuple", "TextLabel"))
        self.RBHaut.setToolTip(_translate("WidgetPlusieursTuple", "Remonte la ligne"))
        self.RBHaut.setText(_translate("WidgetPlusieursTuple", "..."))
        self.RBBas.setToolTip(_translate("WidgetPlusieursTuple", "Descend la ligne"))
        self.RBBas.setText(_translate("WidgetPlusieursTuple", "..."))
        self.RBMoins.setToolTip(_translate("WidgetPlusieursTuple", "supprime une ligne"))
        self.RBMoins.setText(_translate("WidgetPlusieursTuple", "..."))
        self.RBPlus.setToolTip(_translate("WidgetPlusieursTuple", "Ajoute une ligne"))
        self.RBPlus.setText(_translate("WidgetPlusieursTuple", "..."))
        self.RBVoisListe.setToolTip(_translate("WidgetPlusieursTuple", "Montre l\'ensemble des valeurs"))
        self.RBVoisListe.setText(_translate("WidgetPlusieursTuple", "..."))
        self.BSelectFichier.setToolTip(_translate("WidgetPlusieursTuple", "Ouvre un fichier de sélection des valeurs"))
        self.BSelectFichier.setText(_translate("WidgetPlusieursTuple", "..."))
        self.RBPoubelle.setToolTip(_translate("WidgetPlusieursTuple", "Détruit le mot-clef"))
        self.RBPoubelle.setText(_translate("WidgetPlusieursTuple", "..."))

from monBoutonValide import MonBoutonValide
from monLabelClic import MonLabelClic

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetPlusieursTuple = QtWidgets.QWidget()
    ui = Ui_WidgetPlusieursTuple()
    ui.setupUi(WidgetPlusieursTuple)
    WidgetPlusieursTuple.show()
    sys.exit(app.exec_())

