from Accas import *

JdC = JDC_CATA (code = 'MAP',
                execmodul = None,
                )
# ======================================================================
# Catalog entry for the MAP function : c_pre_interfaceBody_mesh
# ======================================================================
START=PROC(nom="START",op=None,
     Title = SIMP( statut='o',typ='TXM'),
     Working_Directory = SIMP( statut='o',typ='Repertoire',defaut='/tmp'),
     Dictionnary   = SIMP( statut='o', typ = ('Fichier', 'Dico (*.dico);;All Files (*)',),
              ),
     Geometry_File     = SIMP( statut='o', typ = ('Fichier', 'Geo Files (*.geo);;All Files (*)',),
              fr='Nom du fichier contenant le maillage du calcul a realiser.',
              ang='Name of the file containing the mesh. This file may also contain the topography and the friction coefficients.'
              ),
     Geometry_File_Format = SIMP( statut='f',typ='TXM',into=['MED','SERAFIN','SERAFIND'],sug='MED',
              ),
     Steering_File     = SIMP( statut='o', typ = ('Fichier', 'Steering Files (*.cas);;All Files (*)',),
              ),
     Fortran_File=SIMP(statut='f',typ = ('Fichier', 'Fortran files (*.f);;All Files (*)'),
                       fr='Nom du fichier a soumettre',
                       ang='Name of FORTRAN file to be submitted',),
     Boundary_Condition_File     = SIMP( statut='o', typ = ('Fichier', 'Boundary Condition (*.cli);;All Files (*)',),
              ),
     Reference_File     = SIMP( statut='f', typ = ('Fichier', 'Reference File (*.ref);;All Files (*)',),
              ),

     Formated_And_Binary_Files=FACT( statut='f',
          Formated_File1     = SIMP( statut='f', typ = ('Fichier', 'formated File (*.txt);;All Files (*)',),),
          Formated_File2     = SIMP( statut='f', typ = ('Fichier', 'formated File (*.txt);;All Files (*)',),),
          Binary_Data_File1  = SIMP( statut='f', typ = ('Fichier', 'Reference File (*.txt);;All Files (*)',),),
          Binary_Data_File2  = SIMP( statut='f', typ = ('Fichier', 'Reference File (*.txt);;All Files (*)',),),
     ),
     Computation_Continued=FACT( statut='f',
          Previous_Computation = SIMP( statut='o',typ='TXM',into=['SERALIN','SERAFIN'],sug='SERAFIN',),
          Initial_Time_Set     =SIMP(typ=bool, statut='f'),
          Computation_File   = SIMP( statut='o', typ = ('Fichier', 'Computation File (*.res);;All Files (*)',),),
     ),
)
# Ordre Catalogue START

GENERAL_PARAMETERS=PROC(nom="GENERAL_PARAMETERS",op=None,
     Time=FACT( statut='f',
       Original_Date_of_Time=FACT( statut='f',
         Jour=SIMP(statut='o',typ='I',val_min=1,val_max=31),
         Mois=SIMP(statut='o',typ='I',val_min=1,val_max=12),
         An=SIMP(statut='o',typ='I',val_min=1900),
          ),
       Original_Hour_of_Time=FACT( statut='f',
         Heure=SIMP(statut='o',typ='I',val_min=0,val_max=24,sug=0),
         Minute=SIMP(statut='o',typ='I',val_min=0,val_max=60,sug=0),
         Seconde=SIMP(statut='o',typ='I',val_min=0,val_max=60,sug=0),
         ),
      ),
     Location=FACT( statut='f',
       regles=( PRESENT_PRESENT('Longitude_of_origin','Latitute_of_origin', ),),
        Latitute_of_origin=SIMP(statut='f',typ='R',val_min=-90,val_max=90),
        Longitude_of_origin=SIMP(statut='f',typ='R'),
        Spatial_Projection=SIMP(statut='f',typ='I',into=[1,2,3]),
        Geographic_System=SIMP(statut='f',typ='I',into=[-1,0,1,2,3,4,5]),
        Zone_number_in_Geographic_System=SIMP(statut='f',typ='I',into=[-1,0,1,2,3,4,22,30]),
     ),
     Machine=FACT( statut='f',
        Number_of_Processors=SIMP(statut='f',typ='I',val_min=0),
        Parallel_Computation=SIMP(statut='f',typ=bool,),
     ),
     Coupling=FACT( statut='f',
        Sisyphe=SIMP(statut='f',typ=bool,sug=0),
        Tomawac=SIMP(statut='f',typ=bool,sug=0),
        Delwacq=SIMP(statut='f',typ=bool,sug=0),
     ),
)
# Ordre Catalogue GENERAL_PARAMETERS

INITIAL_CONDITIONS=PROC(nom="INITIAL_CONDITIONS",op=None,
        Initial_Conditions=SIMP(statut='f',typ='TXM',into=['ZERO ELEVATION', 'CONSTANT ELEVATION','ZERO DEPTH','CONSTANT DEPTH','SPECIAL','TPXO SATELLITE ALTIMETRY'],sug='ZERO ELEVATION',),
 
         b_initial_elevation     =BLOC(condition = "Initial_Conditions == 'CONSTANT ELEVATION'",
           Initial_Elevation       =SIMP(statut='o',typ='R' ),
         ),
         b_initial_depth     =BLOC(condition = "Initial_Conditions == 'CONSTANT DEPTH'",
           Initial_Depth       =SIMP(statut='o',typ='R' ),
         ),
        Initial_Guess_for_U=SIMP(statut='f',typ='TXM',into=['0=zero','1=previous','2=extrapolation'],sug='1=previous',),
        Initial_Guess_for_H=SIMP(statut='f',typ='TXM',into=['0=zero','1=previous','2=extrapolation'],sug='1=previous',),

    Boundary_Conditions=FACT(statut='f', 
       Liquid_Boundaries=FACT(statut='f',max='**',

            Prescibed_Flowrates=SIMP(statut='f',typ='R'),
            Prescibed_Elevations=SIMP(statut='f',typ='R'),
            Prescibed_Velocity=SIMP(statut='f',typ='R'),
            Options=SIMP(statut='f',typ='I',into=[1,2]),
       ),
       Stage_Discharge_Curves=SIMP(statut='f',typ='I',into=[0,1,2]),
       Stage_Discharge_Curves_File   = SIMP( statut='f', typ = ('Fichier', 'All Files (*)',),),
       Treatment_of_Fluxes_at_the_Boundaries   = SIMP( statut='f',typ='I',into=[1,2],sug=1),
       Option_for_tidal_Boundary_Conditions   = SIMP( statut='f',typ='I',into=[1,2],sug=1),
   ),
)
# Ordre Catalogue INITIAL_CONDITIONS

NUMERICAL_PARAMETERS=PROC(nom="NUMERICAL_PARAMETERS",op=None,
        Solver=FACT(statut='o',
          Equations=SIMP(statut='o',typ='TXM',into=['SAINT-VENANT EF','SAINT-VENANT VF','BOUSSINESQ'],sug='SAINT-VENANT EF'),
          Solver=SIMP(statut='o',typ='I',into=[1,2,3,4,6,7,8]),
          Solver_Accuracy=SIMP(statut='o',typ='R'),
          Maximum_Number_of_Iterations=SIMP(statut='o',typ='I'),
        ),
        Time=FACT(statut='f',
        regles=(AU_MOINS_UN('Number_of_time_Steps','Variable_Time_Step'),
                PRESENT_PRESENT('Time_Step','Duration',),),
           Number_of_Time_Steps=SIMP(statut='f',typ='I'),
           Time_Step=SIMP(statut='f',typ='R'),
           Duration=SIMP(statut='f',typ='R'),
           Variable_Time_Step=SIMP(statut='f',typ=bool),
        ),
        Linearity=FACT(statut='f',
           Treatment_of_Fluxes_at_the_Boundaries =SIMP( statut='f',typ='I',into=[1,2],sug=1),
           Continuity_Correction  =SIMP(typ=bool, statut='f'),
           Number_of_Sub_Iterations=SIMP(statut='f',typ='I'),
        ),
        Precondionning=FACT(statut='f',
          Preconditionning=SIMP(statut='f',typ='I',into=[0,2,3,7,11,14,21],sug=2),
          C_U_Preconditionning  =SIMP(typ=bool, statut='f',),
          Matrix_Vector_Product =SIMP(statut='f',typ='I',into=[1,2]),
          Matrix_Storage =SIMP(statut='f',typ='I',into=[1,3]),
          Mass_Lumping_on_H =SIMP(statut='f',typ='R',sug=0),
          Mass_Lumping_on_Velocity =SIMP(statut='f',typ='R',sug=0),
        ),
        Advection_Propagation=FACT(statut='f',
          Type_of_Advection=SIMP(statut='f',typ='I',min=4,max=4,into=[1,2,3,4,5,6,7,13,14],defaut=(1,5,1,1),),
          Advection_of_U_and_V=SIMP(statut='f',typ=bool),
          Advection_of_H=SIMP(statut='f',typ=bool),
          Advection_of_Tracers=SIMP(statut='f',typ=bool),
          Advection_of_K_and_Epsilon=SIMP(statut='f',typ=bool),

         b_upwind     =BLOC(condition = "2 in Type_of_Advection",
            Upwind_Coefficients=SIMP(statut='o',typ='R',min=4,max=4,)
           ),
          Linearized_Propoagation=SIMP(statut='f',typ=bool,sug=False),
          Mean_Depth_For_Linearity=SIMP(statut='f',typ='R',sug=0.0),
        ),
        Discretisation_Implicitation=FACT(statut='f',
          Discretisation_in_Space=SIMP(statut='f',typ='I',min=4,max=4,into=[11,12,13],defaut=(11,11,11),),
          Implicitation_for_Diffusion_of_velocity=SIMP(statut='f',typ='R',sug=0),
          Implicitation_for_Depth=SIMP(statut='f',typ='R',sug=0.55),
          Implicitation_for_Velocity=SIMP(statut='f',typ='R',sug=0.55),
          Free_Surface_Gradient_Compatibility=SIMP(statut='f',typ='R',sug=1.),
        ),
)
# Ordre Catalogue NUMERICAL_PARAMETERS

PHYSICAL_PARAMETERS=PROC(nom="PHYSICAL_PARAMETERS",op=None,
        Atmosphere=FACT(statut='f',
          Wind=SIMP(statut='f',typ=bool,sug=False),
          b_Wind     =BLOC(condition = "Wind=='True'",
            regles=( PRESENT_PRESENT('Wind_Velocity_along_X','Wind_Velocity_along_Y', ),),
            Coefficient_of_Wind_Influence=SIMP(statut='f',typ='R',sug=0,),
            Wind_Velocity_along_X=SIMP(statut='f',typ='R',sug=0,),
            Wind_Velocity_along_Y=SIMP(statut='f',typ='R',sug=0,),
            Threashold_Depth_for_Wind=SIMP(statut='f',typ='R',sug=0,),
            Air_Pressure=SIMP(statut='f',typ=bool,sug=False),
         ),
          Rain_or_Evaporation=SIMP(statut='f',typ=bool,sug=False),
          b_Rain     =BLOC(condition = "Rain_or_Evaporation=='True'",
            Rain_or_Evaporation_in_mm_perday=SIMP(statut='f',typ='I',sug=0),
                         ),
         ),
          Tide_Generating_Force=SIMP(statut='f',typ=bool,sug=False),
          b_Tide     =BLOC(condition = "Tide_Generating_Force=='True'",
              Tidal_Data_Base=SIMP(statut='f',typ='I',into=[-1,1,2,3,4]),
              Coefficient_To_Calibrate_Tidal_Range=SIMP(statut='f',typ='R',sug=1.),
              Coefficient_To_Calibrate_Tidal_Velocity=SIMP(statut='f',typ='R',sug=999999),
              Coefficient_To_Calibrate_Sea_Level=SIMP(statut='f',typ='R',sug=0.),
              Binary_Database_1_for_Tide  = SIMP( statut='f', typ = ('Fichier', '(All Files (*)',),),
              Binary_Database_2_for_Tide  = SIMP( statut='f', typ = ('Fichier', '(All Files (*)',),),
         ),
          Wave_Driver_Currents=SIMP(statut='f',typ=bool,sug=False),
          b_Wave     =BLOC(condition = "Wave_Driver_Currents=='True'",
              Record_Number_in_Wave_File=SIMP(statut='f',typ='I',sug=1),
         ),
)

# Ordre Catalogue PHYSICAL_PARAMETERS
