# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desCommande.ui'
#
# Created: Tue Sep 23 10:19:58 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DComm(object):
    def setupUi(self, DComm):
        DComm.setObjectName("DComm")
        DComm.resize(505,483)
        DComm.setMinimumSize(QtCore.QSize(505,0))
        self.gridlayout = QtGui.QGridLayout(DComm)
        self.gridlayout.setObjectName("gridlayout")
        self.Commentaire = QtGui.QLabel(DComm)
        self.Commentaire.setFrameShape(QtGui.QFrame.NoFrame)
        self.Commentaire.setFrameShadow(QtGui.QFrame.Plain)
        self.Commentaire.setWordWrap(False)
        self.Commentaire.setObjectName("Commentaire")
        self.gridlayout.addWidget(self.Commentaire,1,0,1,3)
        self.bOk = QtGui.QPushButton(DComm)
        self.bOk.setMinimumSize(QtCore.QSize(0,30))
        self.bOk.setAutoDefault(True)
        self.bOk.setDefault(True)
        self.bOk.setObjectName("bOk")
        self.gridlayout.addWidget(self.bOk,2,1,1,1)
        self.bSup = QtGui.QPushButton(DComm)
        self.bSup.setMinimumSize(QtCore.QSize(0,30))
        self.bSup.setAutoDefault(True)
        self.bSup.setObjectName("bSup")
        self.gridlayout.addWidget(self.bSup,2,0,1,1)
        self.bHelp = QtGui.QPushButton(DComm)
        self.bHelp.setMinimumSize(QtCore.QSize(0,30))
        self.bHelp.setAutoDefault(True)
        self.bHelp.setObjectName("bHelp")
        self.gridlayout.addWidget(self.bHelp,2,2,1,1)
        self.TWChoix = QtGui.QTabWidget(DComm)
        self.TWChoix.setObjectName("TWChoix")
        self.MotClef = QtGui.QWidget()
        self.MotClef.setGeometry(QtCore.QRect(0,0,483,372))
        self.MotClef.setObjectName("MotClef")
        self.gridLayout_3 = QtGui.QGridLayout(self.MotClef)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textLabel1 = QtGui.QLabel(self.MotClef)
        self.textLabel1.setMinimumSize(QtCore.QSize(0,0))
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.gridLayout_3.addWidget(self.textLabel1,0,0,1,1)
        self.textLabel1_2 = QtGui.QLabel(self.MotClef)
        self.textLabel1_2.setWordWrap(False)
        self.textLabel1_2.setObjectName("textLabel1_2")
        self.gridLayout_3.addWidget(self.textLabel1_2,0,1,1,1)
        self.LBMCPermis = QtGui.QListWidget(self.MotClef)
        self.LBMCPermis.setObjectName("LBMCPermis")
        self.gridLayout_3.addWidget(self.LBMCPermis,1,0,1,1)
        self.LBRegles = QtGui.QListWidget(self.MotClef)
        self.LBRegles.setObjectName("LBRegles")
        self.gridLayout_3.addWidget(self.LBRegles,1,1,1,1)
        self.TWChoix.addTab(self.MotClef,"")
        self.Concept = QtGui.QWidget()
        self.Concept.setGeometry(QtCore.QRect(0,0,483,372))
        self.Concept.setObjectName("Concept")
        self.gridlayout1 = QtGui.QGridLayout(self.Concept)
        self.gridlayout1.setObjectName("gridlayout1")
        self.groupBox1 = QtGui.QGroupBox(self.Concept)
        self.groupBox1.setObjectName("groupBox1")
        self.textLabel1_3 = QtGui.QLabel(self.groupBox1)
        self.textLabel1_3.setGeometry(QtCore.QRect(80,50,130,31))
        self.textLabel1_3.setWordWrap(False)
        self.textLabel1_3.setObjectName("textLabel1_3")
        self.textLabel1_3_2 = QtGui.QLabel(self.groupBox1)
        self.textLabel1_3_2.setGeometry(QtCore.QRect(80,170,150,31))
        self.textLabel1_3_2.setWordWrap(False)
        self.textLabel1_3_2.setObjectName("textLabel1_3_2")
        self.LENomConcept = QtGui.QLineEdit(self.groupBox1)
        self.LENomConcept.setGeometry(QtCore.QRect(80,110,310,30))
        self.LENomConcept.setObjectName("LENomConcept")
        self.textLabel3 = QtGui.QLabel(self.groupBox1)
        self.textLabel3.setGeometry(QtCore.QRect(10,200,290,31))
        self.textLabel3.setWordWrap(False)
        self.textLabel3.setObjectName("textLabel3")
        self.typeConcept = QtGui.QLabel(self.groupBox1)
        self.typeConcept.setGeometry(QtCore.QRect(310,200,130,31))
        self.typeConcept.setWordWrap(False)
        self.typeConcept.setObjectName("typeConcept")
        self.gridlayout1.addWidget(self.groupBox1,0,0,1,1)
        self.TWChoix.addTab(self.Concept,"")
        self.Commande = QtGui.QWidget()
        self.Commande.setGeometry(QtCore.QRect(0,0,483,372))
        self.Commande.setObjectName("Commande")
        self.gridLayout_2 = QtGui.QGridLayout(self.Commande)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textLabel1_4 = QtGui.QLabel(self.Commande)
        self.textLabel1_4.setWordWrap(False)
        self.textLabel1_4.setObjectName("textLabel1_4")
        self.gridLayout_2.addWidget(self.textLabel1_4,0,0,1,1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textLabel6 = QtGui.QLabel(self.Commande)
        self.textLabel6.setMinimumSize(QtCore.QSize(50,30))
        self.textLabel6.setWordWrap(False)
        self.textLabel6.setObjectName("textLabel6")
        self.horizontalLayout.addWidget(self.textLabel6)
        self.LEFiltre = QtGui.QLineEdit(self.Commande)
        self.LEFiltre.setMinimumSize(QtCore.QSize(160,30))
        self.LEFiltre.setObjectName("LEFiltre")
        self.horizontalLayout.addWidget(self.LEFiltre)
        self.BNext = QtGui.QPushButton(self.Commande)
        self.BNext.setObjectName("BNext")
        self.horizontalLayout.addWidget(self.BNext)
        self.gridLayout_2.addLayout(self.horizontalLayout,1,0,1,1)
        self.groupBox = QtGui.QGroupBox(self.Commande)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.RBalpha = QtGui.QRadioButton(self.groupBox)
        self.RBalpha.setChecked(True)
        self.RBalpha.setObjectName("RBalpha")
        self.gridLayout.addWidget(self.RBalpha,0,0,1,1)
        self.RBGroupe = QtGui.QRadioButton(self.groupBox)
        self.RBGroupe.setObjectName("RBGroupe")
        self.gridLayout.addWidget(self.RBGroupe,1,0,1,1)
        self.gridLayout_2.addWidget(self.groupBox,0,1,2,1)
        self.LBNouvCommande = QtGui.QListWidget(self.Commande)
        self.LBNouvCommande.setObjectName("LBNouvCommande")
        self.gridLayout_2.addWidget(self.LBNouvCommande,2,0,1,2)
        self.textLabel4 = QtGui.QLabel(self.Commande)
        self.textLabel4.setWordWrap(False)
        self.textLabel4.setObjectName("textLabel4")
        self.gridLayout_2.addWidget(self.textLabel4,3,0,1,2)
        self.TWChoix.addTab(self.Commande,"")
        self.gridlayout.addWidget(self.TWChoix,0,0,1,3)

        self.retranslateUi(DComm)
        self.TWChoix.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DComm)
        DComm.setTabOrder(self.LEFiltre,self.LENomConcept)
        DComm.setTabOrder(self.LENomConcept,self.TWChoix)
        DComm.setTabOrder(self.TWChoix,self.LBNouvCommande)
        DComm.setTabOrder(self.LBNouvCommande,self.bOk)
        DComm.setTabOrder(self.bOk,self.bSup)
        DComm.setTabOrder(self.bSup,self.bHelp)

    def retranslateUi(self, DComm):
        DComm.setWindowTitle(QtGui.QApplication.translate("DComm", "DComm", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setToolTip(QtGui.QApplication.translate("DComm", "validation de la saisie", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setText(QtGui.QApplication.translate("DComm", "&Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setShortcut(QtGui.QApplication.translate("DComm", "Shift+A, Alt+A, Alt+A, Alt+A", None, QtGui.QApplication.UnicodeUTF8))
        self.bSup.setToolTip(QtGui.QApplication.translate("DComm", "suppression du mot clef", None, QtGui.QApplication.UnicodeUTF8))
        self.bSup.setText(QtGui.QApplication.translate("DComm", "&Supprimer", None, QtGui.QApplication.UnicodeUTF8))
        self.bSup.setShortcut(QtGui.QApplication.translate("DComm", "Alt+S", None, QtGui.QApplication.UnicodeUTF8))
        self.bHelp.setToolTip(QtGui.QApplication.translate("DComm", "affichage documentation aster", None, QtGui.QApplication.UnicodeUTF8))
        self.bHelp.setText(QtGui.QApplication.translate("DComm", "&Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.bHelp.setShortcut(QtGui.QApplication.translate("DComm", "Alt+D", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1.setText(QtGui.QApplication.translate("DComm", "<h3><p align=\"center\"><u><b>Mots Clefs Permis</b></u></p></h3>", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_2.setText(QtGui.QApplication.translate("DComm", "<h3><p align=\"center\"><u><b>Règles</b></u></p></h3>", None, QtGui.QApplication.UnicodeUTF8))
        self.TWChoix.setTabText(self.TWChoix.indexOf(self.MotClef), QtGui.QApplication.translate("DComm", "Ajouter Mot-Clef", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox1.setTitle(QtGui.QApplication.translate("DComm", "Concept", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_3.setText(QtGui.QApplication.translate("DComm", "<u>Nom du concept :</u>", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_3_2.setText(QtGui.QApplication.translate("DComm", "<u>Type du concept :</u>", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel3.setText(QtGui.QApplication.translate("DComm", "L\'opérateur retourne un concept de type :", None, QtGui.QApplication.UnicodeUTF8))
        self.typeConcept.setText(QtGui.QApplication.translate("DComm", "TypeDuConcept", None, QtGui.QApplication.UnicodeUTF8))
        self.TWChoix.setTabText(self.TWChoix.indexOf(self.Concept), QtGui.QApplication.translate("DComm", "Nommer Concept", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_4.setText(QtGui.QApplication.translate("DComm", "<b><u>Commandes :</u></b>", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel6.setText(QtGui.QApplication.translate("DComm", "Filtre", None, QtGui.QApplication.UnicodeUTF8))
        self.BNext.setText(QtGui.QApplication.translate("DComm", "Suivant", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DComm", "Affichage", None, QtGui.QApplication.UnicodeUTF8))
        self.RBalpha.setText(QtGui.QApplication.translate("DComm", "alphabétique", None, QtGui.QApplication.UnicodeUTF8))
        self.RBGroupe.setText(QtGui.QApplication.translate("DComm", "par groupe", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4.setText(QtGui.QApplication.translate("DComm", "La commande choisie sera ajoutée APRES la commande courante", None, QtGui.QApplication.UnicodeUTF8))
        self.TWChoix.setTabText(self.TWChoix.indexOf(self.Commande), QtGui.QApplication.translate("DComm", "Nouvelle Commande", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DComm = QtGui.QWidget()
    ui = Ui_DComm()
    ui.setupUi(DComm)
    DComm.show()
    sys.exit(app.exec_())

