# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desCommentaire.ui'
#
# Created: Fri Apr 24 12:05:46 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DComment(object):
    def setupUi(self, DComment):
        DComment.setObjectName("DComment")
        DComment.resize(796, 618)
        DComment.setMinimumSize(QtCore.QSize(505, 0))
        self.gridLayout_3 = QtGui.QGridLayout(DComment)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.TWChoix = QtGui.QTabWidget(DComment)
        self.TWChoix.setObjectName("TWChoix")
        self.Valeur_Parametre = QtGui.QWidget()
        self.Valeur_Parametre.setObjectName("Valeur_Parametre")
        self.gridLayout = QtGui.QGridLayout(self.Valeur_Parametre)
        self.gridLayout.setObjectName("gridLayout")
        self.textCommentaire = QtGui.QTextEdit(self.Valeur_Parametre)
        self.textCommentaire.setObjectName("textCommentaire")
        self.gridLayout.addWidget(self.textCommentaire, 0, 0, 1, 1)
        self.TWChoix.addTab(self.Valeur_Parametre, "")
        self.Commande = QtGui.QWidget()
        self.Commande.setObjectName("Commande")
        self.gridLayout_4 = QtGui.QGridLayout(self.Commande)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textLabel1_4 = QtGui.QLabel(self.Commande)
        self.textLabel1_4.setWordWrap(False)
        self.textLabel1_4.setObjectName("textLabel1_4")
        self.gridLayout_2.addWidget(self.textLabel1_4, 0, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(self.Commande)
        self.groupBox.setMinimumSize(QtCore.QSize(171, 71))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout1 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout1.setObjectName("gridLayout1")
        self.RBalpha = QtGui.QRadioButton(self.groupBox)
        self.RBalpha.setMinimumSize(QtCore.QSize(149, 16))
        self.RBalpha.setMaximumSize(QtCore.QSize(149, 16))
        self.RBalpha.setChecked(True)
        self.RBalpha.setObjectName("RBalpha")
        self.gridLayout1.addWidget(self.RBalpha, 0, 0, 1, 1)
        self.RBGroupe = QtGui.QRadioButton(self.groupBox)
        self.RBGroupe.setObjectName("RBGroupe")
        self.gridLayout1.addWidget(self.RBGroupe, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 4, 2, 1)
        self.textLabel6 = QtGui.QLabel(self.Commande)
        self.textLabel6.setMinimumSize(QtCore.QSize(91, 30))
        self.textLabel6.setWordWrap(False)
        self.textLabel6.setObjectName("textLabel6")
        self.gridLayout_2.addWidget(self.textLabel6, 1, 0, 1, 1)
        self.LEFiltre = QtGui.QLineEdit(self.Commande)
        self.LEFiltre.setMinimumSize(QtCore.QSize(231, 30))
        self.LEFiltre.setObjectName("LEFiltre")
        self.gridLayout_2.addWidget(self.LEFiltre, 1, 1, 1, 1)
        self.BNext = QtGui.QPushButton(self.Commande)
        self.BNext.setMinimumSize(QtCore.QSize(90, 30))
        self.BNext.setObjectName("BNext")
        self.gridLayout_2.addWidget(self.BNext, 1, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(108, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.LBNouvCommande = QtGui.QListWidget(self.Commande)
        self.LBNouvCommande.setObjectName("LBNouvCommande")
        self.gridLayout_4.addWidget(self.LBNouvCommande, 1, 0, 1, 1)
        self.textLabel4 = QtGui.QLabel(self.Commande)
        self.textLabel4.setMaximumSize(QtCore.QSize(721, 20))
        self.textLabel4.setWordWrap(False)
        self.textLabel4.setObjectName("textLabel4")
        self.gridLayout_4.addWidget(self.textLabel4, 2, 0, 1, 1)
        self.TWChoix.addTab(self.Commande, "")
        self.gridLayout_3.addWidget(self.TWChoix, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtGui.QSpacerItem(268, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.bOk = QtGui.QPushButton(DComment)
        self.bOk.setMinimumSize(QtCore.QSize(160, 30))
        self.bOk.setMaximumSize(QtCore.QSize(160, 30))
        self.bOk.setAutoDefault(True)
        self.bOk.setDefault(True)
        self.bOk.setObjectName("bOk")
        self.horizontalLayout.addWidget(self.bOk)
        spacerItem2 = QtGui.QSpacerItem(328, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(DComment)
        self.TWChoix.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DComment)
        DComment.setTabOrder(self.TWChoix, self.bOk)

    def retranslateUi(self, DComment):
        DComment.setWindowTitle(QtGui.QApplication.translate("DComment", "DComm", None, QtGui.QApplication.UnicodeUTF8))
        self.TWChoix.setTabText(self.TWChoix.indexOf(self.Valeur_Parametre), QtGui.QApplication.translate("DComment", "Commentaire", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_4.setText(QtGui.QApplication.translate("DComment", "<b><u>Commandes :</u></b>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DComment", "Affichage", None, QtGui.QApplication.UnicodeUTF8))
        self.RBalpha.setText(QtGui.QApplication.translate("DComment", "alphabétique", None, QtGui.QApplication.UnicodeUTF8))
        self.RBGroupe.setText(QtGui.QApplication.translate("DComment", "par groupe", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel6.setText(QtGui.QApplication.translate("DComment", "Filtre", None, QtGui.QApplication.UnicodeUTF8))
        self.BNext.setText(QtGui.QApplication.translate("DComment", "Suivant", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4.setText(QtGui.QApplication.translate("DComment", "La commande choisie sera ajoutée APRES la commande courante", None, QtGui.QApplication.UnicodeUTF8))
        self.TWChoix.setTabText(self.TWChoix.indexOf(self.Commande), QtGui.QApplication.translate("DComment", "Nouvelle Commande", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setToolTip(QtGui.QApplication.translate("DComment", "validation de la saisie", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setText(QtGui.QApplication.translate("DComment", "&Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setShortcut(QtGui.QApplication.translate("DComment", "Shift+A, Alt+A, Alt+A, Alt+A", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DComment = QtGui.QWidget()
    ui = Ui_DComment()
    ui.setupUi(DComment)
    DComment.show()
    sys.exit(app.exec_())

