# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desCommentaire.ui'
#
# Created: Wed Jul 23 12:00:45 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DComment(object):
    def setupUi(self, DComment):
        DComment.setObjectName("DComment")
        DComment.resize(505,482)
        DComment.setMinimumSize(QtCore.QSize(505,0))
        self.gridlayout = QtGui.QGridLayout(DComment)
        self.gridlayout.setObjectName("gridlayout")
        self.bOk = QtGui.QPushButton(DComment)
        self.bOk.setMinimumSize(QtCore.QSize(0,30))
        self.bOk.setAutoDefault(True)
        self.bOk.setDefault(True)
        self.bOk.setObjectName("bOk")
        self.gridlayout.addWidget(self.bOk,2,1,1,1)
        self.bSup = QtGui.QPushButton(DComment)
        self.bSup.setMinimumSize(QtCore.QSize(0,30))
        self.bSup.setAutoDefault(True)
        self.bSup.setObjectName("bSup")
        self.gridlayout.addWidget(self.bSup,2,0,1,1)
        self.bHelp = QtGui.QPushButton(DComment)
        self.bHelp.setMinimumSize(QtCore.QSize(0,30))
        self.bHelp.setAutoDefault(True)
        self.bHelp.setObjectName("bHelp")
        self.gridlayout.addWidget(self.bHelp,2,2,1,1)
        self.Commentaire = QtGui.QLabel(DComment)
        self.Commentaire.setFrameShape(QtGui.QFrame.NoFrame)
        self.Commentaire.setFrameShadow(QtGui.QFrame.Plain)
        self.Commentaire.setWordWrap(False)
        self.Commentaire.setObjectName("Commentaire")
        self.gridlayout.addWidget(self.Commentaire,1,0,1,3)
        self.TWChoix = QtGui.QTabWidget(DComment)
        self.TWChoix.setObjectName("TWChoix")
        self.Valeur_Parametre = QtGui.QWidget()
        self.Valeur_Parametre.setGeometry(QtCore.QRect(0,0,483,371))
        self.Valeur_Parametre.setObjectName("Valeur_Parametre")
        self.gridLayout = QtGui.QGridLayout(self.Valeur_Parametre)
        self.gridLayout.setObjectName("gridLayout")
        self.textCommentaire = QtGui.QTextEdit(self.Valeur_Parametre)
        self.textCommentaire.setObjectName("textCommentaire")
        self.gridLayout.addWidget(self.textCommentaire,0,0,1,1)
        self.TWChoix.addTab(self.Valeur_Parametre,"")
        self.Commande = QtGui.QWidget()
        self.Commande.setGeometry(QtCore.QRect(0,0,483,371))
        self.Commande.setObjectName("Commande")
        self.gridLayout_4 = QtGui.QGridLayout(self.Commande)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textLabel1_4 = QtGui.QLabel(self.Commande)
        self.textLabel1_4.setWordWrap(False)
        self.textLabel1_4.setObjectName("textLabel1_4")
        self.gridLayout_4.addWidget(self.textLabel1_4,0,0,1,3)
        self.groupBox = QtGui.QGroupBox(self.Commande)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.RBalpha = QtGui.QRadioButton(self.groupBox)
        self.RBalpha.setChecked(True)
        self.RBalpha.setObjectName("RBalpha")
        self.gridLayout_3.addWidget(self.RBalpha,0,0,1,1)
        self.RBGroupe = QtGui.QRadioButton(self.groupBox)
        self.RBGroupe.setObjectName("RBGroupe")
        self.gridLayout_3.addWidget(self.RBGroupe,1,0,1,1)
        self.gridLayout_4.addWidget(self.groupBox,0,3,2,1)
        self.textLabel6_2 = QtGui.QLabel(self.Commande)
        self.textLabel6_2.setMinimumSize(QtCore.QSize(50,30))
        self.textLabel6_2.setWordWrap(False)
        self.textLabel6_2.setObjectName("textLabel6_2")
        self.gridLayout_4.addWidget(self.textLabel6_2,1,0,1,1)
        self.LEFiltre = QtGui.QLineEdit(self.Commande)
        self.LEFiltre.setMinimumSize(QtCore.QSize(160,30))
        self.LEFiltre.setObjectName("LEFiltre")
        self.gridLayout_4.addWidget(self.LEFiltre,1,1,1,1)
        self.BNext = QtGui.QPushButton(self.Commande)
        self.BNext.setObjectName("BNext")
        self.gridLayout_4.addWidget(self.BNext,1,2,1,1)
        self.LBNouvCommande = QtGui.QListWidget(self.Commande)
        self.LBNouvCommande.setObjectName("LBNouvCommande")
        self.gridLayout_4.addWidget(self.LBNouvCommande,2,0,1,4)
        self.textLabel4 = QtGui.QLabel(self.Commande)
        self.textLabel4.setWordWrap(False)
        self.textLabel4.setObjectName("textLabel4")
        self.gridLayout_4.addWidget(self.textLabel4,3,0,1,4)
        self.TWChoix.addTab(self.Commande,"")
        self.gridlayout.addWidget(self.TWChoix,0,0,1,3)

        self.retranslateUi(DComment)
        self.TWChoix.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DComment)
        DComment.setTabOrder(self.TWChoix,self.bOk)
        DComment.setTabOrder(self.bOk,self.bSup)
        DComment.setTabOrder(self.bSup,self.bHelp)

    def retranslateUi(self, DComment):
        DComment.setWindowTitle(QtGui.QApplication.translate("DComment", "DComm", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setToolTip(QtGui.QApplication.translate("DComment", "validation de la saisie", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setText(QtGui.QApplication.translate("DComment", "&Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setShortcut(QtGui.QApplication.translate("DComment", "Shift+A, Alt+A, Alt+A, Alt+A", None, QtGui.QApplication.UnicodeUTF8))
        self.bSup.setToolTip(QtGui.QApplication.translate("DComment", "suppression du mot clef", None, QtGui.QApplication.UnicodeUTF8))
        self.bSup.setText(QtGui.QApplication.translate("DComment", "&Supprimer", None, QtGui.QApplication.UnicodeUTF8))
        self.bSup.setShortcut(QtGui.QApplication.translate("DComment", "Alt+S", None, QtGui.QApplication.UnicodeUTF8))
        self.bHelp.setToolTip(QtGui.QApplication.translate("DComment", "affichage documentation aster", None, QtGui.QApplication.UnicodeUTF8))
        self.bHelp.setText(QtGui.QApplication.translate("DComment", "&Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.bHelp.setShortcut(QtGui.QApplication.translate("DComment", "Alt+D", None, QtGui.QApplication.UnicodeUTF8))
        self.TWChoix.setTabText(self.TWChoix.indexOf(self.Valeur_Parametre), QtGui.QApplication.translate("DComment", "Commentaire", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_4.setText(QtGui.QApplication.translate("DComment", "<b><u>Commandes :</u></b>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DComment", "Affichage", None, QtGui.QApplication.UnicodeUTF8))
        self.RBalpha.setText(QtGui.QApplication.translate("DComment", "alphabétique", None, QtGui.QApplication.UnicodeUTF8))
        self.RBGroupe.setText(QtGui.QApplication.translate("DComment", "par groupe", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel6_2.setText(QtGui.QApplication.translate("DComment", "Filtre", None, QtGui.QApplication.UnicodeUTF8))
        self.BNext.setText(QtGui.QApplication.translate("DComment", "Suivant", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4.setText(QtGui.QApplication.translate("DComment", "La commande choisie sera ajoutée APRES la commande courante", None, QtGui.QApplication.UnicodeUTF8))
        self.TWChoix.setTabText(self.TWChoix.indexOf(self.Commande), QtGui.QApplication.translate("DComment", "Nouvelle Commande", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DComment = QtGui.QWidget()
    ui = Ui_DComment()
    ui.setupUi(DComment)
    DComment.show()
    sys.exit(app.exec_())

