# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desCommande.ui'
#
# Created: Fri Sep 17 16:46:35 2010
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DComm(object):
    def setupUi(self, DComm):
        DComm.setObjectName("DComm")
        DComm.resize(792,770)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DComm.sizePolicy().hasHeightForWidth())
        DComm.setSizePolicy(sizePolicy)
        DComm.setMinimumSize(QtCore.QSize(505,0))
        self.gridLayout_11 = QtGui.QGridLayout(DComm)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.TWChoix = QtGui.QTabWidget(DComm)
        self.TWChoix.setObjectName("TWChoix")
        self.MotClef = QtGui.QWidget()
        self.MotClef.setObjectName("MotClef")
        self.gridLayout_6 = QtGui.QGridLayout(self.MotClef)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.textLabel1 = QtGui.QLabel(self.MotClef)
        self.textLabel1.setMinimumSize(QtCore.QSize(0,0))
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.gridLayout_5.addWidget(self.textLabel1,0,0,1,1)
        self.textLabel1_2 = QtGui.QLabel(self.MotClef)
        self.textLabel1_2.setWordWrap(False)
        self.textLabel1_2.setObjectName("textLabel1_2")
        self.gridLayout_5.addWidget(self.textLabel1_2,0,1,1,1)
        self.LBMCPermis = QtGui.QListWidget(self.MotClef)
        self.LBMCPermis.setObjectName("LBMCPermis")
        self.gridLayout_5.addWidget(self.LBMCPermis,1,0,1,1)
        self.LBRegles = QtGui.QListWidget(self.MotClef)
        self.LBRegles.setObjectName("LBRegles")
        self.gridLayout_5.addWidget(self.LBRegles,1,1,1,1)
        self.gridLayout_6.addLayout(self.gridLayout_5,0,0,1,1)
        self.TWChoix.addTab(self.MotClef,"")
        self.Concept = QtGui.QWidget()
        self.Concept.setObjectName("Concept")
        self.gridLayout_9 = QtGui.QGridLayout(self.Concept)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox1 = QtGui.QGroupBox(self.Concept)
        self.groupBox1.setObjectName("groupBox1")
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Label1 = QtGui.QLabel(self.groupBox1)
        self.Label1.setWordWrap(False)
        self.Label1.setObjectName("Label1")
        self.gridLayout_3.addWidget(self.Label1,0,0,1,2)
        self.LENomConcept = QtGui.QLineEdit(self.groupBox1)
        self.LENomConcept.setMinimumSize(QtCore.QSize(360,40))
        self.LENomConcept.setObjectName("LENomConcept")
        self.gridLayout_3.addWidget(self.LENomConcept,1,0,1,1)
        spacerItem = QtGui.QSpacerItem(356,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem,1,1,1,1)
        self.gridLayout_10.addLayout(self.gridLayout_3,0,0,1,1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.listBoxASSD = QtGui.QListWidget(self.groupBox1)
        self.listBoxASSD.setObjectName("listBoxASSD")
        self.gridLayout_8.addWidget(self.listBoxASSD,0,0,1,1)
        spacerItem1 = QtGui.QSpacerItem(20,168,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem1,1,0,1,1)
        self.gridLayout_10.addLayout(self.gridLayout_8,1,0,1,1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.Label2 = QtGui.QLabel(self.groupBox1)
        self.Label2.setWordWrap(False)
        self.Label2.setObjectName("Label2")
        self.gridLayout_7.addWidget(self.Label2,0,0,1,1)
        self.Label3 = QtGui.QLabel(self.groupBox1)
        self.Label3.setWordWrap(False)
        self.Label3.setObjectName("Label3")
        self.gridLayout_7.addWidget(self.Label3,1,0,1,1)
        self.typeConcept = QtGui.QLabel(self.groupBox1)
        self.typeConcept.setWordWrap(False)
        self.typeConcept.setObjectName("typeConcept")
        self.gridLayout_7.addWidget(self.typeConcept,1,1,1,1)
        self.gridLayout_10.addLayout(self.gridLayout_7,2,0,1,1)
        self.gridLayout_9.addWidget(self.groupBox1,0,0,1,1)
        self.TWChoix.addTab(self.Concept,"")
        self.Commande = QtGui.QWidget()
        self.Commande.setObjectName("Commande")
        self.gridLayout_4 = QtGui.QGridLayout(self.Commande)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textLabel1_4 = QtGui.QLabel(self.Commande)
        self.textLabel1_4.setWordWrap(False)
        self.textLabel1_4.setObjectName("textLabel1_4")
        self.gridLayout_2.addWidget(self.textLabel1_4,0,0,1,2)
        self.groupBox = QtGui.QGroupBox(self.Commande)
        self.groupBox.setMinimumSize(QtCore.QSize(171,71))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.RBalpha = QtGui.QRadioButton(self.groupBox)
        self.RBalpha.setMinimumSize(QtCore.QSize(149,16))
        self.RBalpha.setMaximumSize(QtCore.QSize(149,16))
        self.RBalpha.setChecked(True)
        self.RBalpha.setObjectName("RBalpha")
        self.gridLayout.addWidget(self.RBalpha,0,0,1,1)
        self.RBGroupe = QtGui.QRadioButton(self.groupBox)
        self.RBGroupe.setObjectName("RBGroupe")
        self.gridLayout.addWidget(self.RBGroupe,1,0,1,1)
        self.gridLayout_2.addWidget(self.groupBox,0,4,2,1)
        self.textLabel6 = QtGui.QLabel(self.Commande)
        self.textLabel6.setMinimumSize(QtCore.QSize(91,30))
        self.textLabel6.setWordWrap(False)
        self.textLabel6.setObjectName("textLabel6")
        self.gridLayout_2.addWidget(self.textLabel6,1,0,1,1)
        self.LEFiltre = QtGui.QLineEdit(self.Commande)
        self.LEFiltre.setMinimumSize(QtCore.QSize(231,30))
        self.LEFiltre.setObjectName("LEFiltre")
        self.gridLayout_2.addWidget(self.LEFiltre,1,1,1,1)
        self.BNext = QtGui.QPushButton(self.Commande)
        self.BNext.setMinimumSize(QtCore.QSize(90,30))
        self.BNext.setObjectName("BNext")
        self.gridLayout_2.addWidget(self.BNext,1,2,1,1)
        spacerItem2 = QtGui.QSpacerItem(108,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2,1,3,1,1)
        self.gridLayout_4.addLayout(self.gridLayout_2,0,0,1,1)
        self.LBNouvCommande = QtGui.QListWidget(self.Commande)
        self.LBNouvCommande.setObjectName("LBNouvCommande")
        self.gridLayout_4.addWidget(self.LBNouvCommande,1,0,1,1)
        self.textLabel4 = QtGui.QLabel(self.Commande)
        self.textLabel4.setMaximumSize(QtCore.QSize(721,20))
        self.textLabel4.setWordWrap(False)
        self.textLabel4.setObjectName("textLabel4")
        self.gridLayout_4.addWidget(self.textLabel4,2,0,1,1)
        self.TWChoix.addTab(self.Commande,"")
        self.gridLayout_11.addWidget(self.TWChoix,0,0,1,1)
        self.Commentaire = QtGui.QLabel(DComm)
        self.Commentaire.setMaximumSize(QtCore.QSize(793,20))
        self.Commentaire.setFrameShape(QtGui.QFrame.NoFrame)
        self.Commentaire.setFrameShadow(QtGui.QFrame.Plain)
        self.Commentaire.setWordWrap(False)
        self.Commentaire.setObjectName("Commentaire")
        self.gridLayout_11.addWidget(self.Commentaire,1,0,1,1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtGui.QSpacerItem(263,27,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.bOk = QtGui.QPushButton(DComm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bOk.sizePolicy().hasHeightForWidth())
        self.bOk.setSizePolicy(sizePolicy)
        self.bOk.setMinimumSize(QtCore.QSize(160,30))
        self.bOk.setMaximumSize(QtCore.QSize(16777215,30))
        self.bOk.setAutoDefault(True)
        self.bOk.setDefault(True)
        self.bOk.setObjectName("bOk")
        self.horizontalLayout.addWidget(self.bOk)
        spacerItem4 = QtGui.QSpacerItem(254,27,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.gridLayout_11.addLayout(self.horizontalLayout,2,0,1,1)

        self.retranslateUi(DComm)
        self.TWChoix.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DComm)
        DComm.setTabOrder(self.TWChoix,self.LBNouvCommande)
        DComm.setTabOrder(self.LBNouvCommande,self.bOk)

    def retranslateUi(self, DComm):
        DComm.setWindowTitle(QtGui.QApplication.translate("DComm", "DComm", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1.setText(QtGui.QApplication.translate("DComm", "<h3><p align=\"center\"><u><b>Mots Clefs Permis</b></u></p></h3>", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_2.setText(QtGui.QApplication.translate("DComm", "<h3><p align=\"center\"><u><b>Règles</b></u></p></h3>", None, QtGui.QApplication.UnicodeUTF8))
        self.TWChoix.setTabText(self.TWChoix.indexOf(self.MotClef), QtGui.QApplication.translate("DComm", "Ajouter Mot-Clef", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox1.setTitle(QtGui.QApplication.translate("DComm", "Concept", None, QtGui.QApplication.UnicodeUTF8))
        self.Label1.setText(QtGui.QApplication.translate("DComm", "<u>Nom du concept :</u>", None, QtGui.QApplication.UnicodeUTF8))
        self.Label2.setText(QtGui.QApplication.translate("DComm", "<u>Type du concept :</u>", None, QtGui.QApplication.UnicodeUTF8))
        self.Label3.setText(QtGui.QApplication.translate("DComm", "L\'opérateur retourne un concept de type :", None, QtGui.QApplication.UnicodeUTF8))
        self.typeConcept.setText(QtGui.QApplication.translate("DComm", "TypeDuConcept", None, QtGui.QApplication.UnicodeUTF8))
        self.TWChoix.setTabText(self.TWChoix.indexOf(self.Concept), QtGui.QApplication.translate("DComm", "Nommer Concept", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_4.setText(QtGui.QApplication.translate("DComm", "<b><u>Commandes :</u></b>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DComm", "Affichage", None, QtGui.QApplication.UnicodeUTF8))
        self.RBalpha.setText(QtGui.QApplication.translate("DComm", "alphabétique", None, QtGui.QApplication.UnicodeUTF8))
        self.RBGroupe.setText(QtGui.QApplication.translate("DComm", "par groupe", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel6.setText(QtGui.QApplication.translate("DComm", "Filtre", None, QtGui.QApplication.UnicodeUTF8))
        self.BNext.setText(QtGui.QApplication.translate("DComm", "Suivant", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4.setText(QtGui.QApplication.translate("DComm", "La commande choisie sera ajoutée APRES la commande courante", None, QtGui.QApplication.UnicodeUTF8))
        self.TWChoix.setTabText(self.TWChoix.indexOf(self.Commande), QtGui.QApplication.translate("DComm", "Nouvelle Commande", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setToolTip(QtGui.QApplication.translate("DComm", "validation de la saisie", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setText(QtGui.QApplication.translate("DComm", "&Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setShortcut(QtGui.QApplication.translate("DComm", "Shift+A, Alt+A, Alt+A, Alt+A", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DComm = QtGui.QWidget()
    ui = Ui_DComm()
    ui.setupUi(DComm)
    DComm.show()
    sys.exit(app.exec_())

