# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desParam.ui'
#
# Created: Tue Nov 18 17:37:24 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DParam(object):
    def setupUi(self, DParam):
        DParam.setObjectName("DParam")
        DParam.resize(505,483)
        DParam.setMinimumSize(QtCore.QSize(505,0))
        self.gridlayout = QtGui.QGridLayout(DParam)
        self.gridlayout.setObjectName("gridlayout")
        self.Commentaire = QtGui.QLabel(DParam)
        self.Commentaire.setFrameShape(QtGui.QFrame.NoFrame)
        self.Commentaire.setFrameShadow(QtGui.QFrame.Plain)
        self.Commentaire.setWordWrap(False)
        self.Commentaire.setObjectName("Commentaire")
        self.gridlayout.addWidget(self.Commentaire,1,0,1,3)
        self.TWChoix = QtGui.QTabWidget(DParam)
        self.TWChoix.setObjectName("TWChoix")
        self.Valeur_Parametre = QtGui.QWidget()
        self.Valeur_Parametre.setGeometry(QtCore.QRect(0,0,483,372))
        self.Valeur_Parametre.setObjectName("Valeur_Parametre")
        self.gridLayout_3 = QtGui.QGridLayout(self.Valeur_Parametre)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textLabel2_2_2 = QtGui.QLabel(self.Valeur_Parametre)
        self.textLabel2_2_2.setWordWrap(False)
        self.textLabel2_2_2.setObjectName("textLabel2_2_2")
        self.gridLayout_3.addWidget(self.textLabel2_2_2,0,1,1,1)
        self.textLabel2_2 = QtGui.QLabel(self.Valeur_Parametre)
        self.textLabel2_2.setWordWrap(False)
        self.textLabel2_2.setObjectName("textLabel2_2")
        self.gridLayout_3.addWidget(self.textLabel2_2,1,0,1,1)
        self.lineEditNom = QtGui.QLineEdit(self.Valeur_Parametre)
        self.lineEditNom.setMinimumSize(QtCore.QSize(231,31))
        self.lineEditNom.setObjectName("lineEditNom")
        self.gridLayout_3.addWidget(self.lineEditNom,1,1,1,1)
        self.textLabel2 = QtGui.QLabel(self.Valeur_Parametre)
        self.textLabel2.setWordWrap(False)
        self.textLabel2.setObjectName("textLabel2")
        self.gridLayout_3.addWidget(self.textLabel2,2,0,1,1)
        self.lineEditVal = QtGui.QLineEdit(self.Valeur_Parametre)
        self.lineEditVal.setMinimumSize(QtCore.QSize(231,31))
        self.lineEditVal.setObjectName("lineEditVal")
        self.gridLayout_3.addWidget(self.lineEditVal,2,1,1,1)
        self.Commentaire2 = QtGui.QLabel(self.Valeur_Parametre)
        self.Commentaire2.setWordWrap(False)
        self.Commentaire2.setObjectName("Commentaire2")
        self.gridLayout_3.addWidget(self.Commentaire2,3,0,1,2)
        self.Commentaire_2 = QtGui.QLabel(self.Valeur_Parametre)
        self.Commentaire_2.setWordWrap(False)
        self.Commentaire_2.setObjectName("Commentaire_2")
        self.gridLayout_3.addWidget(self.Commentaire_2,4,0,1,2)
        self.TWChoix.addTab(self.Valeur_Parametre,"")
        self.Commande = QtGui.QWidget()
        self.Commande.setGeometry(QtCore.QRect(0,0,483,372))
        self.Commande.setObjectName("Commande")
        self.gridLayout_2 = QtGui.QGridLayout(self.Commande)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textLabel1_4 = QtGui.QLabel(self.Commande)
        self.textLabel1_4.setWordWrap(False)
        self.textLabel1_4.setObjectName("textLabel1_4")
        self.gridLayout_2.addWidget(self.textLabel1_4,0,0,1,3)
        self.groupBox = QtGui.QGroupBox(self.Commande)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.RBGroupe = QtGui.QRadioButton(self.groupBox)
        self.RBGroupe.setObjectName("RBGroupe")
        self.gridLayout.addWidget(self.RBGroupe,1,0,1,1)
        self.RBalpha = QtGui.QRadioButton(self.groupBox)
        self.RBalpha.setChecked(True)
        self.RBalpha.setObjectName("RBalpha")
        self.gridLayout.addWidget(self.RBalpha,0,0,1,1)
        self.gridLayout_2.addWidget(self.groupBox,0,3,2,1)
        self.textLabel6 = QtGui.QLabel(self.Commande)
        self.textLabel6.setMinimumSize(QtCore.QSize(50,30))
        self.textLabel6.setWordWrap(False)
        self.textLabel6.setObjectName("textLabel6")
        self.gridLayout_2.addWidget(self.textLabel6,1,0,1,1)
        self.LEFiltre = QtGui.QLineEdit(self.Commande)
        self.LEFiltre.setMinimumSize(QtCore.QSize(160,30))
        self.LEFiltre.setObjectName("LEFiltre")
        self.gridLayout_2.addWidget(self.LEFiltre,1,1,1,1)
        self.BNext = QtGui.QPushButton(self.Commande)
        self.BNext.setObjectName("BNext")
        self.gridLayout_2.addWidget(self.BNext,1,2,1,1)
        self.LBNouvCommande = QtGui.QListWidget(self.Commande)
        self.LBNouvCommande.setObjectName("LBNouvCommande")
        self.gridLayout_2.addWidget(self.LBNouvCommande,2,0,1,4)
        self.textLabel4 = QtGui.QLabel(self.Commande)
        self.textLabel4.setWordWrap(False)
        self.textLabel4.setObjectName("textLabel4")
        self.gridLayout_2.addWidget(self.textLabel4,3,0,1,4)
        self.TWChoix.addTab(self.Commande,"")
        self.gridlayout.addWidget(self.TWChoix,0,0,1,3)
        self.bOk = QtGui.QPushButton(DParam)
        self.bOk.setMinimumSize(QtCore.QSize(0,30))
        self.bOk.setAutoDefault(True)
        self.bOk.setDefault(True)
        self.bOk.setObjectName("bOk")
        self.gridlayout.addWidget(self.bOk,2,1,1,1)
        self.bSup = QtGui.QPushButton(DParam)
        self.bSup.setMinimumSize(QtCore.QSize(0,30))
        self.bSup.setAutoDefault(True)
        self.bSup.setObjectName("bSup")
        self.gridlayout.addWidget(self.bSup,2,0,1,1)
        self.bHelp = QtGui.QPushButton(DParam)
        self.bHelp.setMinimumSize(QtCore.QSize(0,30))
        self.bHelp.setAutoDefault(True)
        self.bHelp.setObjectName("bHelp")
        self.gridlayout.addWidget(self.bHelp,2,2,1,1)

        self.retranslateUi(DParam)
        self.TWChoix.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DParam)
        DParam.setTabOrder(self.LEFiltre,self.TWChoix)
        DParam.setTabOrder(self.TWChoix,self.lineEditNom)
        DParam.setTabOrder(self.lineEditNom,self.lineEditVal)
        DParam.setTabOrder(self.lineEditVal,self.LBNouvCommande)
        DParam.setTabOrder(self.LBNouvCommande,self.RBalpha)
        DParam.setTabOrder(self.RBalpha,self.bOk)
        DParam.setTabOrder(self.bOk,self.bSup)
        DParam.setTabOrder(self.bSup,self.bHelp)

    def retranslateUi(self, DParam):
        DParam.setWindowTitle(QtGui.QApplication.translate("DParam", "DComm", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2_2_2.setText(QtGui.QApplication.translate("DParam", "<u><b><p align=\"center\">Parametre</p></b></u>", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2_2.setText(QtGui.QApplication.translate("DParam", "<b> Nom: </b>", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2.setText(QtGui.QApplication.translate("DParam", "<b> Valeur: </b>", None, QtGui.QApplication.UnicodeUTF8))
        self.Commentaire2.setText(QtGui.QApplication.translate("DParam", "Retour Chariot dans une sone de saisie permet de vérifier la \n"
"validité de la valeur saisie.\n"
"\n"
"Les nouvelles valeurs ne seront prises  en compte qu\'après avoir \n"
"appuyé sur  le bouton Valider.", None, QtGui.QApplication.UnicodeUTF8))
        self.TWChoix.setTabText(self.TWChoix.indexOf(self.Valeur_Parametre), QtGui.QApplication.translate("DParam", "Valeur Parametre", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_4.setText(QtGui.QApplication.translate("DParam", "<b><u>Commandes :</u></b>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DParam", "Affichage", None, QtGui.QApplication.UnicodeUTF8))
        self.RBGroupe.setText(QtGui.QApplication.translate("DParam", "par groupe", None, QtGui.QApplication.UnicodeUTF8))
        self.RBalpha.setText(QtGui.QApplication.translate("DParam", "alphabétique", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel6.setText(QtGui.QApplication.translate("DParam", "Filtre", None, QtGui.QApplication.UnicodeUTF8))
        self.BNext.setText(QtGui.QApplication.translate("DParam", "Suivant", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4.setText(QtGui.QApplication.translate("DParam", "La commande choisie sera ajoutée APRES la commande courante", None, QtGui.QApplication.UnicodeUTF8))
        self.TWChoix.setTabText(self.TWChoix.indexOf(self.Commande), QtGui.QApplication.translate("DParam", "Nouvelle Commande", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setToolTip(QtGui.QApplication.translate("DParam", "validation de la saisie", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setText(QtGui.QApplication.translate("DParam", "&Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setShortcut(QtGui.QApplication.translate("DParam", "Shift+A, Alt+A, Alt+A, Alt+A", None, QtGui.QApplication.UnicodeUTF8))
        self.bSup.setToolTip(QtGui.QApplication.translate("DParam", "suppression du mot clef", None, QtGui.QApplication.UnicodeUTF8))
        self.bSup.setText(QtGui.QApplication.translate("DParam", "&Supprimer", None, QtGui.QApplication.UnicodeUTF8))
        self.bSup.setShortcut(QtGui.QApplication.translate("DParam", "Alt+S", None, QtGui.QApplication.UnicodeUTF8))
        self.bHelp.setToolTip(QtGui.QApplication.translate("DParam", "affichage documentation aster", None, QtGui.QApplication.UnicodeUTF8))
        self.bHelp.setText(QtGui.QApplication.translate("DParam", "&Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.bHelp.setShortcut(QtGui.QApplication.translate("DParam", "Alt+D", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DParam = QtGui.QWidget()
    ui = Ui_DParam()
    ui.setupUi(DParam)
    DParam.show()
    sys.exit(app.exec_())

