# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desParam.ui'
#
# Created: Fri Apr 24 10:10:36 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DParam(object):
    def setupUi(self, DParam):
        DParam.setObjectName("DParam")
        DParam.resize(682, 552)
        DParam.setMinimumSize(QtCore.QSize(505, 0))
        self.gridLayout_3 = QtGui.QGridLayout(DParam)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.TWChoix = QtGui.QTabWidget(DParam)
        self.TWChoix.setObjectName("TWChoix")
        self.Valeur_Parametre = QtGui.QWidget()
        self.Valeur_Parametre.setObjectName("Valeur_Parametre")
        self.gridLayout_5 = QtGui.QGridLayout(self.Valeur_Parametre)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.textLabel2_2_2 = QtGui.QLabel(self.Valeur_Parametre)
        self.textLabel2_2_2.setWordWrap(False)
        self.textLabel2_2_2.setObjectName("textLabel2_2_2")
        self.gridLayout_5.addWidget(self.textLabel2_2_2, 0, 0, 1, 2)
        self.textLabel2_2 = QtGui.QLabel(self.Valeur_Parametre)
        self.textLabel2_2.setWordWrap(False)
        self.textLabel2_2.setObjectName("textLabel2_2")
        self.gridLayout_5.addWidget(self.textLabel2_2, 1, 0, 1, 1)
        self.lineEditNom = QtGui.QLineEdit(self.Valeur_Parametre)
        self.lineEditNom.setMinimumSize(QtCore.QSize(231, 31))
        self.lineEditNom.setObjectName("lineEditNom")
        self.gridLayout_5.addWidget(self.lineEditNom, 1, 1, 1, 1)
        self.textLabel2 = QtGui.QLabel(self.Valeur_Parametre)
        self.textLabel2.setWordWrap(False)
        self.textLabel2.setObjectName("textLabel2")
        self.gridLayout_5.addWidget(self.textLabel2, 2, 0, 1, 1)
        self.lineEditVal = QtGui.QLineEdit(self.Valeur_Parametre)
        self.lineEditVal.setMinimumSize(QtCore.QSize(231, 31))
        self.lineEditVal.setObjectName("lineEditVal")
        self.gridLayout_5.addWidget(self.lineEditVal, 2, 1, 1, 1)
        self.Commentaire2 = QtGui.QLabel(self.Valeur_Parametre)
        self.Commentaire2.setWordWrap(False)
        self.Commentaire2.setObjectName("Commentaire2")
        self.gridLayout_5.addWidget(self.Commentaire2, 3, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(460, 139, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 4, 0, 1, 2)
        self.Commentaire = QtGui.QLabel(self.Valeur_Parametre)
        self.Commentaire.setMinimumSize(QtCore.QSize(0, 20))
        self.Commentaire.setMaximumSize(QtCore.QSize(465, 16777215))
        self.Commentaire.setObjectName("Commentaire")
        self.gridLayout_5.addWidget(self.Commentaire, 5, 0, 1, 2)
        self.Commentaire_2 = QtGui.QLabel(self.Valeur_Parametre)
        self.Commentaire_2.setWordWrap(False)
        self.Commentaire_2.setObjectName("Commentaire_2")
        self.gridLayout_5.addWidget(self.Commentaire_2, 6, 0, 1, 2)
        self.TWChoix.addTab(self.Valeur_Parametre, "")
        self.Commande = QtGui.QWidget()
        self.Commande.setObjectName("Commande")
        self.gridLayout_4 = QtGui.QGridLayout(self.Commande)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textLabel1_4 = QtGui.QLabel(self.Commande)
        self.textLabel1_4.setWordWrap(False)
        self.textLabel1_4.setObjectName("textLabel1_4")
        self.gridLayout_2.addWidget(self.textLabel1_4, 0, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(self.Commande)
        self.groupBox.setMinimumSize(QtCore.QSize(171, 71))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.RBalpha = QtGui.QRadioButton(self.groupBox)
        self.RBalpha.setMinimumSize(QtCore.QSize(149, 16))
        self.RBalpha.setMaximumSize(QtCore.QSize(149, 16))
        self.RBalpha.setChecked(True)
        self.RBalpha.setObjectName("RBalpha")
        self.gridLayout.addWidget(self.RBalpha, 0, 0, 1, 1)
        self.RBGroupe = QtGui.QRadioButton(self.groupBox)
        self.RBGroupe.setObjectName("RBGroupe")
        self.gridLayout.addWidget(self.RBGroupe, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 4, 2, 1)
        self.textLabel6 = QtGui.QLabel(self.Commande)
        self.textLabel6.setMinimumSize(QtCore.QSize(91, 30))
        self.textLabel6.setWordWrap(False)
        self.textLabel6.setObjectName("textLabel6")
        self.gridLayout_2.addWidget(self.textLabel6, 1, 0, 1, 1)
        self.LEFiltre = QtGui.QLineEdit(self.Commande)
        self.LEFiltre.setMinimumSize(QtCore.QSize(231, 30))
        self.LEFiltre.setObjectName("LEFiltre")
        self.gridLayout_2.addWidget(self.LEFiltre, 1, 1, 1, 1)
        self.BNext = QtGui.QPushButton(self.Commande)
        self.BNext.setMinimumSize(QtCore.QSize(90, 30))
        self.BNext.setObjectName("BNext")
        self.gridLayout_2.addWidget(self.BNext, 1, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(108, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.LBNouvCommande = QtGui.QListWidget(self.Commande)
        self.LBNouvCommande.setObjectName("LBNouvCommande")
        self.gridLayout_4.addWidget(self.LBNouvCommande, 1, 0, 1, 1)
        self.textLabel4 = QtGui.QLabel(self.Commande)
        self.textLabel4.setMaximumSize(QtCore.QSize(721, 20))
        self.textLabel4.setWordWrap(False)
        self.textLabel4.setObjectName("textLabel4")
        self.gridLayout_4.addWidget(self.textLabel4, 2, 0, 1, 1)
        self.TWChoix.addTab(self.Commande, "")
        self.gridLayout_3.addWidget(self.TWChoix, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtGui.QSpacerItem(158, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.bOk = QtGui.QPushButton(DParam)
        self.bOk.setMinimumSize(QtCore.QSize(160, 30))
        self.bOk.setMaximumSize(QtCore.QSize(160, 30))
        self.bOk.setAutoDefault(True)
        self.bOk.setDefault(True)
        self.bOk.setObjectName("bOk")
        self.horizontalLayout.addWidget(self.bOk)
        spacerItem3 = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(DParam)
        self.TWChoix.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DParam)
        DParam.setTabOrder(self.LEFiltre, self.TWChoix)
        DParam.setTabOrder(self.TWChoix, self.lineEditNom)
        DParam.setTabOrder(self.lineEditNom, self.lineEditVal)
        DParam.setTabOrder(self.lineEditVal, self.LBNouvCommande)
        DParam.setTabOrder(self.LBNouvCommande, self.RBalpha)
        DParam.setTabOrder(self.RBalpha, self.bOk)

    def retranslateUi(self, DParam):
        DParam.setWindowTitle(QtGui.QApplication.translate("DParam", "DComm", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2_2_2.setText(QtGui.QApplication.translate("DParam", "<u><b><p align=\"center\">Parametre</p></b></u>", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2_2.setText(QtGui.QApplication.translate("DParam", "<b> Nom: </b>", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2.setText(QtGui.QApplication.translate("DParam", "<b> Valeur: </b>", None, QtGui.QApplication.UnicodeUTF8))
        self.Commentaire2.setText(QtGui.QApplication.translate("DParam", "Retour Chariot dans une sone de saisie permet de vérifier la \n"
"validité de la valeur saisie.\n"
"\n"
"Les nouvelles valeurs ne seront prises  en compte qu\'après avoir \n"
"appuyé sur  le bouton Valider.", None, QtGui.QApplication.UnicodeUTF8))
        self.TWChoix.setTabText(self.TWChoix.indexOf(self.Valeur_Parametre), QtGui.QApplication.translate("DParam", "Valeur Parametre", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_4.setText(QtGui.QApplication.translate("DParam", "<b><u>Commandes :</u></b>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DParam", "Affichage", None, QtGui.QApplication.UnicodeUTF8))
        self.RBalpha.setText(QtGui.QApplication.translate("DParam", "alphabétique", None, QtGui.QApplication.UnicodeUTF8))
        self.RBGroupe.setText(QtGui.QApplication.translate("DParam", "par groupe", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel6.setText(QtGui.QApplication.translate("DParam", "Filtre", None, QtGui.QApplication.UnicodeUTF8))
        self.BNext.setText(QtGui.QApplication.translate("DParam", "Suivant", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4.setText(QtGui.QApplication.translate("DParam", "La commande choisie sera ajoutée APRES la commande courante", None, QtGui.QApplication.UnicodeUTF8))
        self.TWChoix.setTabText(self.TWChoix.indexOf(self.Commande), QtGui.QApplication.translate("DParam", "Nouvelle Commande", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setToolTip(QtGui.QApplication.translate("DParam", "validation de la saisie", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setText(QtGui.QApplication.translate("DParam", "&Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setShortcut(QtGui.QApplication.translate("DParam", "Shift+A, Alt+A, Alt+A, Alt+A", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DParam = QtGui.QWidget()
    ui = Ui_DParam()
    ui.setupUi(DParam)
    DParam.show()
    sys.exit(app.exec_())

