# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desPlusieursBase.ui'
#
# Created: Fri Apr 24 15:50:34 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DPlusBase(object):
    def setupUi(self, DPlusBase):
        DPlusBase.setObjectName("DPlusBase")
        DPlusBase.resize(643, 728)
        DPlusBase.setMinimumSize(QtCore.QSize(350, 0))
        self.gridLayout_4 = QtGui.QGridLayout(DPlusBase)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabuniqueinto = QtGui.QTabWidget(DPlusBase)
        self.tabuniqueinto.setObjectName("tabuniqueinto")
        self.Widget8 = QtGui.QWidget()
        self.Widget8.setObjectName("Widget8")
        self.gridLayout_2 = QtGui.QGridLayout(self.Widget8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textLabel1 = QtGui.QLabel(self.Widget8)
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.verticalLayout_2.addWidget(self.textLabel1)
        self.LBValeurs = QtGui.QListWidget(self.Widget8)
        self.LBValeurs.setMinimumSize(QtCore.QSize(200, 0))
        self.LBValeurs.setObjectName("LBValeurs")
        self.verticalLayout_2.addWidget(self.LBValeurs)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textLabel1_2 = QtGui.QLabel(self.Widget8)
        self.textLabel1_2.setMinimumSize(QtCore.QSize(61, 21))
        self.textLabel1_2.setMaximumSize(QtCore.QSize(61, 21))
        self.textLabel1_2.setWordWrap(False)
        self.textLabel1_2.setObjectName("textLabel1_2")
        self.horizontalLayout.addWidget(self.textLabel1_2)
        spacerItem = QtGui.QSpacerItem(168, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        self.BAjout1Val = QtGui.QToolButton(self.Widget8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BAjout1Val.sizePolicy().hasHeightForWidth())
        self.BAjout1Val.setSizePolicy(sizePolicy)
        self.BAjout1Val.setMinimumSize(QtCore.QSize(40, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Editeur/icons/arrow_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BAjout1Val.setIcon(icon)
        self.BAjout1Val.setObjectName("BAjout1Val")
        self.gridLayout.addWidget(self.BAjout1Val, 1, 0, 1, 1)
        self.LEValeur = QtGui.QLineEdit(self.Widget8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEValeur.sizePolicy().hasHeightForWidth())
        self.LEValeur.setSizePolicy(sizePolicy)
        self.LEValeur.setMinimumSize(QtCore.QSize(220, 30))
        self.LEValeur.setObjectName("LEValeur")
        self.gridLayout.addWidget(self.LEValeur, 1, 1, 1, 2)
        self.BSup1Val = QtGui.QToolButton(self.Widget8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSup1Val.sizePolicy().hasHeightForWidth())
        self.BSup1Val.setSizePolicy(sizePolicy)
        self.BSup1Val.setMinimumSize(QtCore.QSize(40, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../EficasV1/Editeur/icons/arrow_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BSup1Val.setIcon(icon1)
        self.BSup1Val.setObjectName("BSup1Val")
        self.gridLayout.addWidget(self.BSup1Val, 2, 0, 1, 1)
        self.BSalome = QtGui.QToolButton(self.Widget8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSalome.sizePolicy().hasHeightForWidth())
        self.BSalome.setSizePolicy(sizePolicy)
        self.BSalome.setMinimumSize(QtCore.QSize(40, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("image240.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BSalome.setIcon(icon2)
        self.BSalome.setObjectName("BSalome")
        self.gridLayout.addWidget(self.BSalome, 2, 1, 1, 1)
        self.BView2D = QtGui.QPushButton(self.Widget8)
        self.BView2D.setMinimumSize(QtCore.QSize(120, 30))
        self.BView2D.setObjectName("BView2D")
        self.gridLayout.addWidget(self.BView2D, 2, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 158, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtGui.QSpacerItem(150, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.bParam = QtGui.QPushButton(self.Widget8)
        self.bParam.setMinimumSize(QtCore.QSize(100, 30))
        self.bParam.setMaximumSize(QtCore.QSize(100, 30))
        self.bParam.setAutoDefault(True)
        self.bParam.setObjectName("bParam")
        self.verticalLayout.addWidget(self.bParam)
        self.bImport = QtGui.QPushButton(self.Widget8)
        self.bImport.setMinimumSize(QtCore.QSize(100, 30))
        self.bImport.setMaximumSize(QtCore.QSize(100, 30))
        self.bImport.setAutoDefault(True)
        self.bImport.setObjectName("bImport")
        self.verticalLayout.addWidget(self.bImport)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem3 = QtGui.QSpacerItem(265, 48, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.Commentaire = QtGui.QLabel(self.Widget8)
        self.Commentaire.setMinimumSize(QtCore.QSize(251, 21))
        self.Commentaire.setObjectName("Commentaire")
        self.verticalLayout_3.addWidget(self.Commentaire)
        spacerItem4 = QtGui.QSpacerItem(265, 48, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtGui.QSpacerItem(118, 27, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.bOk = QtGui.QPushButton(self.Widget8)
        self.bOk.setMinimumSize(QtCore.QSize(160, 30))
        self.bOk.setMaximumSize(QtCore.QSize(160, 30))
        self.bOk.setAutoDefault(True)
        self.bOk.setDefault(False)
        self.bOk.setObjectName("bOk")
        self.horizontalLayout_3.addWidget(self.bOk)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.tabuniqueinto.addTab(self.Widget8, "")
        self.gridLayout_4.addWidget(self.tabuniqueinto, 0, 0, 1, 1)

        self.retranslateUi(DPlusBase)
        QtCore.QMetaObject.connectSlotsByName(DPlusBase)
        DPlusBase.setTabOrder(self.LEValeur, self.tabuniqueinto)
        DPlusBase.setTabOrder(self.tabuniqueinto, self.bOk)
        DPlusBase.setTabOrder(self.bOk, self.bImport)
        DPlusBase.setTabOrder(self.bImport, self.LBValeurs)
        DPlusBase.setTabOrder(self.LBValeurs, self.BView2D)

    def retranslateUi(self, DPlusBase):
        DPlusBase.setWindowTitle(QtGui.QApplication.translate("DPlusBase", "DUnIn", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1.setText(QtGui.QApplication.translate("DPlusBase", "<u><font size=\"+1\">Valeur(s) actuelle(s)</font></u>", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_2.setText(QtGui.QApplication.translate("DPlusBase", "<font size=\"+1\">Valeur</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.BAjout1Val.setToolTip(QtGui.QApplication.translate("DPlusBase", "ajoute la valeur saisie sous l occurence selectionnée (en fin de liste si il n y a pas de selection)", None, QtGui.QApplication.UnicodeUTF8))
        self.BSup1Val.setToolTip(QtGui.QApplication.translate("DPlusBase", "enleve l occurence selectionnee", None, QtGui.QApplication.UnicodeUTF8))
        self.BSalome.setToolTip(QtGui.QApplication.translate("DPlusBase", "ajoute la valeur saisie sous l occurence selectionnée (en fin de liste si il n y a pas de selection)", None, QtGui.QApplication.UnicodeUTF8))
        self.BView2D.setText(QtGui.QApplication.translate("DPlusBase", "Visualiser", None, QtGui.QApplication.UnicodeUTF8))
        self.bParam.setToolTip(QtGui.QApplication.translate("DPlusBase", "suppression du mot clef", None, QtGui.QApplication.UnicodeUTF8))
        self.bParam.setText(QtGui.QApplication.translate("DPlusBase", "&Parametres", None, QtGui.QApplication.UnicodeUTF8))
        self.bParam.setShortcut(QtGui.QApplication.translate("DPlusBase", "Alt+P", None, QtGui.QApplication.UnicodeUTF8))
        self.bImport.setToolTip(QtGui.QApplication.translate("DPlusBase", "suppression du mot clef", None, QtGui.QApplication.UnicodeUTF8))
        self.bImport.setText(QtGui.QApplication.translate("DPlusBase", "&Importer", None, QtGui.QApplication.UnicodeUTF8))
        self.bImport.setShortcut(QtGui.QApplication.translate("DPlusBase", "Alt+I", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setToolTip(QtGui.QApplication.translate("DPlusBase", "validation de la saisie", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setText(QtGui.QApplication.translate("DPlusBase", "&Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setShortcut(QtGui.QApplication.translate("DPlusBase", "Shift+A, Alt+A, Alt+A, Alt+A", None, QtGui.QApplication.UnicodeUTF8))
        self.tabuniqueinto.setTabText(self.tabuniqueinto.indexOf(self.Widget8), QtGui.QApplication.translate("DPlusBase", "Saisir Valeur", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DPlusBase = QtGui.QWidget()
    ui = Ui_DPlusBase()
    ui.setupUi(DPlusBase)
    DPlusBase.show()
    sys.exit(app.exec_())

