# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desPoursuite.ui'
#
# Created: Fri Oct 10 11:42:29 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DPour(object):
    def setupUi(self, DPour):
        DPour.setObjectName("DPour")
        DPour.resize(521,544)
        DPour.setMinimumSize(QtCore.QSize(505,0))
        self.gridlayout = QtGui.QGridLayout(DPour)
        self.gridlayout.setObjectName("gridlayout")
        self.TWChoix = QtGui.QTabWidget(DPour)
        self.TWChoix.setObjectName("TWChoix")
        self.MotClef = QtGui.QWidget()
        self.MotClef.setGeometry(QtCore.QRect(0,0,499,433))
        self.MotClef.setObjectName("MotClef")
        self.gridLayout_4 = QtGui.QGridLayout(self.MotClef)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textLabel1 = QtGui.QLabel(self.MotClef)
        self.textLabel1.setMinimumSize(QtCore.QSize(0,0))
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.gridLayout_4.addWidget(self.textLabel1,0,0,1,1)
        self.textLabel1_2 = QtGui.QLabel(self.MotClef)
        self.textLabel1_2.setWordWrap(False)
        self.textLabel1_2.setObjectName("textLabel1_2")
        self.gridLayout_4.addWidget(self.textLabel1_2,0,1,1,1)
        self.LBMCPermis = QtGui.QListWidget(self.MotClef)
        self.LBMCPermis.setMinimumSize(QtCore.QSize(0,0))
        self.LBMCPermis.setObjectName("LBMCPermis")
        self.gridLayout_4.addWidget(self.LBMCPermis,1,0,1,1)
        self.LBRegles = QtGui.QListWidget(self.MotClef)
        self.LBRegles.setObjectName("LBRegles")
        self.gridLayout_4.addWidget(self.LBRegles,1,1,1,1)
        self.TWChoix.addTab(self.MotClef,"")
        self.Commande = QtGui.QWidget()
        self.Commande.setGeometry(QtCore.QRect(0,0,499,433))
        self.Commande.setObjectName("Commande")
        self.gridLayout_3 = QtGui.QGridLayout(self.Commande)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textLabel1_4 = QtGui.QLabel(self.Commande)
        self.textLabel1_4.setWordWrap(False)
        self.textLabel1_4.setObjectName("textLabel1_4")
        self.gridLayout_3.addWidget(self.textLabel1_4,0,0,1,3)
        self.groupBox = QtGui.QGroupBox(self.Commande)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.RBalpha = QtGui.QRadioButton(self.groupBox)
        self.RBalpha.setChecked(True)
        self.RBalpha.setObjectName("RBalpha")
        self.gridLayout.addWidget(self.RBalpha,0,0,1,1)
        self.RBGroupe = QtGui.QRadioButton(self.groupBox)
        self.RBGroupe.setObjectName("RBGroupe")
        self.gridLayout.addWidget(self.RBGroupe,1,0,1,1)
        self.gridLayout_3.addWidget(self.groupBox,0,3,2,1)
        self.textLabel6 = QtGui.QLabel(self.Commande)
        self.textLabel6.setMinimumSize(QtCore.QSize(50,30))
        self.textLabel6.setWordWrap(False)
        self.textLabel6.setObjectName("textLabel6")
        self.gridLayout_3.addWidget(self.textLabel6,1,0,1,1)
        self.LEFiltre = QtGui.QLineEdit(self.Commande)
        self.LEFiltre.setMinimumSize(QtCore.QSize(160,30))
        self.LEFiltre.setObjectName("LEFiltre")
        self.gridLayout_3.addWidget(self.LEFiltre,1,1,1,1)
        self.pushButton = QtGui.QPushButton(self.Commande)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton,1,2,1,1)
        self.LBNouvCommande = QtGui.QListWidget(self.Commande)
        self.LBNouvCommande.setObjectName("LBNouvCommande")
        self.gridLayout_3.addWidget(self.LBNouvCommande,2,0,1,4)
        self.textLabel4 = QtGui.QLabel(self.Commande)
        self.textLabel4.setWordWrap(False)
        self.textLabel4.setObjectName("textLabel4")
        self.gridLayout_3.addWidget(self.textLabel4,3,0,1,4)
        self.TWChoix.addTab(self.Commande,"")
        self.TabPage = QtGui.QWidget()
        self.TabPage.setGeometry(QtCore.QRect(0,0,499,433))
        self.TabPage.setObjectName("TabPage")
        self.gridLayout_2 = QtGui.QGridLayout(self.TabPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textLabel1_3 = QtGui.QLabel(self.TabPage)
        self.textLabel1_3.setWordWrap(False)
        self.textLabel1_3.setObjectName("textLabel1_3")
        self.gridLayout_2.addWidget(self.textLabel1_3,0,0,1,1)
        self.LENomFichier = QtGui.QLineEdit(self.TabPage)
        self.LENomFichier.setMinimumSize(QtCore.QSize(470,40))
        self.LENomFichier.setObjectName("LENomFichier")
        self.gridLayout_2.addWidget(self.LENomFichier,1,0,1,1)
        spacerItem = QtGui.QSpacerItem(21,190,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem,2,0,1,1)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem1 = QtGui.QSpacerItem(331,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.BBrowse = QtGui.QPushButton(self.TabPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BBrowse.sizePolicy().hasHeightForWidth())
        self.BBrowse.setSizePolicy(sizePolicy)
        self.BBrowse.setMinimumSize(QtCore.QSize(140,50))
        self.BBrowse.setObjectName("BBrowse")
        self.hboxlayout.addWidget(self.BBrowse)
        self.gridLayout_2.addLayout(self.hboxlayout,3,0,1,1)
        spacerItem2 = QtGui.QSpacerItem(21,87,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2,4,0,1,1)
        self.TWChoix.addTab(self.TabPage,"")
        self.gridlayout.addWidget(self.TWChoix,0,0,1,3)
        self.bSup = QtGui.QPushButton(DPour)
        self.bSup.setMinimumSize(QtCore.QSize(0,30))
        self.bSup.setAutoDefault(True)
        self.bSup.setObjectName("bSup")
        self.gridlayout.addWidget(self.bSup,2,0,1,1)
        self.bOk = QtGui.QPushButton(DPour)
        self.bOk.setMinimumSize(QtCore.QSize(0,30))
        self.bOk.setAutoDefault(True)
        self.bOk.setDefault(True)
        self.bOk.setObjectName("bOk")
        self.gridlayout.addWidget(self.bOk,2,1,1,1)
        self.bHelp = QtGui.QPushButton(DPour)
        self.bHelp.setMinimumSize(QtCore.QSize(0,30))
        self.bHelp.setAutoDefault(True)
        self.bHelp.setObjectName("bHelp")
        self.gridlayout.addWidget(self.bHelp,2,2,1,1)
        self.Commentaire = QtGui.QLabel(DPour)
        self.Commentaire.setWordWrap(False)
        self.Commentaire.setObjectName("Commentaire")
        self.gridlayout.addWidget(self.Commentaire,1,0,1,3)

        self.retranslateUi(DPour)
        self.TWChoix.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DPour)
        DPour.setTabOrder(self.LEFiltre,self.LENomFichier)
        DPour.setTabOrder(self.LENomFichier,self.TWChoix)
        DPour.setTabOrder(self.TWChoix,self.LBMCPermis)
        DPour.setTabOrder(self.LBMCPermis,self.LBRegles)
        DPour.setTabOrder(self.LBRegles,self.LBNouvCommande)
        DPour.setTabOrder(self.LBNouvCommande,self.RBalpha)
        DPour.setTabOrder(self.RBalpha,self.BBrowse)
        DPour.setTabOrder(self.BBrowse,self.bSup)
        DPour.setTabOrder(self.bSup,self.bOk)
        DPour.setTabOrder(self.bOk,self.bHelp)

    def retranslateUi(self, DPour):
        DPour.setWindowTitle(QtGui.QApplication.translate("DPour", "DMacro", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1.setText(QtGui.QApplication.translate("DPour", "<h3><p align=\"center\"><u><b>Mots Clefs Permis</b></u></p></h3>", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_2.setText(QtGui.QApplication.translate("DPour", "<h3><p align=\"center\"><u><b>Régles</b></u></p></h3>", None, QtGui.QApplication.UnicodeUTF8))
        self.TWChoix.setTabText(self.TWChoix.indexOf(self.MotClef), QtGui.QApplication.translate("DPour", "Ajouter Mot-Clef", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_4.setText(QtGui.QApplication.translate("DPour", "<b><u>Commandes :</u></b>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DPour", "Affichage", None, QtGui.QApplication.UnicodeUTF8))
        self.RBalpha.setText(QtGui.QApplication.translate("DPour", "alphabétique", None, QtGui.QApplication.UnicodeUTF8))
        self.RBGroupe.setText(QtGui.QApplication.translate("DPour", "par groupe", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel6.setText(QtGui.QApplication.translate("DPour", "Filtre", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("DPour", "Suivant", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4.setText(QtGui.QApplication.translate("DPour", "La commande choisie sera ajoutée APRES la commande courante", None, QtGui.QApplication.UnicodeUTF8))
        self.TWChoix.setTabText(self.TWChoix.indexOf(self.Commande), QtGui.QApplication.translate("DPour", "Nouvelle Commande", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_3.setText(QtGui.QApplication.translate("DPour", "<font size=\"+1\">La commande POURSUITE requiert un nom de Fichier :</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.BBrowse.setText(QtGui.QApplication.translate("DPour", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.TWChoix.setTabText(self.TWChoix.indexOf(self.TabPage), QtGui.QApplication.translate("DPour", "Fichier Poursuite", None, QtGui.QApplication.UnicodeUTF8))
        self.bSup.setToolTip(QtGui.QApplication.translate("DPour", "suppression du mot clef", None, QtGui.QApplication.UnicodeUTF8))
        self.bSup.setText(QtGui.QApplication.translate("DPour", "&Supprimer", None, QtGui.QApplication.UnicodeUTF8))
        self.bSup.setShortcut(QtGui.QApplication.translate("DPour", "Alt+S", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setToolTip(QtGui.QApplication.translate("DPour", "validation de la saisie", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setText(QtGui.QApplication.translate("DPour", "&Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setShortcut(QtGui.QApplication.translate("DPour", "Shift+A, Alt+A, Alt+A, Alt+A", None, QtGui.QApplication.UnicodeUTF8))
        self.bHelp.setToolTip(QtGui.QApplication.translate("DPour", "affichage documentation aster", None, QtGui.QApplication.UnicodeUTF8))
        self.bHelp.setText(QtGui.QApplication.translate("DPour", "&Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.bHelp.setShortcut(QtGui.QApplication.translate("DPour", "Alt+D", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DPour = QtGui.QWidget()
    ui = Ui_DPour()
    ui.setupUi(DPour)
    DPour.show()
    sys.exit(app.exec_())

