# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desUniqueBase.ui'
#
# Created: Fri Apr 24 14:36:52 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DUnBase(object):
    def setupUi(self, DUnBase):
        DUnBase.setObjectName("DUnBase")
        DUnBase.resize(482, 480)
        DUnBase.setMinimumSize(QtCore.QSize(350, 0))
        self.gridlayout = QtGui.QGridLayout(DUnBase)
        self.gridlayout.setObjectName("gridlayout")
        self.tabuniqueinto = QtGui.QTabWidget(DUnBase)
        self.tabuniqueinto.setObjectName("tabuniqueinto")
        self.Widget8 = QtGui.QWidget()
        self.Widget8.setObjectName("Widget8")
        self.gridLayout = QtGui.QGridLayout(self.Widget8)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textLabel2 = QtGui.QLabel(self.Widget8)
        self.textLabel2.setWordWrap(False)
        self.textLabel2.setObjectName("textLabel2")
        self.horizontalLayout.addWidget(self.textLabel2)
        self.lineEditVal = QtGui.QLineEdit(self.Widget8)
        self.lineEditVal.setMinimumSize(QtCore.QSize(290, 50))
        self.lineEditVal.setObjectName("lineEditVal")
        self.horizontalLayout.addWidget(self.lineEditVal)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 4)
        spacerItem = QtGui.QSpacerItem(137, 43, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.bParametres = QtGui.QPushButton(self.Widget8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bParametres.sizePolicy().hasHeightForWidth())
        self.bParametres.setSizePolicy(sizePolicy)
        self.bParametres.setMinimumSize(QtCore.QSize(140, 45))
        self.bParametres.setObjectName("bParametres")
        self.gridLayout.addWidget(self.bParametres, 1, 3, 2, 1)
        spacerItem1 = QtGui.QSpacerItem(293, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 3)
        self.BSalome = QtGui.QPushButton(self.Widget8)
        self.BSalome.setMinimumSize(QtCore.QSize(142, 40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image240.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BSalome.setIcon(icon)
        self.BSalome.setObjectName("BSalome")
        self.gridLayout.addWidget(self.BSalome, 3, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(138, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(137, 77, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 2, 2, 1)
        self.BView2D = QtGui.QPushButton(self.Widget8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BView2D.sizePolicy().hasHeightForWidth())
        self.BView2D.setSizePolicy(sizePolicy)
        self.BView2D.setMinimumSize(QtCore.QSize(140, 40))
        self.BView2D.setObjectName("BView2D")
        self.gridLayout.addWidget(self.BView2D, 3, 3, 1, 1)
        self.BFichier = QtGui.QPushButton(self.Widget8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BFichier.sizePolicy().hasHeightForWidth())
        self.BFichier.setSizePolicy(sizePolicy)
        self.BFichier.setMinimumSize(QtCore.QSize(140, 40))
        self.BFichier.setIcon(icon)
        self.BFichier.setObjectName("BFichier")
        self.gridLayout.addWidget(self.BFichier, 4, 3, 2, 1)
        spacerItem4 = QtGui.QSpacerItem(293, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 5, 0, 1, 3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.Commentaire = QtGui.QLabel(self.Widget8)
        self.Commentaire.setObjectName("Commentaire")
        self.verticalLayout.addWidget(self.Commentaire)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.gridLayout.addLayout(self.verticalLayout, 6, 0, 1, 4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.bOk = QtGui.QPushButton(self.Widget8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bOk.sizePolicy().hasHeightForWidth())
        self.bOk.setSizePolicy(sizePolicy)
        self.bOk.setMinimumSize(QtCore.QSize(140, 40))
        self.bOk.setAutoDefault(True)
        self.bOk.setDefault(True)
        self.bOk.setObjectName("bOk")
        self.horizontalLayout_2.addWidget(self.bOk)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.gridLayout.addLayout(self.horizontalLayout_2, 7, 0, 1, 4)
        self.tabuniqueinto.addTab(self.Widget8, "")
        self.gridlayout.addWidget(self.tabuniqueinto, 0, 0, 1, 1)

        self.retranslateUi(DUnBase)
        QtCore.QMetaObject.connectSlotsByName(DUnBase)
        DUnBase.setTabOrder(self.lineEditVal, self.bOk)
        DUnBase.setTabOrder(self.bOk, self.BSalome)
        DUnBase.setTabOrder(self.BSalome, self.BView2D)

    def retranslateUi(self, DUnBase):
        DUnBase.setWindowTitle(QtGui.QApplication.translate("DUnBase", "DUnIn", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2.setText(QtGui.QApplication.translate("DUnBase", "<b><u><p align=\"center\">Valeur: </p></u></b>", None, QtGui.QApplication.UnicodeUTF8))
        self.bParametres.setText(QtGui.QApplication.translate("DUnBase", "Parametres", None, QtGui.QApplication.UnicodeUTF8))
        self.BView2D.setText(QtGui.QApplication.translate("DUnBase", "Visualiser", None, QtGui.QApplication.UnicodeUTF8))
        self.BFichier.setText(QtGui.QApplication.translate("DUnBase", "Fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.Commentaire.setText(QtGui.QApplication.translate("DUnBase", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setToolTip(QtGui.QApplication.translate("DUnBase", "validation de la saisie", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setText(QtGui.QApplication.translate("DUnBase", "&Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setShortcut(QtGui.QApplication.translate("DUnBase", "Shift+A, Alt+A, Alt+A, Alt+A", None, QtGui.QApplication.UnicodeUTF8))
        self.tabuniqueinto.setTabText(self.tabuniqueinto.indexOf(self.Widget8), QtGui.QApplication.translate("DUnBase", "Saisir Valeur", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DUnBase = QtGui.QWidget()
    ui = Ui_DUnBase()
    ui.setupUi(DUnBase)
    DUnBase.show()
    sys.exit(app.exec_())

