# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desUniqueBase.ui'
#
# Created: Tue Nov 18 17:37:25 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DUnBase(object):
    def setupUi(self, DUnBase):
        DUnBase.setObjectName("DUnBase")
        DUnBase.resize(482,480)
        DUnBase.setMinimumSize(QtCore.QSize(350,0))
        self.gridlayout = QtGui.QGridLayout(DUnBase)
        self.gridlayout.setObjectName("gridlayout")
        self.tabuniqueinto = QtGui.QTabWidget(DUnBase)
        self.tabuniqueinto.setObjectName("tabuniqueinto")
        self.Widget8 = QtGui.QWidget()
        self.Widget8.setGeometry(QtCore.QRect(0,0,460,435))
        self.Widget8.setObjectName("Widget8")
        self.gridlayout1 = QtGui.QGridLayout(self.Widget8)
        self.gridlayout1.setObjectName("gridlayout1")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.textLabel2 = QtGui.QLabel(self.Widget8)
        self.textLabel2.setWordWrap(False)
        self.textLabel2.setObjectName("textLabel2")
        self.hboxlayout.addWidget(self.textLabel2)
        self.lineEditVal = QtGui.QLineEdit(self.Widget8)
        self.lineEditVal.setMinimumSize(QtCore.QSize(290,50))
        self.lineEditVal.setObjectName("lineEditVal")
        self.hboxlayout.addWidget(self.lineEditVal)
        self.gridlayout1.addLayout(self.hboxlayout,1,0,1,3)
        spacerItem = QtGui.QSpacerItem(288,21,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem,0,0,1,2)
        self.bParametres = QtGui.QPushButton(self.Widget8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bParametres.sizePolicy().hasHeightForWidth())
        self.bParametres.setSizePolicy(sizePolicy)
        self.bParametres.setMinimumSize(QtCore.QSize(140,30))
        self.bParametres.setObjectName("bParametres")
        self.gridlayout1.addWidget(self.bParametres,0,2,1,1)
        self.bSup = QtGui.QPushButton(self.Widget8)
        self.bSup.setMinimumSize(QtCore.QSize(0,30))
        self.bSup.setAutoDefault(True)
        self.bSup.setObjectName("bSup")
        self.gridlayout1.addWidget(self.bSup,5,0,1,1)
        self.bOk = QtGui.QPushButton(self.Widget8)
        self.bOk.setMinimumSize(QtCore.QSize(0,30))
        self.bOk.setAutoDefault(True)
        self.bOk.setDefault(True)
        self.bOk.setObjectName("bOk")
        self.gridlayout1.addWidget(self.bOk,5,1,1,1)
        self.bHelp = QtGui.QPushButton(self.Widget8)
        self.bHelp.setMinimumSize(QtCore.QSize(0,30))
        self.bHelp.setAutoDefault(True)
        self.bHelp.setObjectName("bHelp")
        self.gridlayout1.addWidget(self.bHelp,5,2,1,1)
        spacerItem1 = QtGui.QSpacerItem(41,112,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem1,2,1,1,1)
        spacerItem2 = QtGui.QSpacerItem(21,112,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem2,4,1,1,1)
        self.Commentaire = QtGui.QLabel(self.Widget8)
        self.Commentaire.setMinimumSize(QtCore.QSize(430,40))
        self.Commentaire.setWordWrap(False)
        self.Commentaire.setObjectName("Commentaire")
        self.gridlayout1.addWidget(self.Commentaire,3,0,1,3)
        self.BView2D = QtGui.QPushButton(self.Widget8)
        self.BView2D.setMinimumSize(QtCore.QSize(110,40))
        self.BView2D.setObjectName("BView2D")
        self.gridlayout1.addWidget(self.BView2D,2,2,1,1)
        self.BSalome = QtGui.QPushButton(self.Widget8)
        self.BSalome.setMinimumSize(QtCore.QSize(50,40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image240.gif"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.BSalome.setIcon(icon)
        self.BSalome.setObjectName("BSalome")
        self.gridlayout1.addWidget(self.BSalome,2,0,1,1)
        self.tabuniqueinto.addTab(self.Widget8,"")
        self.gridlayout.addWidget(self.tabuniqueinto,0,0,1,1)

        self.retranslateUi(DUnBase)
        QtCore.QMetaObject.connectSlotsByName(DUnBase)
        DUnBase.setTabOrder(self.lineEditVal,self.bOk)
        DUnBase.setTabOrder(self.bOk,self.bSup)
        DUnBase.setTabOrder(self.bSup,self.BSalome)
        DUnBase.setTabOrder(self.BSalome,self.bHelp)
        DUnBase.setTabOrder(self.bHelp,self.BView2D)
        DUnBase.setTabOrder(self.BView2D,self.bParametres)
        DUnBase.setTabOrder(self.bParametres,self.tabuniqueinto)

    def retranslateUi(self, DUnBase):
        DUnBase.setWindowTitle(QtGui.QApplication.translate("DUnBase", "DUnIn", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2.setText(QtGui.QApplication.translate("DUnBase", "<b><u><p align=\"center\">Valeur: </p></u></b>", None, QtGui.QApplication.UnicodeUTF8))
        self.bParametres.setText(QtGui.QApplication.translate("DUnBase", "Parametres", None, QtGui.QApplication.UnicodeUTF8))
        self.bSup.setToolTip(QtGui.QApplication.translate("DUnBase", "suppression du mot clef", None, QtGui.QApplication.UnicodeUTF8))
        self.bSup.setText(QtGui.QApplication.translate("DUnBase", "&Supprimer", None, QtGui.QApplication.UnicodeUTF8))
        self.bSup.setShortcut(QtGui.QApplication.translate("DUnBase", "Alt+S", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setToolTip(QtGui.QApplication.translate("DUnBase", "validation de la saisie", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setText(QtGui.QApplication.translate("DUnBase", "&Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setShortcut(QtGui.QApplication.translate("DUnBase", "Shift+A, Alt+A, Alt+A, Alt+A", None, QtGui.QApplication.UnicodeUTF8))
        self.bHelp.setToolTip(QtGui.QApplication.translate("DUnBase", "affichage documentation aster", None, QtGui.QApplication.UnicodeUTF8))
        self.bHelp.setText(QtGui.QApplication.translate("DUnBase", "&Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.bHelp.setShortcut(QtGui.QApplication.translate("DUnBase", "Alt+D", None, QtGui.QApplication.UnicodeUTF8))
        self.BView2D.setText(QtGui.QApplication.translate("DUnBase", "Visualiser", None, QtGui.QApplication.UnicodeUTF8))
        self.tabuniqueinto.setTabText(self.tabuniqueinto.indexOf(self.Widget8), QtGui.QApplication.translate("DUnBase", "Saisir Valeur", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DUnBase = QtGui.QWidget()
    ui = Ui_DUnBase()
    ui.setupUi(DUnBase)
    DUnBase.show()
    sys.exit(app.exec_())

