tiny:
	env PYTHONPATH=`pwd`:`pwd`/..:`pwd`/../Aster epydoc -n EFICASV1.5 --show-imports -o tiny_api  \
                            ../Aster/prefs.py \
                            ../Noyau/*.py \
                            ../Validation/*.py \
                            ../Ihm/*.py \
                            ../Extensions/*.py \
                            ../Accas/*.py \
                            ../Editeur/*.py \
                            ../generator/*.py \
                            ../convert/*.py \
                            ../convert/Parserv5/__init__.py \
                            ../convert/Parserv5/conv.py \
                      ../AIDE/__init__.py  ../AIDE/aide_gui.py  ../AIDE/aide_objets.py  ../AIDE/viewer.py \
                            ../Tools/*.py \
                            ../Tools/*/*.py \

